// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Account (Me), webhooks and transactions.
 */

/**
 * Me Address
 */
export const MeAddressSchema = z.looseObject({
  /**
   * Unique Address ID.
   */
  AddressID: z.string().nullable().optional(),
  /**
   * Address Line 1. Max length: 256. Required.
   */
  Line1: z.string().nullable().optional(),
  /**
   * Address Line 2. Max length: 256.
   */
  Line2: z.string().nullable().optional(),
  /**
   * City / Suburb. Max length: 256. Required.
   */
  CitySuburb: z.string().nullable().optional(),
  /**
   * State / Province. Max length: 256. Required.
   */
  StateProvince: z.string().nullable().optional(),
  /**
   * Zip / PostCode. Max length: 20. Required.
   */
  ZipPostCode: z.string().nullable().optional(),
  /**
   * Country name Required.
   */
  Country: z.string().nullable().optional(),
  /**
   * Address Type. Should be one of the following values: `Billing`, `Business` or
   * `Shipping`. Required.
   */
  Type: z.string().nullable().optional(),
  /**
   * Points that Address is used as default for chosen Type. `False` as default.
   */
  DefaultForType: z.boolean().nullable().optional()
});

export type MeAddress = z.infer<typeof MeAddressSchema>;

/**
 * Me Contact
 */
export const MeContactSchema = z.looseObject({
  /**
   * Unique MeContact ID.
   */
  ContactID: z.string().nullable().optional(),
  /**
   * Name of MeContact. Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Phone Max length: 50.
   */
  Phone: z.string().nullable().optional(),
  /**
   * Fax Max length: 50.
   */
  Fax: z.string().nullable().optional(),
  /**
   * Email Max length: 256.
   */
  Email: z.string().nullable().optional(),
  /**
   * Website Max length: 256.
   */
  Website: z.string().nullable().optional(),
  /**
   * Comment Max length: 256.
   */
  Comment: z.string().nullable().optional(),
  /**
   * MeContact Type. Should be one of the following values: `Billing`, `Business`, `Sale`,
   * `Shipping` or `Employee`. Max length: 50.
   */
  Type: z.string().nullable().optional(),
  /**
   * Points that MeContact is used as default for chosen Type. `False` as default.
   */
  DefaultForType: z.boolean().nullable().optional()
});

export type MeContact = z.infer<typeof MeContactSchema>;

/**
 * Transactions
 */
export const TransactionsSchema = z.looseObject({
  /**
   * Task ID
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Debit Account.
   */
  DebitAccountCode: z.string().nullable().optional(),
  /**
   * Credit Account.
   */
  CreditAccountCode: z.string().nullable().optional(),
  /**
   * Amount.
   */
  Amount: z.number().nullable().optional(),
  /**
   * Transaction Date
   */
  EffectiveDate: z.string().nullable().optional(),
  /**
   * Custom Reference
   */
  Reference: z.string().nullable().optional(),
  /**
   * Transaction description.
   */
  Transaction: z.string().nullable().optional(),
  /**
   * Transaction Type. Available values are
   * `InventoryWriteOff`,`StockTake`,`StockAdjustment`,`Journal`,`Disassembly`,`Depreciation`
   */
  Type: z.string().nullable().optional()
});

export type Transactions = z.infer<typeof TransactionsSchema>;

/**
 * Rounding Table Model
 */
export const RoundingTableSchema = z.looseObject({
  RangeTo: z.number().nullable().optional(),
  RoundToNearest: z.number().nullable().optional(),
  /**
   * No Ajustment (N), Add (A), Subtract (S)
   */
  AdjustmentRule: z.string().nullable().optional(),
  AdjustmentValue: z.string().nullable().optional()
});

export type RoundingTable = z.infer<typeof RoundingTableSchema>;

/**
 * ME
 */
export const MESchema = z.looseObject({
  /**
   * Your company name
   */
  Company: z.string().nullable().optional(),
  /**
   * Your company base currency
   */
  Currency: z.string().nullable().optional(),
  /**
   * Time Zone where your company located
   */
  TimeZone: z.string().nullable().optional(),
  /**
   * Unit of measure for unit weight. Available Values are values Max length: 10.
   */
  DefaultWeightUnits: z.string().nullable().optional(),
  /**
   * Unit of measure for unit length/width/height. Available Values are values Max length:
   * 10.
   */
  DefaultDimensionsUnits: z.string().nullable().optional(),
  /**
   * Financial settings option. Indicates date period start from what you can change
   * transactional data. Formatted in Tenant date format
   */
  LockDate: z.string().nullable().optional(),
  /**
   * Date of opening balances in the system. Formatted in Tenant date format
   */
  OpeningBalanceDate: z.string().nullable().optional(),
  /**
   * Indicate if tax calculation should be based on Row total or (Document) Total
   */
  TaxCalculationMethod: z.string().nullable().optional(),
  /**
   * Taxation rule ID selected by default when creating new customers
   */
  DefaultSaleTaxRuleId: z.string().nullable().optional(),
  /**
   * Taxation rule Name selected by default when creating new customers
   */
  DefaultSaleTaxRuleName: z.string().nullable().optional(),
  /**
   * Maximum decimal places in quantity on printable documents
   */
  MaximumDecimalPlacesInQuantity: z.string().nullable().optional(),
  /**
   * In some scenarios, the seller wants to add an extra discount to the selected customers
   * despite the fact that product related discounts are already applied
   */
  ApplyCustomerDiscountsAfterOtherDiscounts: z.boolean().nullable().optional(),
  /**
   * This will let the system process any available discount by either amending the sale
   * price of the item or recalculating the discount % in the sale order line for the
   * eligible item
   */
  DiscountRule: z.string().nullable().optional(),
  /**
   * Enable this option to allow Cin7 Core to automatically apply discounts and deals on
   * authorisation
   */
  AutomaticallyApplyDiscounts: z.boolean().nullable().optional(),
  /**
   * The calculated price will be rounded to the specified value and adjusted as per
   * specified rule to let you implement your special price ending/charm pricing strategy
   */
  RoundingTable: z.array(RoundingTableSchema).nullable().optional()
});

export type ME = z.infer<typeof MESchema>;
