// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Shared envelopes and helpers for the Cin7 Core API.
 */

/**
 * Standard paging envelope returned by list endpoints.
 * The collection itself is under a resource-specific key such as `SaleList`.
 */
export const PageEnvelopeSchema = z.looseObject({
  Total: z.number().nullable().optional(),
  Page: z.number().nullable().optional()
});

export type PageEnvelope = z.infer<typeof PageEnvelopeSchema>;

/**
 * Builds a page schema that unwraps a named list key.
 */
export function pageSchema<T extends z.ZodType>(listKey: string, itemSchema: T) {
  return PageEnvelopeSchema.extend({
    [listKey]: z.array(itemSchema).nullable().optional()
  });
}

/**
 * Error payload Cin7 Core returns alongside non-2xx status codes.
 */
export const ErrorSchema = z.looseObject({
  ErrorCode: z.number().nullable().optional(),
  Exception: z.string().nullable().optional(),
  /** Present on some validation failures. */
  Errors: z.array(z.string()).nullable().optional()
});

export type CoreError = z.infer<typeof ErrorSchema>;
