// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * CRM leads, opportunities and tasks.
 */

/**
 * Lead
 */
export const LeadSchema = z.looseObject({
  /**
   * Unique lead ID generated by Cin7 Core. Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Lead status. Available values are NEW, ATTEMPTING TO CONTACT, QUALIFIED, DISQUALIFIED.
   * Max length: 256. Required.
   */
  LeadStatus: z.string().nullable().optional(),
  /**
   * Name of the lead. Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Currency code of the lead. Max length: 3. Required.
   */
  Currency: z.string().nullable().optional(),
  /**
   * Payment term for the lead. Required.
   */
  PaymentTerm: z.number().nullable().optional(),
  /**
   * Price tier. Max length: 50. Required.
   */
  PriceTier: z.string().nullable().optional(),
  /**
   * Sale representative name. Max length: 256. Required.
   */
  SalesRepresentative: z.string().nullable().optional(),
  /**
   * Tax rule name for the lead. Max length: 255. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Lead value.
   */
  Amount: z.number().nullable().optional(),
  /**
   * % chance of wining a lead. Available values are 0%, 10%, 20%, 30%..... etc. Required.
   */
  CloseChance: z.number().nullable().optional(),
  /**
   * Lead deal estimated close date. Required.
   */
  CloseDate: z.string().nullable().optional(),
  /**
   * Additional comments. Max length: 2000.
   */
  Comments: z.string().nullable().optional(),
  /**
   * List of contacts.
   */
  Contacts: z.array(z.unknown()).nullable().optional(),
  /**
   * List of addresses.
   */
  Addresses: z.array(z.unknown()).nullable().optional()
});

export type Lead = z.infer<typeof LeadSchema>;

/**
 * Opportunity
 */
export const OpportunitySchema = z.looseObject({
  /**
   * Unique Cin7 Core opportunity ID. Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Customer identifier.
   */
  CustomerID: z.string().nullable().optional(),
  /**
   * Lead identifier.
   */
  LeadID: z.string().nullable().optional(),
  /**
   * Lead or customer name. Max length: 256. Required.
   */
  CustomerName: z.string().nullable().optional(),
  /**
   * Lead or customer contact name. Max length: 256.
   */
  Contact: z.string().nullable().optional(),
  /**
   * Lead or customer phone number. Max length: 50.
   */
  Phone: z.string().nullable().optional(),
  /**
   * Account code used by default for invoice lines when no revenue account is defined on
   * Product. By default it is set to default revenue account. Max length: 50.
   */
  DefaultAccount: z.string().nullable().optional(),
  /**
   * Opportunity billing address line 1. Max length: 256. Required.
   */
  BillingAddressLine1: z.string().nullable().optional(),
  /**
   * Opportunity billing address line 2. Max length: 256.
   */
  BillingAddressLine2: z.string().nullable().optional(),
  /**
   * Opportunity Currency. Max length: 3. Required.
   */
  Currency: z.string().nullable().optional(),
  /**
   * Opportunity Tax %.
   */
  TaxPercent: z.number().nullable().optional(),
  /**
   * Opportunity is tax Inclusive or Exclusive.
   */
  TaxInclusive: z.boolean().nullable().optional(),
  /**
   * Default Tax Rule name selected for opportunity. Max length: 255. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Opportunity payment term number of days.
   */
  TermDays: z.number().nullable().optional(),
  /**
   * Opportunity payment term name. Max length: 50. Required.
   */
  Terms: z.string().nullable().optional(),
  /**
   * Price Tier name selected for opportunity. Max length: 50. Required.
   */
  PriceTier: z.string().nullable().optional(),
  /**
   * Opportunity shipping address line 1. Max length: 256.
   */
  ShippingAddressLine1: z.string().nullable().optional(),
  /**
   * Opportunity shipping address line 2. Max length: 256.
   */
  ShippingAddressLine2: z.string().nullable().optional(),
  /**
   * Default location to pick stock from once converted to sale. Max length: 256. Required.
   */
  OpportunityLocation: z.string().nullable().optional(),
  /**
   * Number of opportunities. Max length: 256.
   */
  OpportunityNumber: z.string().nullable().optional(),
  /**
   * Date opportunity is created.
   */
  OpportunityDate: z.string().nullable().optional(),
  /**
   * Additional comments added on opportunity. Max length: 1024.
   */
  OpportunityComment: z.string().nullable().optional(),
  /**
   * Additional information for the opportunity. Max length: 1024.
   */
  OpportunityMemo: z.string().nullable().optional(),
  /**
   * Status of the opportunity. Possible values: Draft, In Progress, Won, Lost. Max length:
   * 25.
   */
  OpportunityStatus: z.string().nullable().optional(),
  /**
   * Total tax amount for the opportunity.
   */
  TaxTotal: z.number().nullable().optional(),
  /**
   * Total opportunity.
   */
  Total: z.number().nullable().optional(),
  /**
   * Customer reference. Max length: 256.
   */
  CustomerReference: z.string().nullable().optional(),
  /**
   * Currency conversion rate.
   */
  CurrencyConversionRate: z.number().nullable().optional(),
  /**
   * Customer Currency. Max length: 3. Required.
   */
  CustomerCurrency: z.string().nullable().optional(),
  /**
   * Required.
   */
  TermMethod: z.number().nullable().optional(),
  /**
   * Sales Representative name. Max length: 256. Required.
   */
  SalesRepresentative: z.string().nullable().optional(),
  TermDueNextMonth: z.number().nullable().optional(),
  /**
   * If false and customer or leads' address matching Line 1 not found, then a new customer/
   * lead shipping address will be created. Required.
   */
  ShipToOther: z.boolean().nullable().optional(),
  /**
   * Ship to company name when ShipToOther is true. Max length: 128.
   */
  ShipToCompany: z.string().nullable().optional(),
  /**
   * Ship to contact name when ShipToOther is true. Max length: 512.
   */
  ShipToContact: z.string().nullable().optional(),
  /**
   * Ship to country when ShipToOther is true. Max length: 64.
   */
  ShipToCountry: z.string().nullable().optional(),
  /**
   * Ship to post code when ShipToOther is true. Max length: 32.
   */
  ShipToPostCode: z.string().nullable().optional(),
  /**
   * Ship to state when ShipToOther is true. Max length: 128.
   */
  ShipToState: z.string().nullable().optional(),
  /**
   * Ship to city when ShipToOther is true. Max length: 128.
   */
  ShipToCity: z.string().nullable().optional(),
  /**
   * Ship to address line 1. Max length: 256.
   */
  ShipToAddress1: z.string().nullable().optional(),
  /**
   * Ship to address line 2. Max length: 256.
   */
  ShipToAddress2: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 1. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField1: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 2. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField2: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 3. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField3: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 4. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField4: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 5. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField5: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 6. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField6: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 7. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField7: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 8. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField8: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 9. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField9: z.string().nullable().optional(),
  /**
   * Value of opportunity additional attribute 10. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  CustomField10: z.string().nullable().optional(),
  /**
   * Opportunity line items.
   */
  Lines: z.array(z.unknown()).nullable().optional(),
  /**
   * Opportunity line additional charges. If true then additional charges lines displayed in
   * Lines array.
   */
  AdditionalCharges: z.array(z.unknown()).nullable().optional()
});

export type Opportunity = z.infer<typeof OpportunitySchema>;
