// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Customers. https://dearinventory.docs.apiary.io/#reference/customer
 */

/**
 * Customer Credits
 */
export const CustomerCreditsSchema = z.looseObject({
  /**
   * Credit ID, identifier unique key.
   */
  CreditID: z.string().nullable().optional(),
  /**
   * Customer ID
   */
  CustomerID: z.string().nullable().optional(),
  /**
   * Customer name.
   */
  CustomerName: z.string().nullable().optional(),
  /**
   * Credit account.
   */
  Account: z.string().nullable().optional(),
  /**
   * Credit amount.
   */
  Amount: z.number().nullable().optional(),
  /**
   * Credit remaining amount.
   */
  RemainingAmount: z.number().nullable().optional(),
  /**
   * Credit currency name.
   */
  Currency: z.string().nullable().optional(),
  /**
   * Currency conversion rate.
   */
  ConvRate: z.number().nullable().optional(),
  /**
   * Date paid
   */
  Date: z.string().nullable().optional(),
  /**
   * Credit description
   */
  Description: z.string().nullable().optional()
});

export type CustomerCredits = z.infer<typeof CustomerCreditsSchema>;

/**
 * Customer Default Template
 */
export const CustomerDefaultTemplateSchema = z.looseObject({
  /**
   * Customer ID. Required (conditional).
   */
  CustomerID: z.string().nullable().optional(),
  /**
   * Template ID. Required (conditional).
   */
  TemplateID: z.string().nullable().optional()
});

export type CustomerDefaultTemplate = z.infer<typeof CustomerDefaultTemplateSchema>;

/**
 * Child Customer Model
 */
export const ChildCustomerSchema = z.looseObject({
  /**
   * Customer ID
   */
  CustomerID: z.string().nullable().optional(),
  /**
   * Customer name
   */
  CustomerName: z.string().nullable().optional()
});

export type ChildCustomer = z.infer<typeof ChildCustomerSchema>;

/**
 * Address Model
 */
export const AddressSchema = z.looseObject({
  /**
   * Address ID, optional, applicable for sales only, POST/PUT methods. If specified then
   * existing address is taken by ID.
   */
  ID: z.string().nullable().optional(),
  /**
   * Address Line 1 as displayed on Sale form. = Line1 + Line2 Max length: 256.
   */
  DisplayAddressLine1: z.string().nullable().optional(),
  /**
   * Address Line 2 as displayed on Sale form. = City + State/Region + Zip/Postcode + Country
   * Max length: 256.
   */
  DisplayAddressLine2: z.string().nullable().optional(),
  /**
   * Address Line 1 Max length: 256. Required.
   */
  Line1: z.string().nullable().optional(),
  /**
   * Address Line 2 Max length: 256.
   */
  Line2: z.string().nullable().optional(),
  /**
   * City Max length: 256.
   */
  City: z.string().nullable().optional(),
  /**
   * State Max length: 256.
   */
  State: z.string().nullable().optional(),
  /**
   * Post code Max length: 20.
   */
  Postcode: z.string().nullable().optional(),
  /**
   * Country Max length: 256. Required.
   */
  Country: z.string().nullable().optional()
});

export type Address = z.infer<typeof AddressSchema>;

/**
 * Additional Attribute Model
 */
export const AdditionalAttributeSchema = z.looseObject({
  /**
   * Additional Attribute 1 value Max length: 256.
   */
  AdditionalAttribute1: z.string().nullable().optional(),
  /**
   * Additional Attribute 2 value Max length: 256.
   */
  AdditionalAttribute2: z.string().nullable().optional(),
  /**
   * Additional Attribute 3 value Max length: 256.
   */
  AdditionalAttribute3: z.string().nullable().optional(),
  /**
   * Additional Attribute 4 value Max length: 256.
   */
  AdditionalAttribute4: z.string().nullable().optional(),
  /**
   * Additional Attribute 5 value Max length: 256.
   */
  AdditionalAttribute5: z.string().nullable().optional(),
  /**
   * Additional Attribute 6 value Max length: 256.
   */
  AdditionalAttribute6: z.string().nullable().optional(),
  /**
   * Additional Attribute 7 value Max length: 256.
   */
  AdditionalAttribute7: z.string().nullable().optional(),
  /**
   * Additional Attribute 8 value Max length: 256.
   */
  AdditionalAttribute8: z.string().nullable().optional(),
  /**
   * Additional Attribute 9 value Max length: 256.
   */
  AdditionalAttribute9: z.string().nullable().optional(),
  /**
   * Additional Attribute 10 value Max length: 256.
   */
  AdditionalAttribute10: z.string().nullable().optional()
});

export type AdditionalAttribute = z.infer<typeof AdditionalAttributeSchema>;

/**
 * Customer
 */
export const CustomerSchema = z.looseObject({
  /**
   * Unique Customer ID. Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Customer name. Must be unique. Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Preferred customer name. Unlike `Name`, multiple customers can use this `DisplayName`.
   * It does not need to be unique. Max length: 256.
   */
  DisplayName: z.string().nullable().optional(),
  /**
   * Points that Customer is Active. Available values are `Active` and `Deprecated`. Required
   * for POST Required (conditional).
   */
  Status: z.string().nullable().optional(),
  /**
   * Currency code of Customer. Required.
   */
  Currency: z.string().nullable().optional(),
  /**
   * Payment term. Required.
   */
  PaymentTerm: z.string().nullable().optional(),
  /**
   * Account receivable code of Customer. Required.
   */
  AccountReceivable: z.string().nullable().optional(),
  /**
   * Sale account code of Customer. Required.
   */
  RevenueAccount: z.string().nullable().optional(),
  /**
   * Tax rule name. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Price tier.
   */
  PriceTier: z.string().nullable().optional(),
  /**
   * Carrier name.
   */
  Carrier: z.string().nullable().optional(),
  /**
   * Sales representative.
   */
  SalesRepresentative: z.string().nullable().optional(),
  /**
   * Location.
   */
  Location: z.string().nullable().optional(),
  /**
   * Discount must be between 0% and 100%.
   */
  Discount: z.number().nullable().optional(),
  /**
   * Comments. Max length: 2000.
   */
  Comments: z.string().nullable().optional(),
  /**
   * Tax number.
   */
  TaxNumber: z.number().nullable().optional(),
  /**
   * Credit limit.
   */
  CreditLimit: z.number().nullable().optional(),
  /**
   * Tags string.
   */
  Tags: z.string().nullable().optional(),
  /**
   * AttributeSet name.
   */
  AttributeSet: z.string().nullable().optional(),
  /**
   * Additional attribute value. # - int(1-10).
   */
  'AdditionalAttribute#': z.string().nullable().optional(),
  /**
   * Date of last modification.
   */
  LastModifiedOn: z.string().nullable().optional(),
  /**
   * Is On Credit Hold.
   */
  IsOnCreditHold: z.boolean().nullable().optional(),
  /**
   * `true` if a customer is a Legal Entity. Default `false`.
   */
  IsLegalEntity: z.boolean().nullable().optional(),
  /**
   * The unique Customer ID for a parent customer or `null`.
   */
  CustomerParentID: z.string().nullable().optional(),
  /**
   * Name of the parent customer. Max length: 256.
   */
  CustomerParentName: z.string().nullable().optional(),
  /**
   * Default `false`. Not available if the Parent is empty or null. If `true`, Child uses the
   * Parent's billing address and sales history.
   */
  IsBillParent: z.boolean().nullable().optional(),
  /**
   * Customer specific Product Prices.
   */
  ProductPrices: z.array(z.unknown()).nullable().optional(),
  /**
   * List of addresses.
   */
  Addresses: z.array(z.unknown()).nullable().optional(),
  /**
   * List of contacts.
   */
  Contacts: z.array(z.unknown()).nullable().optional(),
  /**
   * Customers’s child records (available only in the responses)
   */
  ChildCustomers: z.array(ChildCustomerSchema).nullable().optional()
});

export type Customer = z.infer<typeof CustomerSchema>;
