// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Products and availability. https://dearinventory.docs.apiary.io/#reference/product
 */

/**
 * Product
 */
export const ProductSchema = z.looseObject({
  /**
   * Ignored by POST action. Required for PUT action
   */
  ID: z.string().nullable().optional(),
  /**
   * Product SKU must be unique. Max length: 50. Required.
   */
  SKU: z.string().nullable().optional(),
  /**
   * Product name. Quickbooks Online limitations: maximum length is 100 characters and must
   * be unique Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Category name Max length: 256. Required.
   */
  Category: z.string().nullable().optional(),
  /**
   * Brand name Max length: 50.
   */
  Brand: z.string().nullable().optional(),
  /**
   * Product Type. Valid values: `Stock` or `Service`. Read-only for PUT. Required
   * (conditional).
   */
  Type: z.string().nullable().optional(),
  /**
   * Valid values: `FIFO`, `Special - Batch`, `Special - Serial Number`, `FIFO - Serial
   * Number`, `FIFO - Batch`, `FEFO - Batch`, `FEFO - Serial Number` Max length: 50.
   * Required.
   */
  CostingMethod: z.string().nullable().optional(),
  /**
   * One of these values: `No Drop Ship`, `Optional Drop Ship`, `Always Drop Ship`. Default
   * value is `No Drop Ship`
   */
  DropShipMode: z.string().nullable().optional(),
  /**
   * Name of the default Location for product. (Location with this name must exist in
   * reference books under locations) Max length: 50.
   */
  DefaultLocation: z.string().nullable().optional(),
  /**
   * Length dimension, Defaults to 0 Max length: 50.
   */
  Length: z.number().nullable().optional(),
  /**
   * Width dimension, Defaults to 0 Max length: 50.
   */
  Width: z.number().nullable().optional(),
  /**
   * Height dimension, Defaults to 0 Max length: 50.
   */
  Height: z.number().nullable().optional(),
  /**
   * Product Weight (in kilograms) , Defaults to 0 Max length: 50.
   */
  Weight: z.number().nullable().optional(),
  /**
   * Carton Length dimension, Defaults to 0 Max length: 50.
   */
  CartonLength: z.number().nullable().optional(),
  /**
   * Carton Width dimension, Defaults to 0 Max length: 50.
   */
  CartonWidth: z.number().nullable().optional(),
  /**
   * Carton Height dimension, Defaults to 0 Max length: 50.
   */
  CartonHeight: z.number().nullable().optional(),
  /**
   * Carton Quantity, Defaults to 0 Max length: 50.
   */
  CartonQuantity: z.number().nullable().optional(),
  /**
   * Carton Inner Quantity, Defaults to 0 Max length: 50.
   */
  CartonInnerQuantity: z.number().nullable().optional(),
  /**
   * Product Unit of Measure (A unit of measure with this name must exist in reference books
   * under units) Max length: 50. Required.
   */
  UOM: z.string().nullable().optional(),
  /**
   * Unit of measure for unit weight. Available Values are values Max length: 10.
   */
  WeightUnits: z.string().nullable().optional(),
  /**
   * Unit of measure for unit length/width/height. Available Values are values Max length:
   * 10.
   */
  DimensionsUnits: z.string().nullable().optional(),
  /**
   * Product barcode Max length: 256.
   */
  Barcode: z.string().nullable().optional(),
  /**
   * Minimum available product quantity for this product to appear on Reorder report/forms.
   * Defaults to 0
   */
  MinimumBeforeReorder: z.number().nullable().optional(),
  /**
   * Default quantity to put into purchase order when reordering this product. Not applicable
   * to reorder backordered form. Defaults to 0
   */
  ReorderQuantity: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 1 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier1: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 2 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier2: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 3 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier3: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 4 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier4: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 5 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier5: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 6 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier6: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 7 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier7: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 8 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier8: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 9 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier9: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 10 is selected in Sale Task. Up to 4 decimal
   * places.
   */
  PriceTier10: z.number().nullable().optional(),
  /**
   * Object contains list with real price tier names and values for each listed price. This
   * parameter is optional for specifying price. It's required if PriceTierN parameters are
   * not specified. IMPORTANT: It will be disabled in case if some of tenant price tiers have
   * identical names.
   */
  PriceTiers: z.unknown().nullable().optional(),
  /**
   * Read-only field. Average Unit Cost of this product. Up to 4 decimal places
   */
  AverageCost: z.number().nullable().optional(),
  /**
   * Multiline short description of the product Max length: 500.
   */
  ShortDescription: z.string().nullable().optional(),
  /**
   * Multiline description of the product
   */
  Description: z.string().nullable().optional(),
  /**
   * Internal Note Max length: 4000.
   */
  InternalNote: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 1. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute1: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 2. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute2: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 3. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute3: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 4. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute4: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 5. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute5: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 6. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute6: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 7. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute7: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 8. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute8: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 9. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute9: z.string().nullable().optional(),
  /**
   * Value of the product’s additional attribute 10. Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces Max length: 256.
   */
  AdditionalAttribute10: z.string().nullable().optional(),
  /**
   * Name of the product’s additional attribute set. Max length: 50.
   */
  AttributeSet: z.string().nullable().optional(),
  /**
   * Valid discount name (discount with this name must exist in Product Discounts reference
   * book and should be active) Max length: 128.
   */
  DiscountRule: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom tags Max length: 256.
   */
  Tags: z.string().nullable().optional(),
  /**
   * The only valid values are `Active`, `Setup required` and `Deprecated` Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Location of this product in your warehouse Max length: 256.
   */
  StockLocator: z.string().nullable().optional(),
  /**
   * Account code of an active EXPENSE class account from Chart Of Accounts. Only applicable
   * to products of type Stock and ignored for Service products. Max length: 50.
   */
  COGSAccount: z.string().nullable().optional(),
  /**
   * Account code of an active `REVENUE` class account from Chart Of Accounts Max length: 50.
   */
  RevenueAccount: z.string().nullable().optional(),
  /**
   * Account code of an active `EXPENSE` class account from Chart Of Accounts. Only
   * applicable to products of type Stock and ignored for Service products. Max length: 50.
   */
  ExpenseAccount: z.string().nullable().optional(),
  /**
   * Account code of an active `ASSET` class account from Chart Of Accounts with Type not
   * equal to FIXED or BANK. Only applicable to products of type Stock and ignored for
   * Service products. Max length: 50.
   */
  InventoryAccount: z.string().nullable().optional(),
  /**
   * Tax rule used for this product in Purchases. Tax Rule with this name must exist in
   * Taxation Rules reference book and should be Active and have For Purchases flag set to
   * “true” in API Max length: 50.
   */
  PurchaseTaxRule: z.string().nullable().optional(),
  /**
   * Tax rule used for this product in Sales. Tax Rule with this name must exist in Taxation
   * Rules reference book and should be Active and have For Sales flag set to “true” in API
   * Max length: 50.
   */
  SaleTaxRule: z.string().nullable().optional(),
  /**
   * UTC Time. Read-only.
   */
  LastModifiedOn: z.string().nullable().optional(),
  /**
   * Value for field `I am selling this product` on product page. Available values for this
   * field: `true`, `false`. If value of field is not specified then `true` will be accepted
   * by default.
   */
  Sellable: z.boolean().nullable().optional(),
  /**
   * Comma delimited list of pick zones Max length: 256.
   */
  PickZones: z.string().nullable().optional(),
  /**
   * `true` if this product can be assembled from components or disassembled to components or
   * this product is a secondary unit of measure of base product.
   */
  BillOfMaterial: z.boolean().nullable().optional(),
  /**
   * `true` if this product is a kit and should be autoassembled from components on sale
   * order authorisation or this product is a secondary unit of measure of base product.
   */
  AutoAssembly: z.boolean().nullable().optional(),
  /**
   * `true` if when receiving this product during purchase it should be automatically
   * disassembled to components or this product is a secondary unit of measure of a base
   * product.
   */
  AutoDisassembly: z.boolean().nullable().optional(),
  /**
   * Specify how many products will be assembled as per Bill of Materials. Required if
   * `BillOfMaterial` is `true` Required (conditional).
   */
  QuantityToProduce: z.number().nullable().optional(),
  /**
   * Url to external resource describing assembly instruction. Max length: 256.
   */
  AssemblyInstructionURL: z.string().nullable().optional(),
  /**
   * .Required if `BillOfMaterial` is `true` Max length: 256. Required (conditional).
   */
  AssemblyCostEstimationMethod: z.string().nullable().optional(),
  /**
   * Production BOM type. Valid values: 'Assembly', 'Production', 'Make to Order', 'None'.
   * The field is Read-only.
   */
  BOMType: z.string().nullable().optional(),
  /**
   * Specifies the HS Code used in the process of product export. It is a numeric value of
   * minimum 6 digits. Max length: 200.
   */
  HSCode: z.string().nullable().optional(),
  /**
   * Specifies the country of manufacture, production, design, or brand origin where a
   * product comes from.
   */
  CountryOfOrigin: z.string().nullable().optional(),
  /**
   * Specifies the country code of manufacture, production, design, or brand origin where a
   * product comes from.
   */
  CountryOfOriginCode: z.string().nullable().optional(),
  Suppliers: z.array(z.unknown()).nullable().optional(),
  ReorderLevels: z.array(z.unknown()).nullable().optional(),
  BillOfMaterialsProducts: z.array(z.unknown()).nullable().optional(),
  BillOfMaterialsServices: z.array(z.unknown()).nullable().optional(),
  Movements: z.array(z.unknown()).nullable().optional(),
  Attachments: z.array(z.unknown()).nullable().optional(),
  /**
   * Customer specific Product Prices.
   */
  CustomPrices: z.array(z.unknown()).nullable().optional()
});

export type Product = z.infer<typeof ProductSchema>;

/**
 * Product Availability
 */
export const ProductAvailabilitySchema = z.looseObject({
  /**
   * Product ID.
   */
  ID: z.string().nullable().optional(),
  /**
   * SKU of Product. Max length: 50.
   */
  SKU: z.string().nullable().optional(),
  /**
   * Name of Product. Max length: 256.
   */
  Name: z.string().nullable().optional(),
  /**
   * Barcode of Product. Max length: 256.
   */
  Barcode: z.string().nullable().optional(),
  /**
   * Name of product location. Max length: 256.
   */
  Location: z.string().nullable().optional(),
  /**
   * Binof product location. Max length: 50.
   */
  Bin: z.string().nullable().optional(),
  /**
   * Batch.
   */
  Batch: z.string().nullable().optional(),
  /**
   * Expiry Date.
   */
  ExpiryDate: z.string().nullable().optional(),
  /**
   * On Hand.
   */
  OnHand: z.number().nullable().optional(),
  /**
   * Allocated.
   */
  Allocated: z.number().nullable().optional(),
  /**
   * Available.
   */
  Available: z.number().nullable().optional(),
  /**
   * OnOrder.
   */
  OnOrder: z.number().nullable().optional(),
  /**
   * StockOnHand.
   */
  StockOnHand: z.number().nullable().optional(),
  /**
   * In Transit.
   */
  InTransit: z.number().nullable().optional(),
  /**
   * Next delivery date.
   */
  NextDeliveryDate: z.string().nullable().optional()
});

export type ProductAvailability = z.infer<typeof ProductAvailabilitySchema>;

/**
 * Available Fields for ProductCategory
 */
export const ProductCategorySchema = z.looseObject({
  /**
   * Required for PUT, Ignored for POST operations
   */
  ID: z.string().nullable().optional(),
  /**
   * Category name for product Max length: 50. Required.
   */
  Name: z.string().nullable().optional()
});

export type ProductCategory = z.infer<typeof ProductCategorySchema>;

/**
 * Product Family
 */
export const ProductFamilySchema = z.looseObject({
  /**
   * List of Products included in the Family.
   */
  Products: z.array(z.unknown()).nullable().optional(),
  /**
   * Unique ID. Ignored by POST action. Required for PUT action
   */
  ID: z.string().nullable().optional(),
  /**
   * Must be unique. Product Family SKU, used to generate Product SKUs Max length: 45.
   * Required.
   */
  SKU: z.string().nullable().optional(),
  /**
   * Product Family name, used to generate Product names Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Category name Max length: 256. Required.
   */
  Category: z.string().nullable().optional(),
  /**
   * Brand name Max length: 256.
   */
  Brand: z.string().nullable().optional(),
  /**
   * Valid values: `FIFO`, `Special - Batch`, `Special - Serial Number`, `FIFO - Serial
   * Number`, `FIFO - Batch`, `FEFO - Batch`, `FEFO - Serial Number` Required.
   */
  CostingMethod: z.string().nullable().optional(),
  /**
   * Name of the default Location for product family. (Location with this name must exist in
   * Reference Books>Locations and Bins) Max length: 256. Required.
   */
  DefaultLocation: z.string().nullable().optional(),
  /**
   * Unit of Measure (Unit of measure with this name must exist in Reference Books > Units of
   * Measure) Max length: 0. Required.
   */
  UOM: z.string().nullable().optional(),
  /**
   * Minimum available product quantity for this product to appear on Reorder report/forms.
   * Defaults to 0
   */
  MinimumBeforeReorder: z.number().nullable().optional(),
  /**
   * Default quantity to put into purchase order when reordering this product. Not applicable
   * to reorder backordered form. Defaults to 0
   */
  ReorderQuantity: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 1 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier1: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 2 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier2: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 3 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier3: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 4 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier4: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 5 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier5: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 6 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier6: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 7 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier7: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 8 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier8: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 9 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier9: z.number().nullable().optional(),
  /**
   * Product Sale Price used when Price Tier 10 is selected in Sale Task. Up to 4 decimal
   * places
   */
  PriceTier10: z.number().nullable().optional(),
  /**
   * Multiline short description of the product Max length: 500.
   */
  ShortDescription: z.string().nullable().optional(),
  /**
   * Multiline description of the product family
   */
  Description: z.string().nullable().optional(),
  /**
   * Name of the product’s additional attribute set. Max length: 50.
   */
  AttributeSet: z.string().nullable().optional(),
  /**
   * Valid discount name (discount with this name must exist in Product Discounts reference
   * book and should be active) Max length: 128.
   */
  DiscountRule: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom tags Max length: 256.
   */
  Tags: z.string().nullable().optional(),
  /**
   * Account code of an active EXPENSE class account from Chart Of Accounts. Max length: 50.
   */
  COGSAccount: z.string().nullable().optional(),
  /**
   * Account code of an active REVENUE class account from Chart Of Accounts. Max length: 50.
   */
  RevenueAccount: z.string().nullable().optional(),
  /**
   * Account code of an active ASSET class account from Chart Of Accounts with Type not equal
   * to FIXED or BANK. Max length: 50.
   */
  InventoryAccount: z.string().nullable().optional(),
  /**
   * Tax rule used for this product in Purchases. Tax Rule with this name must exist in
   * Reference Books> Taxation Rules and should be Active. Purchases flag needs to be set to
   * true in API. Max length: 50.
   */
  PurchaseTaxRule: z.string().nullable().optional(),
  /**
   * Tax rule used for this product in Sales. Tax Rule with this name must exist in Reference
   * Books > Taxation Rules and should be Active. Sales flag needs to be set to true in API.
   * Max length: 50.
   */
  SaleTaxRule: z.string().nullable().optional(),
  /**
   * One of these values: `No Drop Ship`, `Optional Drop Ship`, `Always Drop Ship`. Default
   * value is `No Drop Ship`.
   */
  DropShipMode: z.string().nullable().optional(),
  /**
   * Family Option 1 name. I.e. Size, Colour, etc. Defaults to Option 1 Max length: 50.
   * Required.
   */
  Option1Name: z.string().nullable().optional(),
  /**
   * Family Option 2 name. I.e. Size, Colour, etc. Defaults to Option 1 Max length: 50.
   */
  Option2Name: z.string().nullable().optional(),
  /**
   * Family Option 3 name. I.e. Size, Colour, etc. Defaults to Option 1 Max length: 50.
   */
  Option3Name: z.string().nullable().optional(),
  /**
   * Comma-delimited list of all possible values for Option 1. Combination of unique values
   * of Option 1 Value for product family products. Read-only.
   */
  Option1Values: z.string().nullable().optional(),
  /**
   * Comma-delimited list of all possible values for Option 2. Combination of unique values
   * of Option 1 Value for product family products. Read-only.
   */
  Option2Values: z.string().nullable().optional(),
  /**
   * Comma-delimited list of all possible values for Option 3. Combination of unique values
   * of Option 1 Value for product family products. Read-only.
   */
  Option3Values: z.string().nullable().optional(),
  /**
   * UTC Time
   */
  LastModifiedOn: z.string().nullable().optional(),
  Attachments: z.array(z.unknown()).nullable().optional(),
  /**
   * Specifies the HS Codes used in the process of product export. It is a numeric value of
   * minimum 6 digits. Max length: 200.
   */
  HSCode: z.string().nullable().optional(),
  /**
   * Specifies the country of manufacture, production, design, or brand origin where a
   * product comes from.
   */
  CountryOfOrigin: z.string().nullable().optional(),
  /**
   * Specifies the country code of manufacture, production, design, or brand origin where a
   * product comes from.
   */
  CountryOfOriginCode: z.string().nullable().optional()
});

export type ProductFamily = z.infer<typeof ProductFamilySchema>;
