// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Production BOM, orders and runs.
 */

/**
 * Production BOM Component
 */
export const ProductionBOMComponentSchema = z.looseObject({
  /**
   * Identifier of a Production BOM Resource. Required.
   */
  BOMComponentID: z.string().nullable().optional(),
  /**
   * Required.
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Required.
   */
  ProductSKU: z.string().nullable().optional(),
  /**
   * Readonly
   */
  ProductName: z.string().nullable().optional(),
  /**
   * Component Quantity should be a positive value. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Can be specified insead of WastagePercent.
   */
  WastageQty: z.number().nullable().optional(),
  /**
   * Can be specified insead of WastageQty. Max length: 0 - 100.
   */
  WastagePercent: z.number().nullable().optional(),
  /**
   * Readonly
   */
  Cost: z.number().nullable().optional(),
  /**
   * Readonly
   */
  CostingMethod: z.string().nullable().optional(),
  /**
   * Readonly
   */
  Unit: z.string().nullable().optional(),
  /**
   * Required.
   */
  Position: z.number().nullable().optional(),
  /**
   * Used only in Buy/Sell co-man operation. Max length: 1 - 10.
   */
  SalePriceTier: z.number().nullable().optional(),
  /**
   * Used only when IssueMethodComponent = Backflush and IssueMethodParameter =
   * BackflushForComponent
   */
  IsBackflush: z.boolean().nullable().optional()
});

export type ProductionBOMComponent = z.infer<typeof ProductionBOMComponentSchema>;

/**
 * Production BOM Resource
 */
export const ProductionBOMResourceSchema = z.looseObject({
  /**
   * Identifier of a Production BOM Resource. Required.
   */
  BOMResourceID: z.string().nullable().optional(),
  /**
   * Required.
   */
  ResourceID: z.string().nullable().optional(),
  /**
   * Readonly
   */
  ResourceName: z.string().nullable().optional(),
  /**
   * Readonly
   */
  ResourceCode: z.string().nullable().optional(),
  /**
   * Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Readonly
   */
  Cost: z.number().nullable().optional(),
  /**
   * Readonly
   */
  CycleTime: z.number().nullable().optional(),
  /**
   * Required.
   */
  Position: z.number().nullable().optional(),
  /**
   * Available values . Required.
   */
  CostCalculationType: z.string().nullable().optional()
});

export type ProductionBOMResource = z.infer<typeof ProductionBOMResourceSchema>;

/**
 * Production Order
 */
export const ProductionOrderSchema = z.looseObject({
  /**
   * Unique identifier of Production Order. Required for Update action. Required.
   */
  ProductionOrderID: z.string().nullable().optional(),
  /**
   * Unique identifier of Product. Required.
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU.
   */
  ProductSKU: z.string().nullable().optional(),
  /**
   * Product Name.
   */
  ProductName: z.string().nullable().optional(),
  /**
   * Production Order Number.
   */
  OrderNumber: z.string().nullable().optional(),
  /**
   * Production Order Location ID. Required.
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Production Order Location Name.
   */
  LocationName: z.string().nullable().optional(),
  /**
   * CostingMethod of Product (FIFO, FEFO etc.).
   */
  CostingMethod: z.string().nullable().optional(),
  /**
   * Readonly.
   */
  WarehouseName: z.string().nullable().optional(),
  /**
   * Readonly.
   */
  Unit: z.string().nullable().optional(),
  /**
   * Production Order execution status (DRAFT, PLANNED, RELEASED, IN PROGRESS, COMPLETED,
   * VOIDED). Readonly.
   */
  OrderStatus: z.string().nullable().optional(),
  /**
   * Production Order status (DRAFT, AUTHORIZED, RELEASED, VOIDED). Readonly.
   */
  Status: z.string().nullable().optional(),
  /**
   * Readonly.
   */
  InstructionURL: z.string().nullable().optional(),
  /**
   * Manual, Sale, SmartReorder.
   */
  SourceName: z.string().nullable().optional(),
  /**
   * Obsolete. Unique identifier of Sale Task that produced the current Production Order
   * record.
   */
  SourceTaskID: z.string().nullable().optional(),
  /**
   * Obsolete. Number of Sale Task that produced the current Production Order record.
   */
  SourceTaskNumber: z.string().nullable().optional(),
  /**
   * Work In Progress Account Code.
   */
  WIPAccountCode: z.string().nullable().optional(),
  /**
   * Finished Goods Account Code.
   */
  FinishedGoodsAccountCode: z.string().nullable().optional(),
  /**
   * Production Order Quantity.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Production BOM origin Quantity. Readonly.
   */
  BOMQuantity: z.number().nullable().optional(),
  /**
   * Type of the capacity calculation method. Available values are `FromStartForward` and
   * `FromRequiredBackward`.
   */
  CapacityCalculationType: z.string().nullable().optional(),
  /**
   * Production Order Planned Date. Required when CapacityCalculationType = FromStartForward.
   */
  StartDate: z.string().nullable().optional(),
  /**
   * Production Order Release Date.
   */
  ReleaseDate: z.string().nullable().optional(),
  /**
   * Production Order Required By Date. Required when CapacityCalculationType =
   * FromRequiredBackward.
   */
  RequiredByDate: z.string().nullable().optional(),
  /**
   * Production Order Completion Date. Readonly.
   */
  CompletionDate: z.string().nullable().optional(),
  /**
   * Readonly.
   */
  IsIgnoreLeadTime: z.boolean().nullable().optional(),
  /**
   * Readonly.
   */
  WarehouseID: z.string().nullable().optional(),
  /**
   * Readonly.
   */
  RetailID: z.string().nullable().optional(),
  /**
   * Max length: 2000.
   */
  Comments: z.string().nullable().optional(),
  /**
   * Readonly.
   */
  ScheduleStart: z.string().nullable().optional(),
  /**
   * Readonly. Max length: 2000.
   */
  PlannedBy: z.string().nullable().optional(),
  /**
   * Readonly. Max length: 2000.
   */
  ReleasedBy: z.string().nullable().optional(),
  /**
   * In seconds.
   */
  OrderCycleTime: z.number().nullable().optional(),
  /**
   * Readonly.
   */
  BOMVersion: z.number().nullable().optional(),
  /**
   * Readonly.
   */
  BOMName: z.string().nullable().optional(),
  Tags: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 1 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField1: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 2 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField2: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 3 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField3: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 4 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField4: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 5 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField5: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 6 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField6: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 7 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField7: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 8 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField8: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 9 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField9: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 10 Date format: Use `yyyy-mm-dd`
   * Numeric format: Enter a number with max 4 decimal palces
   */
  CustomField10: z.string().nullable().optional(),
  ProductionOrderOperations: z.array(z.unknown()).nullable().optional(),
  ProductionRuns: z.array(z.unknown()).nullable().optional(),
  ProductionOrderDeliveryTo: z.array(z.unknown()).nullable().optional(),
  /**
   * Readonly. Can be Manual = 1, Backflush = 2.
   */
  IssueMethodComponent: z.string().nullable().optional(),
  /**
   * Readonly. Ignored when IssueMethodComponent = Manual. Possible values: BackflushForBOM =
   * 1, BackflushForOperation = 2, BackflushForComponent = 3
   */
  IssueMethodParameter: z.string().nullable().optional(),
  /**
   * Readonly. Data of Sale Tasks that produced the current Production Order record.
   */
  SourceTasks: z.array(z.unknown()).nullable().optional(),
  /**
   * Readonly. Run Size specified in Production BOM
   */
  RunSize: z.number().nullable().optional()
});

export type ProductionOrder = z.infer<typeof ProductionOrderSchema>;

/**
 * Production Order List Item
 */
export const ProductionOrderListItemSchema = z.looseObject({
  /**
   * Unique identifier of returned record (Production Order or Production Order Run).
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Unique identifier of Production Order.
   */
  ProductionOrderID: z.string().nullable().optional(),
  /**
   * Type of the returned record. Available values are `O` - Production Order and `R` -
   * Production Order Run.
   */
  Type: z.string().nullable().optional(),
  /**
   * Unique identifier of Product.
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU.
   */
  ProductSKU: z.string().nullable().optional(),
  /**
   * Product Name.
   */
  ProductName: z.string().nullable().optional(),
  /**
   * Production Order Number.
   */
  OrderNumber: z.string().nullable().optional(),
  /**
   * Production Order Location ID.
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Production Order Location Name.
   */
  LocationName: z.string().nullable().optional(),
  /**
   * Production Order state (DRAFT, AUTHORIZED, RELEASED, VOIDED).
   */
  Status: z.string().nullable().optional(),
  /**
   * Production Order status (DRAFT, PLANNED, RELEASED, IN PROGRESS, COMPLETED, VOIDED).
   */
  OrderStatus: z.string().nullable().optional(),
  /**
   * Production Order Quantity.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Production Order Start Date.
   */
  StartDate: z.string().nullable().optional(),
  /**
   * Production Order Release Date.
   */
  ReleaseDate: z.string().nullable().optional(),
  /**
   * Production Order Required By Date.
   */
  RequiredByDate: z.string().nullable().optional(),
  /**
   * Production Order Completion Date.
   */
  CompletionDate: z.string().nullable().optional(),
  /**
   * Comments. Max length: 2000.
   */
  Comments: z.string().nullable().optional(),
  /**
   * Capacity calculation method. Available values are `FromStartForward` and
   * `FromRequiredBackward`.
   */
  CapacityCalculationType: z.string().nullable().optional(),
  /**
   * Work In Progress Account Code.
   */
  WIPAccountCode: z.string().nullable().optional(),
  /**
   * Tags string.
   */
  Tags: z.string().nullable().optional(),
  /**
   * Finished Goods Account Code.
   */
  FinishedGoodsAccountCode: z.string().nullable().optional(),
  /**
   * Obsolete. Unique identifier of Sale Task that produced the current Production Order
   * record.
   */
  SourceTaskID: z.string().nullable().optional(),
  /**
   * Obsolete. Number of Sale Task that produced the current Production Order record.
   */
  SourceTaskNumber: z.string().nullable().optional(),
  /**
   * Obsolete. Type of Sale Task that produced the current Production Order record. Available
   * values are `0` - Simple and `1` - Master
   */
  SourceTaskType: z.number().nullable().optional(),
  /**
   * Obsolete. True if source Sale Task is voided.
   */
  IsSourceTaskVoided: z.boolean().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 1 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField1: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 2 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField2: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 3 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField3: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 4 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField4: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 5 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField5: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 6 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField6: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 7 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField7: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 8 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField8: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 9 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField9: z.string().nullable().optional(),
  /**
   * Value of Production Order's additional attribute 10 Date format: Use `yyyy-mm-dd`
   * Numeric format: Enter a number with max 4 decimal palces
   */
  CustomField10: z.string().nullable().optional(),
  /**
   * Readonly. Data of Sale Tasks that produced the current Production Order record.
   */
  SourceTasks: z.array(z.unknown()).nullable().optional()
});

export type ProductionOrderListItem = z.infer<typeof ProductionOrderListItemSchema>;

/**
 * Finished Goods
 */
export const FinishedGoodsSchema = z.looseObject({
  /**
   * Unique ID.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Assembly Number
   */
  AssemblyNumber: z.string().nullable().optional(),
  /**
   * Finished Goods Task Status. Available values are `DRAFT`,`AUTHORISED`,`IN
   * PROGRESS`,`COMPLETED`,`VOIDED`
   */
  Status: z.string().nullable().optional(),
  /**
   * Product ID
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product Code
   */
  ProductCode: z.string().nullable().optional(),
  /**
   * Product Name
   */
  ProductName: z.string().nullable().optional(),
  /**
   * Location ID
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Location Name
   */
  Location: z.string().nullable().optional(),
  /**
   * Bin ID
   */
  BinID: z.string().nullable().optional(),
  /**
   * Bin Name
   */
  Bin: z.number().nullable().optional(),
  /**
   * Work in Progress Account
   */
  WIPAccount: z.string().nullable().optional(),
  /**
   * Work in Progress Date
   */
  WIPDate: z.string().nullable().optional(),
  /**
   * Finished Goods Account
   */
  Account: z.string().nullable().optional(),
  /**
   * Quantity
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Assembly Instruction URL
   */
  AssemblyInstructionURL: z.string().nullable().optional(),
  /**
   * Completion Date
   */
  CompletionDate: z.string().nullable().optional(),
  /**
   * Batch serial number
   */
  BatchSN: z.string().nullable().optional(),
  /**
   * Batch Expiry Date
   */
  ExpiryDate: z.string().nullable().optional(),
  /**
   * Notes
   */
  Notes: z.string().nullable().optional(),
  OrderLines: z.array(z.unknown()).nullable().optional(),
  PickLines: z.array(z.unknown()).nullable().optional(),
  Transactions: z.array(z.unknown()).nullable().optional(),
  /**
   * If While processing `POST` method, some errors occurred, but task was created, this
   * property will contain array of error messages.
   */
  Errors: z.array(z.unknown()).nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 1 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField1: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 2 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField2: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 3 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField3: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 4 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField4: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 5 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField5: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 6 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField6: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 7 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField7: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 8 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField8: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 9 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField9: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 10 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField10: z.string().nullable().optional()
});

export type FinishedGoods = z.infer<typeof FinishedGoodsSchema>;

/**
 * Finished Goods List
 */
export const FinishedGoodsListSchema = z.looseObject({
  /**
   * Unique ID.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Assembly Number
   */
  AssemblyNumber: z.string().nullable().optional(),
  /**
   * Batch serial number
   */
  BatchSN: z.string().nullable().optional(),
  /**
   * Batch Expiry Date
   */
  ExpiryDate: z.string().nullable().optional(),
  /**
   * Product ID
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product Code
   */
  ProductCode: z.string().nullable().optional(),
  /**
   * Product Name
   */
  ProductName: z.string().nullable().optional(),
  /**
   * Quantity
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Location ID
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Location Name
   */
  Location: z.string().nullable().optional(),
  /**
   * Date
   */
  Date: z.string().nullable().optional(),
  /**
   * Finished Goods Task Status. Available values are `DRAFT`,`AUTHORISED`,`IN
   * PROGRESS`,`COMPLETED`,`VOIDED`
   */
  Status: z.string().nullable().optional(),
  /**
   * Unit Cost
   */
  UnitCost: z.number().nullable().optional(),
  /**
   * Notes
   */
  Notes: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 1 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField1: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 2 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField2: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 3 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField3: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 4 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField4: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 5 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField5: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 6 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField6: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 7 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField7: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 8 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField8: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 9 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField9: z.string().nullable().optional(),
  /**
   * Value of Finished Goods additional attribute 10 Date format: Use `yyyy-mm-dd` Numeric
   * format: Enter a number with max 4 decimal palces
   */
  CustomField10: z.string().nullable().optional()
});

export type FinishedGoodsList = z.infer<typeof FinishedGoodsListSchema>;

/**
 * Disassembly
 */
export const DisassemblySchema = z.looseObject({
  /**
   * Unique ID.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Disassembly Number
   */
  DisassemblyNumber: z.string().nullable().optional(),
  /**
   * Disassembly Task Status. Available values are `DRAFT`,`WORK IN
   * PROGRESS`,`COMPLETED`,`VOIDED`
   */
  Status: z.string().nullable().optional(),
  /**
   * Product ID
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product Code
   */
  ProductCode: z.string().nullable().optional(),
  /**
   * Product Name
   */
  ProductName: z.string().nullable().optional(),
  /**
   * Location ID
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Location Name
   */
  Location: z.string().nullable().optional(),
  /**
   * Work in Progress Account
   */
  WIPAccount: z.string().nullable().optional(),
  /**
   * Quantity
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Assembly Instruction URL
   */
  AssemblyInstructionURL: z.string().nullable().optional(),
  PickLines: z.array(z.unknown()).nullable().optional(),
  OrderLines: z.array(z.unknown()).nullable().optional(),
  OrderServiceLines: z.array(z.unknown()).nullable().optional(),
  Transactions: z.array(z.unknown()).nullable().optional(),
  /**
   * If While processing `POST` method, some errors occurred, but task was created, this
   * property will contain array of error messages.
   */
  Errors: z.array(z.unknown()).nullable().optional()
});

export type Disassembly = z.infer<typeof DisassemblySchema>;

/**
 * Disassembly List
 */
export const DisassemblyListSchema = z.looseObject({
  /**
   * Unique ID.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Disassembly Number
   */
  DisassemblyNumber: z.string().nullable().optional(),
  /**
   * Product ID
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product Code
   */
  ProductCode: z.string().nullable().optional(),
  /**
   * Product Name
   */
  ProductName: z.string().nullable().optional(),
  /**
   * Quantity
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Location ID
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Location Name
   */
  Location: z.string().nullable().optional(),
  /**
   * Date
   */
  Date: z.string().nullable().optional(),
  /**
   * Disassembly Task Status. Available values are `DRAFT`,`WORK IN
   * PROGRESS`,`COMPLETED`,`VOIDED`
   */
  Status: z.string().nullable().optional()
});

export type DisassemblyList = z.infer<typeof DisassemblyListSchema>;

/**
 * Journal
 */
export const JournalSchema = z.looseObject({
  /**
   * Unique ID. Required for PUT Required (conditional).
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Journal Status. Available values are `DRAFT`, `COMPLETED`, `VOIDED` Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Journal Number. Read-only.
   */
  JournalNumber: z.string().nullable().optional(),
  /**
   * Currency code. Required.
   */
  Currency: z.string().nullable().optional(),
  /**
   * Conversion rate between tenant currency and `Currency` currency. Required.
   */
  CurrencyConversionRate: z.number().nullable().optional(),
  /**
   * Effective Date. Required.
   */
  EffectiveDate: z.string().nullable().optional(),
  /**
   * Narration
   */
  Narration: z.string().nullable().optional(),
  /**
   * Notes
   */
  Notes: z.string().nullable().optional(),
  Lines: z.array(z.unknown()).nullable().optional(),
  Attachments: z.array(z.unknown()).nullable().optional()
});

export type Journal = z.infer<typeof JournalSchema>;

/**
 * Production Order Operation Attachment
 */
export const ProductionOrderOperationAttachmentSchema = z.looseObject({
  /**
   * Unique identifier of Production Order Operation Attachment. Required for Update action.
   * Required (conditional).
   */
  AttachmentID: z.string().nullable().optional(),
  /**
   * Max length: 256.
   */
  FileName: z.string().nullable().optional(),
  /**
   * Readonly
   */
  Date: z.string().nullable().optional(),
  /**
   * Max length: 256. Required.
   */
  ContentType: z.string().nullable().optional(),
  /**
   * Required.
   */
  Position: z.number().nullable().optional(),
  /**
   * Base64 string of binary file content. Required when attachment is being created.
   * Required (conditional).
   */
  Content: z.string().nullable().optional()
});

export type ProductionOrderOperationAttachment = z.infer<
  typeof ProductionOrderOperationAttachmentSchema
>;

/**
 * Production Order Operation Note
 */
export const ProductionOrderOperationNoteSchema = z.looseObject({
  /**
   * Unique identifier of Production Order Operation Note. Required for Update action.
   * Required (conditional).
   */
  NoteID: z.string().nullable().optional(),
  /**
   * Max length: 4000.
   */
  Note: z.string().nullable().optional(),
  /**
   * Required.
   */
  Position: z.number().nullable().optional()
});

export type ProductionOrderOperationNote = z.infer<typeof ProductionOrderOperationNoteSchema>;

/**
 * Production BOM Attachment
 */
export const ProductionBOMAttachmentSchema = z.looseObject({
  /**
   * Identifier of a Production BOM Attachment. Required.
   */
  AttachmentID: z.string().nullable().optional(),
  /**
   * Max length: 256.
   */
  FileName: z.string().nullable().optional(),
  /**
   * Readonly
   */
  Date: z.string().nullable().optional(),
  /**
   * Required.
   */
  ContentType: z.string().nullable().optional(),
  /**
   * Base64 string of binary file content. Required.
   */
  Content: z.string().nullable().optional(),
  /**
   * Required.
   */
  Position: z.number().nullable().optional()
});

export type ProductionBOMAttachment = z.infer<typeof ProductionBOMAttachmentSchema>;

/**
 * Production BOM Note
 */
export const ProductionBOMNoteSchema = z.looseObject({
  /**
   * Identifier of a Production BOM Note. Required.
   */
  NoteID: z.string().nullable().optional(),
  /**
   * Yes Max length: 4000.
   */
  Note: z.string().nullable().optional(),
  /**
   * Required.
   */
  Position: z.number().nullable().optional()
});

export type ProductionBOMNote = z.infer<typeof ProductionBOMNoteSchema>;

/**
 * Production BOM Operation Link
 */
export const ProductionBOMOperationLinkSchema = z.looseObject({
  /**
   * Identifier of a Production BOM Operation Link. Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Required.
   */
  RelatedOperationID: z.string().nullable().optional(),
  /**
   * Max length: 200. Required.
   */
  RelatedOperationName: z.string().nullable().optional(),
  /**
   * Possible value: 1 Max length: 0+. Required.
   */
  RelationType: z.number().nullable().optional()
});

export type ProductionBOMOperationLink = z.infer<typeof ProductionBOMOperationLinkSchema>;

/**
 * Production Order Operation
 */
export const ProductionOrderOperationSchema = z.looseObject({
  /**
   * Unique identifier of Production Order Operation. Required for Update action. Required
   * (conditional).
   */
  OperationID: z.string().nullable().optional(),
  /**
   * Operation sequence number. Max length: 1+. Required.
   */
  Order: z.number().nullable().optional(),
  /**
   * Product SKU. Max length: 200. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * In seconds. Max length: 0+. Required.
   */
  CycleTime: z.number().nullable().optional(),
  /**
   * Max length: 0+. Required.
   */
  UnitsPerCycle: z.number().nullable().optional(),
  /**
   * Max length: 1+. Required.
   */
  TotalCycleTime: z.number().nullable().optional(),
  /**
   * Max length: 0+.
   */
  TotalUnitsPerCycle: z.number().nullable().optional(),
  /**
   * Manufacturing, Setup, QA.
   */
  OperationType: z.string().nullable().optional(),
  WorkCenterID: z.string().nullable().optional(),
  WorkCenterName: z.string().nullable().optional(),
  WorkCenterCode: z.string().nullable().optional(),
  /**
   * Only for CoMan workcenters. Readonly. Transfer or Buysell.
   */
  WorkCenterCoManProcurementType: z.string().nullable().optional(),
  /**
   * Readonly.
   */
  ComponentLocationID: z.string().nullable().optional(),
  /**
   * For CoMan operations only.
   */
  IsDropShip: z.boolean().nullable().optional(),
  Attachments: z.array(ProductionOrderOperationAttachmentSchema).nullable().optional(),
  Components: z.array(z.unknown()).nullable().optional(),
  Notes: z.array(ProductionOrderOperationNoteSchema).nullable().optional(),
  Resources: z.array(z.unknown()).nullable().optional(),
  OperationLinks: z.array(z.unknown()).nullable().optional(),
  InputProducts: z.array(z.unknown()).nullable().optional(),
  OutputProducts: z.array(z.unknown()).nullable().optional(),
  FinishedProducts: z.array(z.unknown()).nullable().optional(),
  /**
   * No
   */
  IsBackflush: z.boolean().nullable().optional()
});

export type ProductionOrderOperation = z.infer<typeof ProductionOrderOperationSchema>;

/**
 * Production BOM Operation
 */
export const ProductionBOMOperationSchema = z.looseObject({
  /**
   * Identifier of a Production BOM Operation. Required.
   */
  OperationID: z.string().nullable().optional(),
  /**
   * Required.
   */
  Order: z.number().nullable().optional(),
  /**
   * Max length: 200. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Cycle Time should be a positive value. Specified in seconds. Required.
   */
  CycleTime: z.number().nullable().optional(),
  /**
   * Required.
   */
  UnitsPerCycle: z.number().nullable().optional(),
  /**
   * Required.
   */
  WorkCenterID: z.string().nullable().optional(),
  /**
   * Max length: 256.
   */
  WorkCenterName: z.string().nullable().optional(),
  /**
   * Readonly, can be Transfer or BuySell, is returned for Co-man workcenters only.
   */
  WorkCenterCoManProcurementType: z.string().nullable().optional(),
  /**
   * Available values . Required.
   */
  OperationType: z.string().nullable().optional(),
  DeliveryToID: z.string().nullable().optional(),
  /**
   * Max length: 256.
   */
  DeliveryToName: z.string().nullable().optional(),
  /**
   * Readonly, can be Manual = 1, Backflush = 2, DerivedFromProductFamily = 3, ExternalApi =
   * 4.
   */
  IssueMethod: z.string().nullable().optional(),
  /**
   * Required.
   */
  IsDropShip: z.boolean().nullable().optional(),
  Resources: z.array(ProductionBOMResourceSchema).nullable().optional(),
  Components: z.array(ProductionBOMComponentSchema).nullable().optional(),
  Attachments: z.array(ProductionBOMAttachmentSchema).nullable().optional(),
  Notes: z.array(ProductionBOMNoteSchema).nullable().optional(),
  OperationLinks: z.array(ProductionBOMOperationLinkSchema).nullable().optional(),
  InputProducts: z.array(z.unknown()).nullable().optional(),
  OutputProducts: z.array(z.unknown()).nullable().optional(),
  FinishedProducts: z.array(z.unknown()).nullable().optional(),
  /**
   * Used only when IssueMethodComponent = Backflush and IssueMethodParameter =
   * BackflushForOperation
   */
  IsBackflush: z.boolean().nullable().optional()
});

export type ProductionBOMOperation = z.infer<typeof ProductionBOMOperationSchema>;

/**
 * Production BOM
 */
export const ProductionBOMSchema = z.looseObject({
  /**
   * Identifier of a Production BOM. Required.
   */
  BOMID: z.string().nullable().optional(),
  /**
   * Required.
   */
  OutputQuantity: z.number().nullable().optional(),
  /**
   * Required.
   */
  BufferPercent: z.number().nullable().optional(),
  InstructionUrl: z.string().nullable().optional(),
  /**
   * Default = false
   */
  IgnoreCumulativeLeadTime: z.boolean().nullable().optional(),
  /**
   * Required when IgnoreCumulativeLeadTime is set to 'true'. Default = 0.
   */
  ComponentProductionLeadTime: z.number().nullable().optional(),
  /**
   * Required.
   */
  Version: z.number().nullable().optional(),
  /**
   * Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Required.
   */
  IsDefault: z.boolean().nullable().optional(),
  IsTracing: z.boolean().nullable().optional(),
  /**
   * Location: Bin / Location.
   */
  DeliveryToID: z.string().nullable().optional(),
  /**
   * Max length: 256.
   */
  DeliveryToName: z.string().nullable().optional(),
  /**
   * Readonly, can be Manual = 1, DerivedFromProductFamily = 3, ExternalApi = 4.
   */
  IssueMethod: z.string().nullable().optional(),
  Operations: z.array(ProductionBOMOperationSchema).nullable().optional(),
  /**
   * Can be Manual = 1, Backflush = 2
   */
  IssueMethodComponent: z.string().nullable().optional(),
  /**
   * Ignored when IssueMethodComponent = Manual. Possible values: BackflushForBOM = 1,
   * BackflushForOperation = 2, BackflushForComponent = 3
   */
  IssueMethodParameter: z.string().nullable().optional(),
  /**
   * Minimum Quantity to Produce Per Production Order defines the minimum quantity threshold
   * to initiate the Production Order creation. If this quantity is not met, Production Order
   * is not created automatically based on the Sales Order.
   */
  MinQuantity: z.number().nullable().optional(),
  /**
   * Maximum Quantity to Produce Per Production Order defines the maximum quantity threshold
   * to split the Production Order while creating. If this quantity is met, Production Order
   * is split into several Production Orders based on Max Quantity To Produce Per Production
   * Order.
   */
  MaxQuantity: z.number().nullable().optional(),
  /**
   * Order Quantity Deviation % defines the deviation from Min/Max Quantity to Produce Per
   * Production Order. If Order Quantity Deviation % is set to 0, the Min/Max Quantity to
   * Produce Per Production Order is a fixed quantity.
   */
  DeviationPercent: z.number().nullable().optional(),
  /**
   * Run Size defines the multiplicity factor for Production Run.
   */
  RunSize: z.number().nullable().optional()
});

export type ProductionBOM = z.infer<typeof ProductionBOMSchema>;
