// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Purchases and nested purchase documents. https://dearinventory.docs.apiary.io/#reference/purchase
 */

/**
 * Purchase List
 */
export const PurchaseListSchema = z.looseObject({
  /**
   * Unique Cin7 Core Purchase identifier
   */
  ID: z.string().nullable().optional(),
  /**
   * Specifies, if Purchase is a Blind Receipt order (no purchase order)
   */
  BlindReceipt: z.boolean().nullable().optional(),
  /**
   * Purchase Order number generated by Cin7 Core Max length: 256.
   */
  OrderNumber: z.string().nullable().optional(),
  /**
   * Current Purchase status. Current sale status. Possible values are values Max length: 50.
   */
  Status: z.string().nullable().optional(),
  /**
   * Date when Purchase Order was created
   */
  OrderDate: z.string().nullable().optional(),
  /**
   * Date when Invoice was issued
   */
  InvoiceDate: z.string().nullable().optional(),
  /**
   * Name of the Supplier Max length: 256.
   */
  Supplier: z.string().nullable().optional(),
  /**
   * Identifier of Supplier.
   */
  SupplierID: z.string().nullable().optional(),
  /**
   * Invoice number issued by Supplier Max length: 256.
   */
  InvoiceNumber: z.string().nullable().optional(),
  /**
   * Total Invoice amount in Supplier currency
   */
  InvoiceAmount: z.number().nullable().optional(),
  /**
   * Total Paid amount minus Refunded amount in Supplier currency
   */
  PaidAmount: z.number().nullable().optional(),
  /**
   * Date when invoice is due according to selected payment terms
   */
  InvoiceDueDate: z.string().nullable().optional(),
  /**
   * Date when shipment is due
   */
  RequiredBy: z.string().nullable().optional(),
  /**
   * 3 digit Base currency code (as configured in General Settings) Max length: 3.
   */
  BaseCurrency: z.string().nullable().optional(),
  /**
   * 3 digit Supplier currency code Max length: 3.
   */
  SupplierCurrency: z.string().nullable().optional(),
  /**
   * Credit note number issued by Supplier. Is empty unless credit note is created Max
   * length: 256.
   */
  CreditNoteNumber: z.string().nullable().optional(),
  /**
   * Purchase Order status. Possible Values are `VOIDED`, DRAFT`, `AUTHORISED`, `NOT
   * AVAILABLE` Max length: 20.
   */
  OrderStatus: z.string().nullable().optional(),
  /**
   * Purchase stock received status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`,
   * `NOT AVAILABLE` Max length: 20.
   */
  StockReceivedStatus: z.string().nullable().optional(),
  /**
   * Invoice status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE` Max
   * length: 20.
   */
  UnstockStatus: z.string().nullable().optional(),
  /**
   * Purchase unstock status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT
   * AVAILABLE` Max length: 20.
   */
  InvoiceStatus: z.string().nullable().optional(),
  /**
   * Credit Note status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE`
   * Max length: 20.
   */
  CreditNoteStatus: z.string().nullable().optional(),
  /**
   * Date and time when purchase task was created of last time modified
   */
  LastUpdatedDate: z.string().nullable().optional(),
  /**
   * Combined Put Away status. Possible Values are `FULLY RECEIVED`, `PARTIALLY RECEIVED`,
   * `NOT AVAILABLE`, `NOT RECEIVED`, `VOIDED` Max length: 20. Required.
   */
  CombinedReceivingStatus: z.string().nullable().optional(),
  /**
   * Combined Invoice status. Possible Values are `INVOICED`, `INVOICED / CREDITED`, `NOT
   * AVAILABLE`, `NOT INVOICED`, `PARTIALLY INVOICED`, `PARTIALLY INVOICED / CREDITED` Max
   * length: 20. Required.
   */
  CombinedInvoiceStatus: z.string().nullable().optional(),
  /**
   * Payment status. Possible Values are `PREPAID`, `PARTIALLY PAID`, `UNPAID`, `PAID`,
   * `OVERPAID / CREDITED`, `VOIDED` Max length: 20. Required.
   */
  CombinedPaymentStatus: z.string().nullable().optional(),
  /**
   * Type of Purchase. Possible Values are `Simple Purchase`, `Advanced Purchase` , `Service
   * Purchase` Max length: 20. Required.
   */
  Type: z.string().nullable().optional(),
  /**
   * Specifies, if Purchase is a `Service Purchase`
   */
  IsServiceOnly: z.boolean().nullable().optional(),
  /**
   * ID of sale which created drop ship pruchase
   */
  DropShipTaskID: z.string().nullable().optional()
});

export type PurchaseList = z.infer<typeof PurchaseListSchema>;

/**
 * Purchase Order Line Model
 */
export const PurchaseOrderLineSchema = z.looseObject({
  /**
   * Product identifier referenced by this Line. Required If CombineAdditionalCharges param
   * exist for this endpoint and it have values = `false` Required (conditional).
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU referenced by this Line. Required If CombineAdditionalCharges param exist
   * for this endpoint and it have values = `false` Max length: 50. Required (conditional).
   */
  SKU: z.string().nullable().optional(),
  /**
   * Product Name referenced by this Line Max length: 1024. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Supplier SKU referenced by this line. Max length: 50.
   */
  SupplierSKU: z.string().nullable().optional(),
  /**
   * Comment for this line Max length: 256.
   */
  Comment: z.string().nullable().optional(),
  /**
   * Line Total. For validation Required.
   */
  Total: z.number().nullable().optional()
});

export type PurchaseOrderLine = z.infer<typeof PurchaseOrderLineSchema>;

/**
 * Purchase Stock Line Model
 */
export const PurchaseStockLineSchema = z.looseObject({
  /**
   * Date when items were received Required.
   */
  Date: z.string().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Product identifier referenced by this Line. Required (conditional).
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU referenced by this Line Max length: 50. Required (conditional).
   */
  SKU: z.string().nullable().optional(),
  /**
   * Read-only. Product name referenced by this Line Max length: 1024.
   */
  Name: z.string().nullable().optional(),
  /**
   * Location where the product would be stock to/from. Required if LocationID is empty. Max
   * length: 256. Required (conditional).
   */
  Location: z.string().nullable().optional(),
  /**
   * LocationID where the product would be stock to/from. Required if Location is empty.
   * Required (conditional).
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Flag, which indicates if items were received. Read-only.
   */
  Received: z.boolean().nullable().optional(),
  /**
   * Batch Serial Number Max length: 50.
   */
  BatchSN: z.string().nullable().optional(),
  /**
   * Supplier SKU referenced by this line. Max length: 50.
   */
  SupplierSKU: z.string().nullable().optional(),
  /**
   * Date when selected Batch expires
   */
  ExpiryDate: z.string().nullable().optional(),
  /**
   * Stock Batch ID
   */
  CardID: z.string().nullable().optional()
});

export type PurchaseStockLine = z.infer<typeof PurchaseStockLineSchema>;

/**
 * Purchase Invoice Line Model
 */
export const PurchaseInvoiceLineSchema = z.looseObject({
  /**
   * Product identifier referenced by this Line. Required If CombineAdditionalCharges param
   * exist for this endpoint and it have values = `false` Required (conditional).
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU referenced by this Line. Required If CombineAdditionalCharges param exist
   * for this endpoint and it have values = `false` Max length: 50. Required (conditional).
   */
  SKU: z.string().nullable().optional(),
  /**
   * Product Name referenced by this Line Max length: 1024. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Revenue account Max length: 50. Required.
   */
  Account: z.string().nullable().optional(),
  /**
   * Comment for this line Max length: 256.
   */
  Comment: z.string().nullable().optional(),
  /**
   * Line Total. For validation Required.
   */
  Total: z.number().nullable().optional()
});

export type PurchaseInvoiceLine = z.infer<typeof PurchaseInvoiceLineSchema>;

/**
 * Purchase Invoice Additional Charge Model
 */
export const PurchaseInvoiceAdditionalChargeSchema = z.looseObject({
  /**
   * Name of Service Product referenced by this Line Max length: 256. Required.
   */
  Description: z.string().nullable().optional(),
  /**
   * Comment for this Line Max length: 256.
   */
  Reference: z.string().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Revenue account Max length: 50. Required.
   */
  Account: z.string().nullable().optional(),
  /**
   * Line Total. For validation
   */
  Total: z.number().nullable().optional()
});

export type PurchaseInvoiceAdditionalCharge = z.infer<typeof PurchaseInvoiceAdditionalChargeSchema>;

/**
 * Purchase Credit Note
 */
export const PurchaseCreditNoteSchema = z.looseObject({
  /**
   * Unique Cin7 Core Purchase Task ID Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * if `true` then `additional charges` lines displayed in `Lines` array Required.
   */
  CombineAdditionalCharges: z.boolean().nullable().optional(),
  /**
   * Credit Note Number Required.
   */
  CreditNoteNumber: z.string().nullable().optional(),
  /**
   * Credit Note Date Required.
   */
  CreditNoteDate: z.string().nullable().optional(),
  /**
   * Purchase Credit Note Status. Possible Values are `NOT
   * AVAILABLE`,`DRAFT`,`AUTHORISED`,`VOIDED`. For POST only `DRAFT` and `AUTHORISED` values
   * accepted Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Required.
   */
  Lines: z.array(PurchaseInvoiceLineSchema).nullable().optional(),
  AdditionalCharges: z.array(PurchaseInvoiceAdditionalChargeSchema).nullable().optional(),
  /**
   * Required.
   */
  Unstock: z.array(z.unknown()).nullable().optional(),
  /**
   * Sum of order lines and additional charges without taxes. Not required for POST.
   */
  TotalBeforeTax: z.number().nullable().optional(),
  /**
   * Sum of order lines and additional charges taxes. Not required for POST.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Sum of order lines and additional charges with taxes. Not required for POST.
   */
  Total: z.number().nullable().optional()
});

export type PurchaseCreditNote = z.infer<typeof PurchaseCreditNoteSchema>;

/**
 * Purchase Credit Note List
 */
export const PurchaseCreditNoteListSchema = z.looseObject({
  /**
   * Unique Cin7 Core Purchase identifier
   */
  ID: z.string().nullable().optional(),
  /**
   * Specifies, if Purchase is a Blind Receipt order (no purchase order)
   */
  BlindReceipt: z.boolean().nullable().optional(),
  /**
   * Purchase Order number generated by Cin7 Core Max length: 256.
   */
  OrderNumber: z.string().nullable().optional(),
  /**
   * Current Purchase status. Current sale status. Possible values are values Max length: 50.
   */
  Status: z.string().nullable().optional(),
  /**
   * Date when Purchase Order was created
   */
  OrderDate: z.string().nullable().optional(),
  /**
   * Date when Invoice was issued
   */
  InvoiceDate: z.string().nullable().optional(),
  /**
   * Name of the Supplier Max length: 256.
   */
  Supplier: z.string().nullable().optional(),
  /**
   * Identifier of Supplier.
   */
  SupplierID: z.string().nullable().optional(),
  /**
   * Invoice number issued by Supplier Max length: 256.
   */
  InvoiceNumber: z.string().nullable().optional(),
  /**
   * Total Invoice amount in Supplier currency
   */
  InvoiceAmount: z.number().nullable().optional(),
  /**
   * Total Paid amount minus Refunded amount in Supplier currency
   */
  PaidAmount: z.number().nullable().optional(),
  /**
   * Date when invoice is due according to selected payment terms
   */
  InvoiceDueDate: z.string().nullable().optional(),
  /**
   * Date when shipment is due
   */
  RequiredBy: z.string().nullable().optional(),
  /**
   * 3 digit Base currency code (as configured in General Settings) Max length: 3.
   */
  BaseCurrency: z.string().nullable().optional(),
  /**
   * 3 digit Supplier currency code Max length: 3.
   */
  SupplierCurrency: z.string().nullable().optional(),
  /**
   * Credit note number issued by Supplier. Is empty unless credit note is created Max
   * length: 256.
   */
  CreditNoteNumber: z.string().nullable().optional(),
  /**
   * Purchase Order status. Possible Values are `VOIDED`, DRAFT`, `AUTHORISED`, `NOT
   * AVAILABLE` Max length: 20.
   */
  OrderStatus: z.string().nullable().optional(),
  /**
   * Purchase stock received status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`,
   * `NOT AVAILABLE` Max length: 20.
   */
  StockReceivedStatus: z.string().nullable().optional(),
  /**
   * Invoice status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE` Max
   * length: 20.
   */
  UnstockStatus: z.string().nullable().optional(),
  /**
   * Purchase unstock status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT
   * AVAILABLE` Max length: 20.
   */
  InvoiceStatus: z.string().nullable().optional(),
  /**
   * Credit Note status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE`
   * Max length: 20.
   */
  CreditNoteStatus: z.string().nullable().optional(),
  /**
   * Date and time when purchase task was created of last time modified
   */
  LastUpdatedDate: z.string().nullable().optional(),
  /**
   * Combined Put Away status. Possible Values are `FULLY RECEIVED`, `PARTIALLY RECEIVED`,
   * `NOT AVAILABLE`, `NOT RECEIVED`, `VOIDED` Max length: 20. Required.
   */
  CombinedReceivingStatus: z.string().nullable().optional(),
  /**
   * Combined Invoice status. Possible Values are `INVOICED`, `INVOICED / CREDITED`, `NOT
   * AVAILABLE`, `NOT INVOICED`, `PARTIALLY INVOICED`, `PARTIALLY INVOICED / CREDITED` Max
   * length: 20. Required.
   */
  CombinedInvoiceStatus: z.string().nullable().optional(),
  /**
   * Payment status. Possible Values are `PREPAID`, `PARTIALLY PAID`, `UNPAID`, `PAID`,
   * `OVERPAID / CREDITED`, `VOIDED` Max length: 20. Required.
   */
  CombinedPaymentStatus: z.string().nullable().optional(),
  /**
   * Type of Purchase. Possible Values are `Simple Purchase`, `Advanced Purchase` , `Service
   * Purchase`, `Purchase Credit Note`, `Credit Note` Max length: 20. Required.
   */
  Type: z.string().nullable().optional(),
  /**
   * Specifies, if Purchase is a `Service Purchase`
   */
  IsServiceOnly: z.boolean().nullable().optional(),
  /**
   * ID of sale which created drop ship pruchase
   */
  DropShipTaskID: z.string().nullable().optional()
});

export type PurchaseCreditNoteList = z.infer<typeof PurchaseCreditNoteListSchema>;

/**
 * Purchase Payments
 */
export const PurchasePaymentsSchema = z.looseObject({
  /**
   * Unique Cin7 Core Purchase Task ID. Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Identifier of payment. Available for PUT Required (conditional).
   */
  ID: z.string().nullable().optional(),
  /**
   * Available values are `PREPAYMENT`,`PAYMENT`,`REFUND`. Available for POST Required.
   */
  Type: z.string().nullable().optional(),
  /**
   * Payment reference number. Available for POST/PUT
   */
  Reference: z.string().nullable().optional(),
  /**
   * Payment amount in customer currency. Available for POST/PUT. For PUT is not available
   * when payment is a deposit. Required.
   */
  Amount: z.number().nullable().optional(),
  /**
   * Date when payment has been made. Available for POST/PUT Required.
   */
  DatePaid: z.string().nullable().optional(),
  /**
   * Account Code of the bank/payment account from Chart of accounts. Available for POST/PUT.
   * For PUT is not available when payment is a deposit. Required.
   */
  Account: z.string().nullable().optional(),
  /**
   * Currency Conversion rate expressed as number of Base currency units for one Customer
   * currency unit. Available for POST/PUT Required.
   */
  CurrencyRate: z.number().nullable().optional(),
  /**
   * Date of creation payment record.
   */
  DateCreated: z.string().nullable().optional(),
  /**
   * Identifier of deposit. Available for POST. The payment is taken from deposit if it is
   * specified. Can be used only with Type=`PAYMENT`.
   */
  DepositID: z.string().nullable().optional()
});

export type PurchasePayments = z.infer<typeof PurchasePaymentsSchema>;

/**
 * Purchase Payment Line Model
 */
export const PurchasePaymentLineSchema = z.looseObject({
  /**
   * Identifier of Master Purchase Task
   */
  PurchaseID: z.string().nullable().optional(),
  /**
   * Identifier of Purchase Task
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Identifier of payment
   */
  ID: z.string().nullable().optional(),
  /**
   * Payment reference number
   */
  Reference: z.string().nullable().optional(),
  /**
   * Payment amount in customer currency
   */
  Amount: z.number().nullable().optional(),
  /**
   * Date when payment has been made
   */
  DatePaid: z.string().nullable().optional(),
  /**
   * Account Code of the bank/payment account from Chart of accounts
   */
  Account: z.string().nullable().optional(),
  /**
   * Currency Conversion rate expressed as number of Base currency units for one Customer
   * currency unit.
   */
  CurrencyRate: z.number().nullable().optional(),
  /**
   * Date of creation payment record.
   */
  DateCreated: z.string().nullable().optional()
});

export type PurchasePaymentLine = z.infer<typeof PurchasePaymentLineSchema>;

/**
 * Purchase Additional Charge Model
 */
export const PurchaseAdditionalChargeSchema = z.looseObject({
  /**
   * Name of Service Product referenced by this Line Max length: 256. Required.
   */
  Description: z.string().nullable().optional(),
  /**
   * Comment for this Line Max length: 256.
   */
  Reference: z.string().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Line Total. For validation Required.
   */
  Total: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional()
});

export type PurchaseAdditionalCharge = z.infer<typeof PurchaseAdditionalChargeSchema>;

/**
 * Purchase Manual Journal Line Model
 */
export const PurchaseManualJournalLineSchema = z.looseObject({
  /**
   * Reference Service Object
   */
  Reference: z.string().nullable().optional(),
  /**
   * Amount in base currency for manual journal Required.
   */
  Amount: z.number().nullable().optional(),
  /**
   * Effective date of manual journal Required.
   */
  Date: z.string().nullable().optional(),
  /**
   * Debit Account Required.
   */
  Debit: z.string().nullable().optional(),
  /**
   * Credit Account Required.
   */
  Credit: z.string().nullable().optional(),
  /**
   * Read only. rows with `true` value cannot be deleted or modified.
   */
  IsSystem: z.boolean().nullable().optional()
});

export type PurchaseManualJournalLine = z.infer<typeof PurchaseManualJournalLineSchema>;

/**
 * Purchase Shipping Address Model
 */
export const PurchaseShippingAddressSchema = z.looseObject({
  /**
   * Address Line 1 as displayed on Sale form. = Line1 + Line2 Max length: 256.
   */
  DisplayAddressLine1: z.string().nullable().optional(),
  /**
   * Address Line 2 as displayed on Sale form. = City + State/Region + Zip/Postcode + Country
   * Max length: 256.
   */
  DisplayAddressLine2: z.string().nullable().optional(),
  /**
   * Address Line 1 Max length: 256. Required.
   */
  Line1: z.string().nullable().optional(),
  /**
   * Address Line 2 Max length: 256.
   */
  Line2: z.string().nullable().optional(),
  /**
   * City Max length: 256.
   */
  City: z.string().nullable().optional(),
  /**
   * State Max length: 256.
   */
  State: z.string().nullable().optional(),
  /**
   * Post code Max length: 20.
   */
  Postcode: z.string().nullable().optional(),
  /**
   * Country Max length: 256. Required.
   */
  Country: z.string().nullable().optional(),
  /**
   * Ship to different company
   */
  ShipToOther: z.boolean().nullable().optional(),
  /**
   * Company name when ShipToOther is set to True Max length: 128.
   */
  Company: z.string().nullable().optional()
});

export type PurchaseShippingAddress = z.infer<typeof PurchaseShippingAddressSchema>;

/**
 * Purchase Order
 */
export const PurchaseOrderSchema = z.looseObject({
  /**
   * Unique Cin7 Core Purchase Task ID Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * if `true` then `additional charges` lines displayed in `Lines` array Required.
   */
  CombineAdditionalCharges: z.boolean().nullable().optional(),
  /**
   * Additional information for Order Max length: 1024. Required.
   */
  Memo: z.string().nullable().optional(),
  /**
   * Purchase Order Status. Possible Values are `NOT
   * AVAILABLE`,`DRAFT`,`AUTHORISED`,`VOIDED`. For POST only `DRAFT` and `AUTHORISED` values
   * accepted Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Required.
   */
  Lines: z.array(PurchaseOrderLineSchema).nullable().optional(),
  AdditionalCharges: z.array(PurchaseAdditionalChargeSchema).nullable().optional(),
  /**
   * Sum of order lines and additional charges without taxes. Not required for POST.
   * Required.
   */
  TotalBeforeTax: z.number().nullable().optional(),
  /**
   * Sum of order lines and additional charges taxes. Not required for POST. Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Sum of order lines and additional charges with taxes. Not required for POST. Required.
   */
  Total: z.number().nullable().optional()
});

export type PurchaseOrder = z.infer<typeof PurchaseOrderSchema>;

/**
 * Purchase Stock Model
 */
export const PurchaseStockSchema = z.looseObject({
  /**
   * Purchase Stock Received Status. Possible Values are `NOT
   * AVAILABLE`,`DRAFT`,`AUTHORISED`,`VOIDED`. For POST only `DRAFT` and `AUTHORISED` values
   * accepted Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Required.
   */
  Lines: z.array(PurchaseStockLineSchema).nullable().optional()
});

export type PurchaseStock = z.infer<typeof PurchaseStockSchema>;

/**
 * Purchase Invoice
 */
export const PurchaseInvoiceSchema = z.looseObject({
  /**
   * Unique Cin7 Core Purchase Task ID Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * if `true` then `additional charges` lines displayed in `Lines` array Required.
   */
  CombineAdditionalCharges: z.boolean().nullable().optional(),
  /**
   * Date when invoice created. Default value is current date, used if not specified.
   * Required.
   */
  InvoiceDate: z.string().nullable().optional(),
  /**
   * Date until invoice is valid. If not specified, used default value from Terms. Required.
   */
  InvoiceDueDate: z.string().nullable().optional(),
  /**
   * Invoice Number (auto-generated)
   */
  InvoiceNumber: z.string().nullable().optional(),
  /**
   * Purchase Invoice Status. Possible Values are `NOT
   * AVAILABLE`,`DRAFT`,`AUTHORISED`,`VOIDED`, `PAID`. For POST only `DRAFT` and `AUTHORISED`
   * values accepted Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Required.
   */
  Lines: z.array(PurchaseInvoiceLineSchema).nullable().optional(),
  AdditionalCharges: z.array(PurchaseInvoiceAdditionalChargeSchema).nullable().optional(),
  /**
   * Sum of order lines and additional charges without taxes. Not required for POST.
   */
  TotalBeforeTax: z.number().nullable().optional(),
  /**
   * Sum of order lines and additional charges taxes. Not required for POST.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Sum of order lines and additional charges with taxes. Not required for POST.
   */
  Total: z.number().nullable().optional(),
  /**
   * Not required for POST.
   */
  InvoiceTotalAmount: z.number().nullable().optional(),
  /**
   * Not required for POST.
   */
  InvoiceTotalTaxAmount: z.number().nullable().optional()
});

export type PurchaseInvoice = z.infer<typeof PurchaseInvoiceSchema>;

/**
 * Purchase Manual Journal Model
 */
export const PurchaseManualJournalSchema = z.looseObject({
  /**
   * Manual Journal Status. Available values are `NOT AVAILABLE`, `DRAFT`, `AUTHORISED`.
   * Available values for POST are `DRAFT`, `AUTHORISED` Required.
   */
  Status: z.string().nullable().optional(),
  Lines: z.array(PurchaseManualJournalLineSchema).nullable().optional()
});

export type PurchaseManualJournal = z.infer<typeof PurchaseManualJournalSchema>;

/**
 * Purchase
 */
export const PurchaseSchema = z.looseObject({
  /**
   * Unique Cin7 Core Purchase ID
   */
  ID: z.string().nullable().optional(),
  /**
   * Identifier of Supplier
   */
  SupplierID: z.string().nullable().optional(),
  /**
   * Supplier name Max length: 256.
   */
  Supplier: z.string().nullable().optional(),
  /**
   * Supplier Contact name Max length: 256.
   */
  Contact: z.string().nullable().optional(),
  /**
   * Supplier Contact phone Max length: 50.
   */
  Phone: z.string().nullable().optional(),
  /**
   * Account code used by default for invoice lines when no Inventory account is defined on
   * Product. By default Inventory Control Account is used from account mapping. Max length:
   * 50.
   */
  InventoryAccount: z.string().nullable().optional(),
  /**
   * `True` if there is no order in the purchase. `False` is default
   */
  BlindReceipt: z.boolean().nullable().optional(),
  /**
   * `INVOICE` for `Invoice First`, or `STOCK` for `Stock First` Max length: 10.
   */
  Approach: z.string().nullable().optional(),
  /**
   * Purchase Billing address
   */
  BillingAddress: z.unknown().nullable().optional(),
  /**
   * Purchase Shipping address
   */
  ShippingAddress: PurchaseShippingAddressSchema.nullable().optional(),
  /**
   * 3 character currency code of Base Currency defined in General Settings on the moment
   * when Purchase was created. Max length: 3.
   */
  BaseCurrency: z.string().nullable().optional(),
  /**
   * 3 character currency code of Supplier Currency defined in Supplier card at the moment
   * when Supplier is selected for the Purchase. Max length: 3.
   */
  SupplierCurrency: z.string().nullable().optional(),
  /**
   * Default Tax Rule name selected for Purchase Max length: 50.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * `Inclusive` or `Exclusive`
   */
  TaxCalculation: z.string().nullable().optional(),
  /**
   * Payment terms name Max length: 256.
   */
  Terms: z.string().nullable().optional(),
  /**
   * Date when shipment is due
   */
  RequiredBy: z.string().nullable().optional(),
  /**
   * Default location to store stock to Max length: 256.
   */
  Location: z.string().nullable().optional(),
  /**
   * Custom Purchase note Max length: 1024.
   */
  Note: z.string().nullable().optional(),
  /**
   * Represents Purchase Order Number Max length: 256.
   */
  OrderNumber: z.string().nullable().optional(),
  /**
   * Represents Purchase Order Date
   */
  OrderDate: z.string().nullable().optional(),
  /**
   * Combined Put Away status. Possible Values are `FULLY RECEIVED`, `PARTIALLY RECEIVED`,
   * `NOT AVAILABLE`, `NOT RECEIVED`, `VOIDED` Max length: 20.
   */
  CombinedReceivingStatus: z.string().nullable().optional(),
  /**
   * Combined Invoice status. Possible Values are `INVOICED`, `INVOICED / CREDITED`, `NOT
   * AVAILABLE`, `NOT INVOICED`, `PARTIALLY INVOICED`, `PARTIALLY INVOICED / CREDITED` Max
   * length: 20.
   */
  CombinedInvoiceStatus: z.string().nullable().optional(),
  /**
   * Payment status. Possible Values are `PREPAID`, `PARTIALLY PAID`, `UNPAID`, `PAID`,
   * `OVERPAID / CREDITED`, `VOIDED` Max length: 20.
   */
  CombinedPaymentStatus: z.string().nullable().optional(),
  /**
   * Type of Purchase. Possible Values are `Simple Purchase`, `Advanced Purchase` , `Service
   * Purchase` Max length: 20.
   */
  Type: z.string().nullable().optional(),
  /**
   * Specifies, if Purchase is a `Service Purchase`
   */
  IsServiceOnly: z.boolean().nullable().optional(),
  /**
   * Current Purchase status. Current sale status. Possible values are values Max length: 20.
   */
  Status: z.string().nullable().optional(),
  /**
   * ID of SaleTask this drop-ship purchase is related to.
   */
  RelatedDropShipSaleTask: z.string().nullable().optional(),
  /**
   * Conversion Rate expressed as number of Base currency units for one Supplier currency
   * unit
   */
  CurrencyRate: z.number().nullable().optional(),
  /**
   * Date and time when purchase task was created of last time modified
   */
  LastUpdatedDate: z.string().nullable().optional(),
  /**
   * Purchase Order
   */
  Order: PurchaseOrderSchema.nullable().optional(),
  /**
   * Purchased and received items. The field is filled only for Advanced Purchases.
   */
  StockReceived: z.array(z.unknown()).nullable().optional(),
  /**
   * Purchased and put away items
   */
  PutAway: z.array(z.unknown()).nullable().optional(),
  /**
   * Purchase Invoice
   */
  Invoice: z.array(z.unknown()).nullable().optional(),
  /**
   * Purchase Credit Note
   */
  CreditNote: z.array(z.unknown()).nullable().optional(),
  /**
   * Purchase Manual Journals
   */
  ManualJournals: z.array(z.unknown()).nullable().optional(),
  /**
   * Purchase Additional Attributes
   */
  AdditionalAttributes: z.unknown().nullable().optional(),
  /**
   * Purchase Attachments
   */
  Attachments: z.array(z.unknown()).nullable().optional(),
  /**
   * Purchase Inventory Movements
   */
  InventoryMovements: z.unknown().nullable().optional()
});

export type Purchase = z.infer<typeof PurchaseSchema>;
