// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Reference books (locations, brands, tax, etc.).
 */

/**
 * Attribute Set
 */
export const AttributeSetSchema = z.looseObject({
  /**
   * Required for PUT and DELETE, Ignored for POST operations Required (conditional).
   */
  ID: z.string().nullable().optional(),
  /**
   * Max length: 50. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Attribute Set attribute name. # - int(1-10). Attribute1Name is required for POST, PUT.
   * Max length: 50. Required (conditional).
   */
  'Attribute#Name': z.string().nullable().optional(),
  /**
   * Attribute Set attribute type. # - int(1-10). Attribute1Type is required for POST, PUT.
   * Available values are `Not used`, `Text`, `Checkbox`, `List`, `Date`, `Numeric`. Max
   * length: 50. Required (conditional).
   */
  'Attribute#Type': z.string().nullable().optional(),
  /**
   * Attribute Set attribute values. Delimiter ",". # - int(1-10). Attribute1Values is
   * required for POST, PUT. Required (conditional).
   */
  'Attribute#Values': z.string().nullable().optional(),
  /**
   * Array with attributes. Read-only.
   */
  Attributes: z.array(z.unknown()).nullable().optional()
});

export type AttributeSet = z.infer<typeof AttributeSetSchema>;

/**
 * Bank Accounts
 */
export const BankAccountsSchema = z.looseObject({
  /**
   * Unique ID
   */
  AccountID: z.string().nullable().optional(),
  /**
   * Bank name Max length: 512.
   */
  Bank: z.string().nullable().optional(),
  /**
   * Account name to which the Bank Account is linked Max length: 256.
   */
  AccountName: z.string().nullable().optional(),
  /**
   * Account number Max length: 256.
   */
  AccountNumber: z.string().nullable().optional(),
  /**
   * Account code to which the Bank Account is linked Max length: 50.
   */
  AccountCode: z.string().nullable().optional(),
  /**
   * Currency Max length: 3.
   */
  Currency: z.string().nullable().optional(),
  /**
   * Statement balance
   */
  StatementBalance: z.number().nullable().optional(),
  /**
   * Cin7 Core balance
   */
  BalanceInDear: z.number().nullable().optional(),
  /**
   * Initial balance
   */
  InitialBalance: z.string().nullable().optional()
});

export type BankAccounts = z.infer<typeof BankAccountsSchema>;

/**
 * Brand
 */
export const BrandSchema = z.looseObject({
  /**
   * Required for PUT, Ignored for POST operations
   */
  ID: z.string().nullable().optional(),
  /**
   * Brand name Max length: 50. Required.
   */
  Name: z.string().nullable().optional()
});

export type Brand = z.infer<typeof BrandSchema>;

/**
 * Carrier
 */
export const CarrierSchema = z.looseObject({
  /**
   * Unique Carrier ID.
   */
  CarrierID: z.string().nullable().optional(),
  /**
   * Name of Carrier. Max length: 256. Required.
   */
  Description: z.string().nullable().optional()
});

export type Carrier = z.infer<typeof CarrierSchema>;

/**
 * Chart of Accounts
 */
export const ChartOfAccountsSchema = z.looseObject({
  /**
   * Unique code of Account Max length: 50. Required.
   */
  Code: z.string().nullable().optional(),
  /**
   * Account name Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Should be one of the following values: `BANK`, `CURRLIAB`, `LIABILITY`, `TERMLIA`,
   * `PAYGLIABILITY`, `SUPERANNUATIONLIABILITY`, `WAGESPAYABLELIABILITY` Max length: 50.
   * Required.
   */
  Type: z.string().nullable().optional(),
  /**
   * Account status Max length: 50. Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Account description
   */
  Description: z.string().nullable().optional(),
  /**
   * Should be one of the following values: `ASSET`, `LIABILITY`, `EXPENSE`, `EQUITY`,
   * `REVENUE`
   */
  Class: z.string().nullable().optional(),
  /**
   * Read-only for PUT. Should be one of the following values: `Accounts receivable`,
   * `Accounts payable`, `Bank revaluations`, `GST / VAT`, `GST on imports`, `Historical
   * adjustment`, `Realized currency gains`, `Retained earnings`, `Rounding`, `Tracking
   * transfers`, `Unpaid expense claims`, `Unrealized currency gains`, `Wages payable`". For
   * POST requests, the user may optionally provide a value for either SystemAccount or
   * SystemAccountCode. If both fields are provided, the account code and name must
   * correspond to the same account.
   */
  SystemAccount: z.string().nullable().optional(),
  /**
   * Read-only for PUT. Should be one of the following values: `BANKCURRENCYGAIN`,
   * `CREDITORS`, `DEBTORS`, `GST`, `GSTONIMPORTS`, `HISTORICAL`, `REALISEDCURRENCYGAIN`,
   * `RETAINEDEARNINGS`, `ROUNDING`, `TRACKINGTRANSFERS`, `UNPAIDEXPCLM`,
   * `UNREALISEDCURRENCYGAIN`, `WAGEPAYABLES`". For POST requests, the user may optionally
   * provide a value for either SystemAccount or SystemAccountCode. If both fields are
   * provided, the account code and name must correspond to the same account.
   */
  SystemAccountCode: z.string().nullable().optional(),
  /**
   * Account status
   */
  ForPayments: z.string().nullable().optional(),
  /**
   * Account display name. Read-only.
   */
  DisplayName: z.string().nullable().optional(),
  /**
   * Read-only.
   */
  OldCode: z.string().nullable().optional(),
  /**
   * Name of the Bank. Only for PUT and POST. Required if Account `Type` is `BANK`.
   */
  Bank: z.string().nullable().optional(),
  /**
   * Bank Account Number. Only for PUT and POST. Required if Account `Type` is `BANK`.
   */
  BankAccountNumber: z.string().nullable().optional(),
  /**
   * Bank Account ID to which the Account is linked. Read-only
   */
  BankAccountId: z.string().nullable().optional(),
  /**
   * Currency. Read-only.
   */
  Currency: z.string().nullable().optional()
});

export type ChartOfAccounts = z.infer<typeof ChartOfAccountsSchema>;

/**
 * Fixed Asset Types
 */
export const FixedAssetTypesSchema = z.looseObject({
  /**
   * Unique ID
   */
  FixedAssetTypeID: z.string().nullable().optional(),
  /**
   * Fixed Asset Type name Max length: 50. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Should be one of the following values: `No Depreciation`, `Straight Line`, `Declining
   * Balance`, `Declining Balance (150%)`, `Declining Balance (200%)`, `Sum of the Years'
   * Digits`, `Full Depreciation at Purchase` Max length: 255. Required.
   */
  DepreciationMethod: z.string().nullable().optional(),
  /**
   * Should be one of the following values: `Full Month`, `Actual Days` Max length: 255.
   * Required.
   */
  AveragingMethod: z.string().nullable().optional(),
  /**
   * Rate (%). Unable to set if Effective Life attribute is set Required.
   */
  Rate: z.number().nullable().optional(),
  /**
   * Effective Life (Yrs). Unable to set if Rate attribute is set Required.
   */
  EffectiveLife: z.number().nullable().optional(),
  /**
   * ChartOfAccount Code with Type == `FIXED` && Class == `ASSET` && Status == `ACTIVE`
   * Required.
   */
  AssetAccountCode: z.number().nullable().optional(),
  /**
   * ChartOfAccount Code with Type == `FIXED` && Class == `ASSET` && Status == `ACTIVE`
   * Required.
   */
  AccumulatedDepreciationAccountCode: z.string().nullable().optional(),
  /**
   * `DisplayName` of the linked ChartOfAccount. Read-only.
   */
  AssetAccountName: z.string().nullable().optional(),
  /**
   * `DisplayName` of the linked ChartOfAccount. Read-only.
   */
  AccumulatedDepreciationAccountName: z.string().nullable().optional(),
  /**
   * `DisplayName` of the linked ChartOfAccount. Read-only.
   */
  DepreciationExpenseAccountName: z.string().nullable().optional()
});

export type FixedAssetTypes = z.infer<typeof FixedAssetTypesSchema>;

/**
 * Location
 */
export const LocationSchema = z.looseObject({
  /**
   * Required for PUT and DELETE, Ignored for POST operations Required (conditional).
   */
  ID: z.string().nullable().optional(),
  /**
   * Location name Max length: 50. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Points that location is used as default
   */
  IsDefault: z.boolean().nullable().optional(),
  /**
   * Points that location is deprecated
   */
  Deprecated: z.boolean().nullable().optional(),
  /**
   * Array (ID, Name) with related Bins
   */
  Bins: z.array(z.unknown()).nullable().optional(),
  /**
   * Points that location is used as Fixed Asset
   */
  FixedAssetsLocation: z.boolean().nullable().optional(),
  /**
   * Parent ID (used for Bins)
   */
  ParentID: z.string().nullable().optional(),
  /**
   * Reference linked to current location
   */
  ReferenceCount: z.number().nullable().optional(),
  /**
   * Address line Max length: 50.
   */
  AddressLine1: z.string().nullable().optional(),
  /**
   * Address line second Max length: 50.
   */
  AddressLine2: z.string().nullable().optional(),
  /**
   * City suburb Max length: 50.
   */
  AddressCitySuburb: z.string().nullable().optional(),
  /**
   * State province Max length: 50.
   */
  AddressStateProvince: z.string().nullable().optional(),
  /**
   * Zip post code Max length: 50.
   */
  AddressZipPostCode: z.string().nullable().optional(),
  /**
   * Country Max length: 50.
   */
  AddressCountry: z.string().nullable().optional(),
  /**
   * Pick zones Max length: 50.
   */
  PickZones: z.string().nullable().optional(),
  /**
   * Points that location is shopfloor
   */
  IsShopfloor: z.boolean().nullable().optional(),
  /**
   * Points that location is location of co-manufacturer
   */
  IsCoMan: z.boolean().nullable().optional(),
  /**
   * Points that location is staging. It is used only for Bins.
   */
  IsStaging: z.boolean().nullable().optional()
});

export type Location = z.infer<typeof LocationSchema>;

/**
 * Payment Term
 */
export const PaymentTermSchema = z.looseObject({
  /**
   * Unique Payment Term ID.
   */
  ID: z.string().nullable().optional(),
  /**
   * Name of Payment Term. Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Minimum Payment Term duration in days
   */
  Duration: z.number().nullable().optional(),
  /**
   * Method of Payment Term. Should be one of the following values: `number of days`, `day of
   * next month`, `last day of next month`, `days since the end of the month`
   */
  Method: z.string().nullable().optional(),
  /**
   * Points that Payment Term is Active. `True` as default for POST.
   */
  IsActive: z.boolean().nullable().optional(),
  /**
   * Points that Payment Term is Default. `False` as default for POST.
   */
  IsDefault: z.boolean().nullable().optional()
});

export type PaymentTerm = z.infer<typeof PaymentTermSchema>;

/**
 * Available Fields for PriceTier
 */
export const PriceTierSchema = z.looseObject({
  /**
   * Code number of Price Tier
   */
  Code: z.number().nullable().optional(),
  /**
   * Price Tier name
   */
  Name: z.string().nullable().optional()
});

export type PriceTier = z.infer<typeof PriceTierSchema>;

/**
 * Tax
 */
export const TaxSchema = z.looseObject({
  /**
   * Unique ID Max length: 50.
   */
  ID: z.string().nullable().optional(),
  /**
   * Tax name Max length: 50. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * ChartOfAccount Code with Class == `LIABILITY` && Status == `ACTIVE` Required.
   */
  Account: z.string().nullable().optional(),
  /**
   * Points that tax is Active Required.
   */
  IsActive: z.boolean().nullable().optional(),
  /**
   * Points that tax is Inclusive Required.
   */
  TaxInclusive: z.boolean().nullable().optional(),
  /**
   * Tax percentage, should be between 0 and 100. Read-only
   */
  TaxPercent: z.number().nullable().optional(),
  /**
   * Points that tax is used for Sale
   */
  IsTaxForSale: z.boolean().nullable().optional(),
  /**
   * Points that tax is used for Purchase
   */
  IsTaxForPurchase: z.boolean().nullable().optional(),
  Components: z.array(z.unknown()).nullable().optional()
});

export type Tax = z.infer<typeof TaxSchema>;

/**
 * Available Fields for UnitOfMeasure
 */
export const UnitOfMeasureSchema = z.looseObject({
  /**
   * Required for PUT, Ignored for POST operations
   */
  ID: z.string().nullable().optional(),
  /**
   * Unit of Measure name Max length: 50. Required.
   */
  Name: z.string().nullable().optional()
});

export type UnitOfMeasure = z.infer<typeof UnitOfMeasureSchema>;

/**
 * Shipping Zone
 */
export const ShippingZoneSchema = z.looseObject({
  /**
   * Required.
   */
  ZoneID: z.string().nullable().optional(),
  /**
   * Max length: 128. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Required.
   */
  IsRestZone: z.boolean().nullable().optional(),
  /**
   * Required.
   */
  PricesInclTax: z.boolean().nullable().optional(),
  /**
   * Required.
   */
  Negative: z.boolean().nullable().optional(),
  /**
   * Required.
   */
  DefaultShippingCost: z.number().nullable().optional(),
  /**
   * Readonly
   */
  ShortDesc: z.boolean().nullable().optional(),
  /**
   * Required (conditional).
   */
  TaxRuleID: z.string().nullable().optional(),
  /**
   * Max length: 255. Required (conditional).
   */
  TaxRuleName: z.string().nullable().optional(),
  AppliesTo: z.array(z.unknown()).nullable().optional(),
  Conditions: z.array(z.unknown()).nullable().optional()
});

export type ShippingZone = z.infer<typeof ShippingZoneSchema>;

/**
 * Discount Line Model
 */
export const DiscountLineSchema = z.looseObject({
  /**
   * Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Applicable only when Product Discount Rule Type = QuantityBase and only for the first
   * item in the list. Subsequent items MinValue is being calculated as previous item
   * MaxValue + 0.0001.
   */
  MinValue: z.number().nullable().optional(),
  /**
   * Applicable only when Product Discount Rule Type = QuantityBase
   */
  MaxValue: z.number().nullable().optional(),
  /**
   * DiscountAmount, DiscountPercent, MarkupAmount, MarkupPercent, PriceOverride, FlatAmount,
   * FreeShipping
   */
  DiscountType: z.string().nullable().optional(),
  /**
   * Required (conditional).
   */
  Amount: z.number().nullable().optional(),
  /**
   * Required when DiscountType = FreeShipping Required (conditional).
   */
  OrderExceeds: z.number().nullable().optional()
});

export type DiscountLine = z.infer<typeof DiscountLineSchema>;

/**
 * Product Discount Rule
 */
export const ProductDiscountRuleSchema = z.looseObject({
  /**
   * Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Deal Name Max length: 128. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Required.
   */
  IsActive: z.boolean().nullable().optional(),
  /**
   * Simple, QuantityBased, FreeShipping Required.
   */
  Type: z.string().nullable().optional(),
  DiscountLines: z.array(DiscountLineSchema).nullable().optional()
});

export type ProductDiscountRule = z.infer<typeof ProductDiscountRuleSchema>;

/**
 * Product Deal Customer
 */
export const ProductDealCustomerSchema = z.looseObject({
  /**
   * Required (conditional).
   */
  ID: z.string().nullable().optional(),
  /**
   * Required (conditional).
   */
  CustomerName: z.string().nullable().optional(),
  /**
   * Required (conditional).
   */
  CustomerID: z.string().nullable().optional()
});

export type ProductDealCustomer = z.infer<typeof ProductDealCustomerSchema>;

/**
 * Product Deal
 */
export const ProductDealSchema = z.looseObject({
  /**
   * Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Deal Name Required.
   */
  Name: z.string().nullable().optional(),
  DateFrom: z.string().nullable().optional(),
  DateTo: z.string().nullable().optional(),
  /**
   * Required.
   */
  IsActive: z.boolean().nullable().optional(),
  /**
   * Required.
   */
  AllowCoupons: z.boolean().nullable().optional(),
  /**
   * Required.
   */
  SingleCouponCodeUsage: z.boolean().nullable().optional(),
  /**
   * All, B2B, POS, Specified, CustomerTags
   */
  CustomersGroup: z.string().nullable().optional(),
  CouponCodes: z.string().nullable().optional(),
  DealCustomers: z.array(ProductDealCustomerSchema).nullable().optional(),
  DealCustomerTags: z.array(z.unknown()).nullable().optional(),
  DealDiscounts: z.array(z.unknown()).nullable().optional()
});

export type ProductDeal = z.infer<typeof ProductDealSchema>;
