// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Sales and nested sale documents. https://dearinventory.docs.apiary.io/#reference/sale
 */

/**
 * Sale List
 */
export const SaleListSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale identifier Required.
   */
  SaleID: z.string().nullable().optional(),
  /**
   * Sale Order number generated by Cin7 Core Max length: 256. Required.
   */
  OrderNumber: z.string().nullable().optional(),
  /**
   * Current sale status. Possible values are values Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Date when Sale Order was created Required.
   */
  OrderDate: z.string().nullable().optional(),
  /**
   * Date when Invoice was issued
   */
  InvoiceDate: z.string().nullable().optional(),
  /**
   * Name of the customer Max length: 256. Required.
   */
  Customer: z.string().nullable().optional(),
  /**
   * Customer Identifier
   */
  CustomerID: z.string().nullable().optional(),
  /**
   * Invoice number generated by Cin7 Core Max length: 256.
   */
  InvoiceNumber: z.string().nullable().optional(),
  /**
   * Optional Customer Reference (typically customer Purchase order number) supplied by the
   * customer for the sale Max length: 256.
   */
  CustomerReference: z.string().nullable().optional(),
  /**
   * Total Invoice amount minus total Credit note amount in customer currency Required.
   */
  InvoiceAmount: z.number().nullable().optional(),
  /**
   * Total Paid amount minus Refunded amount in customer currency Required.
   */
  PaidAmount: z.number().nullable().optional(),
  /**
   * Total invoice amount
   */
  SaleInvoicesTotalAmount: z.number().nullable().optional(),
  /**
   * Date when invoice is due according to selected payment terms
   */
  InvoiceDueDate: z.string().nullable().optional(),
  /**
   * Date when shipment is due
   */
  ShipBy: z.string().nullable().optional(),
  /**
   * 3 digit Base currency code (as configured in General Settings) Max length: 3. Required.
   */
  BaseCurrency: z.string().nullable().optional(),
  /**
   * 3 digit Customer currency code Max length: 3. Required.
   */
  CustomerCurrency: z.string().nullable().optional(),
  /**
   * Credit note number generated by Cin7 Core. Is empty unless credit note is created Max
   * length: 256.
   */
  CreditNoteNumber: z.string().nullable().optional(),
  /**
   * Date when the sale was last created/updated last time Required.
   */
  Updated: z.string().nullable().optional(),
  /**
   * Sale Quote status. Possible Values are values Max length: 20. Required.
   */
  QuoteStatus: z.string().nullable().optional(),
  /**
   * Sale Order status. Possible Values are values Max length: 20. Required.
   */
  OrderStatus: z.string().nullable().optional(),
  /**
   * Pick status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `PICKED`, `PICKING` , `NOT
   * PICKED` , `PARTIALLY PICKED` Max length: 20. Required.
   */
  CombinedPickingStatus: z.string().nullable().optional(),
  /**
   * Pack status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `PACKED`, `PACKING`, `NOT
   * PACKED`, `PARTIALLY PACKED` Max length: 20. Required.
   */
  CombinedPackingStatus: z.string().nullable().optional(),
  /**
   * Ship status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `SHIPPED`, `SHIPPING` , `NOT
   * SHIPPED` , `PARTIALLY SHIPPED` Max length: 20. Required.
   */
  CombinedShippingStatus: z.string().nullable().optional(),
  /**
   * Fulfilment status. Possible Values are `FULFILLED`, `PARTIALLY FULFILLED`, `NOT
   * AVAILABLE`, `NOT FULFILLED`, `VOIDED` Max length: 20. Required.
   */
  FulFilmentStatus: z.string().nullable().optional(),
  /**
   * Invoice status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE`,
   * `PAID` Max length: 20. Required.
   */
  CombinedInvoiceStatus: z.string().nullable().optional(),
  /**
   * Combined total invoice paid amount
   */
  CombinedPaymentTotal: z.number().nullable().optional(),
  /**
   * Credit Note status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE`
   * Max length: 20. Required.
   */
  CreditNoteStatus: z.string().nullable().optional(),
  /**
   * Payment status. Possible Values are `NOT REFUNDED`, `PREPAID`, `PARTIALLY PAID`,
   * `UNPAID`, `PAID`, `VOIDED` Max length: 20. Required.
   */
  CombinedPaymentStatus: z.string().nullable().optional(),
  /**
   * Type of Sale. Possible Values are `Simple Sale`, `Advanced Sale` , `Service Sale` Max
   * length: 50. Required.
   */
  Type: z.string().nullable().optional(),
  /**
   * Tracking Numbers Max length: 256. Required.
   */
  CombinedTrackingNumbers: z.string().nullable().optional(),
  /**
   * Source of the sale. read-only field Max length: 32.
   */
  SourceChannel: z.string().nullable().optional(),
  /**
   * Custom field that is only available in API and allows to set arbitrary value for the
   * sale for later search and any custom logic Max length: 256.
   */
  ExternalID: z.string().nullable().optional(),
  /**
   * Sale Order Location ID
   */
  OrderLocationID: z.string().nullable().optional()
});

export type SaleList = z.infer<typeof SaleListSchema>;

/**
 * Sale Quote Line Model
 */
export const SaleQuoteLineSchema = z.looseObject({
  /**
   * Product identifier referenced by this Line. Required If CombineAdditionalCharges param
   * exist for this endpoint and it have values = `false` Required (conditional).
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU referenced by this Line. Required If CombineAdditionalCharges param exist
   * for this endpoint and it have values = `false` Max length: 50. Required (conditional).
   */
  SKU: z.string().nullable().optional(),
  /**
   * Product Name referenced by this Line Max length: 1024. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Average product cost Required.
   */
  AverageCost: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Comment for this line Max length: 256. Required.
   */
  Comment: z.string().nullable().optional(),
  /**
   * Line Total.For validation
   */
  Total: z.number().nullable().optional()
});

export type SaleQuoteLine = z.infer<typeof SaleQuoteLineSchema>;

/**
 * Sale Order Line Model
 */
export const SaleOrderLineSchema = z.looseObject({
  /**
   * Product identifier referenced by this Line. Required If CombineAdditionalCharges param
   * exist for this endpoint and it have values = `false` Required (conditional).
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU referenced by this Line. Required If CombineAdditionalCharges param exist
   * for this endpoint and it have values = `false` Max length: 50. Required (conditional).
   */
  SKU: z.string().nullable().optional(),
  /**
   * Product Name referenced by this Line Max length: 1024. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Average product cost
   */
  AverageCost: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Comment for this line Max length: 256.
   */
  Comment: z.string().nullable().optional(),
  /**
   * Required if product is not a service with “Optional Drop Ship” mode. Otherwise it
   * ignored.
   */
  DropShip: z.boolean().nullable().optional(),
  /**
   * Quantity of the ordered product on backorder. Read Only for POST
   */
  BackorderQuantity: z.number().nullable().optional(),
  /**
   * Line Total.For validation
   */
  Total: z.number().nullable().optional()
});

export type SaleOrderLine = z.infer<typeof SaleOrderLineSchema>;

/**
 * Sale Fulfilment Pick Pack Line Model
 */
export const SaleFulfilmentPickPackLineSchema = z.looseObject({
  /**
   * Product identifier referenced by this Line.
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU referenced by this Line. Max length: 50. Required.
   */
  SKU: z.string().nullable().optional(),
  /**
   * Product Name referenced by this Line Max length: 1024.
   */
  Name: z.string().nullable().optional(),
  /**
   * Location from which pick product. Required if `LocationID` is empty Max length: 256.
   * Required (conditional).
   */
  Location: z.string().nullable().optional(),
  /**
   * LocationID from which pick product. Required if `Location` is empty Required
   * (conditional).
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Product quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Batch Serial Number Max length: 50.
   */
  BatchSN: z.string().nullable().optional(),
  /**
   * Expiry Date
   */
  ExpiryDate: z.string().nullable().optional(),
  /**
   * Pack box name. This field available only for packing. Max length: 256.
   */
  Box: z.string().nullable().optional(),
  /**
   * Indication that this line relates to non-inventory product and won't involve any stock
   * movement.
   */
  NonInventory: z.boolean().nullable().optional(),
  /**
   * Warranty registration number. This field available only for packing. Max length: 256.
   */
  WarrantyRegistrationNumber: z.string().nullable().optional(),
  /**
   * Used only for CreditNote. Location name of return of the product. Max length: 256.
   */
  RestockLocation: z.string().nullable().optional(),
  /**
   * Used only for CreditNote. Location ID of return of the product.
   */
  RestockLocationID: z.string().nullable().optional(),
  /**
   * Used only for CreditNote. Date of return of the product.
   */
  RestockDate: z.string().nullable().optional()
});

export type SaleFulfilmentPickPackLine = z.infer<typeof SaleFulfilmentPickPackLineSchema>;

/**
 * Sale Fulfilment Ship Line Model
 */
export const SaleFulfilmentShipLineSchema = z.looseObject({
  /**
   * Shipment identifier. Not Required for POST/PUT
   */
  ID: z.string().nullable().optional(),
  /**
   * Shipment Date Required.
   */
  ShipmentDate: z.string().nullable().optional(),
  /**
   * Carrier referenced by this Line. Max length: 256.
   */
  Carrier: z.string().nullable().optional(),
  /**
   * Box number. Use commas to separate multiple boxes. For POST/PUT methods use `Box` as the
   * field name. Max length: 256. Required.
   */
  Boxes: z.string().nullable().optional(),
  /**
   * Shipment tracking number. Max length: 256.
   */
  TrackingNumber: z.string().nullable().optional(),
  /**
   * Shipment tracking URL. Read-only. Max length: 512.
   */
  TrackingURL: z.string().nullable().optional(),
  /**
   * Is package shipped.
   */
  IsShipped: z.boolean().nullable().optional()
});

export type SaleFulfilmentShipLine = z.infer<typeof SaleFulfilmentShipLineSchema>;

/**
 * Sale Invoice Line Model
 */
export const SaleInvoiceLineSchema = z.looseObject({
  /**
   * Product identifier referenced by this Line. Required If CombineAdditionalCharges param
   * exist for this endpoint and it have values = `false` Required (conditional).
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Product SKU referenced by this Line. Required If CombineAdditionalCharges param exist
   * for this endpoint and it have values = `false` Max length: 50. Required (conditional).
   */
  SKU: z.string().nullable().optional(),
  /**
   * Product Name referenced by this Line Max length: 1024. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Line Total. For validation Required.
   */
  Total: z.number().nullable().optional(),
  /**
   * Average product cost
   */
  AverageCost: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Revenue account Max length: 50.
   */
  Account: z.string().nullable().optional(),
  /**
   * Comment for this line Max length: 256.
   */
  Comment: z.string().nullable().optional()
});

export type SaleInvoiceLine = z.infer<typeof SaleInvoiceLineSchema>;

/**
 * Sale Invoice Additional Charge Model
 */
export const SaleInvoiceAdditionalChargeSchema = z.looseObject({
  /**
   * Name of Service Product referenced by this Line Max length: 256. Required.
   */
  Description: z.string().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Line Total.For validation
   */
  Total: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Revenue account Max length: 50.
   */
  Account: z.string().nullable().optional(),
  /**
   * Comment Max length: 1024.
   */
  Comment: z.string().nullable().optional()
});

export type SaleInvoiceAdditionalCharge = z.infer<typeof SaleInvoiceAdditionalChargeSchema>;

/**
 * Sale Credit Note List
 */
export const SaleCreditNoteListSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale identifier Required.
   */
  SaleID: z.string().nullable().optional(),
  /**
   * Sale Order number generated by Cin7 Core Max length: 256. Required.
   */
  OrderNumber: z.string().nullable().optional(),
  /**
   * Current sale status. Possible values are values Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Date when Sale Order was created Required.
   */
  OrderDate: z.string().nullable().optional(),
  /**
   * Date when Invoice was issued
   */
  InvoiceDate: z.string().nullable().optional(),
  /**
   * Name of the customer Max length: 256. Required.
   */
  Customer: z.string().nullable().optional(),
  /**
   * Customer Identifier
   */
  CustomerID: z.string().nullable().optional(),
  /**
   * Invoice number generated by Cin7 Core Max length: 256.
   */
  InvoiceNumber: z.string().nullable().optional(),
  /**
   * Optional Customer Reference (typically customer Purchase order number) supplied by the
   * customer for the sale Max length: 256.
   */
  CustomerReference: z.string().nullable().optional(),
  /**
   * Total Invoice amount minus total Credit note amount in customer currency Required.
   */
  InvoiceAmount: z.number().nullable().optional(),
  /**
   * Total Paid amount minus Refunded amount in customer currency Required.
   */
  PaidAmount: z.number().nullable().optional(),
  /**
   * Date when invoice is due according to selected payment terms
   */
  InvoiceDueDate: z.string().nullable().optional(),
  /**
   * Date when shipment is due
   */
  ShipBy: z.string().nullable().optional(),
  /**
   * 3 digit Base currency code (as configured in General Settings) Max length: 3. Required.
   */
  BaseCurrency: z.string().nullable().optional(),
  /**
   * 3 digit Customer currency code Max length: 3. Required.
   */
  CustomerCurrency: z.string().nullable().optional(),
  /**
   * Credit note number generated by Cin7 Core. Is empty unless credit note is created Max
   * length: 256.
   */
  CreditNoteNumber: z.string().nullable().optional(),
  /**
   * Date when the sale was last created/updated last time Required.
   */
  Updated: z.string().nullable().optional(),
  /**
   * Sale Quote status. Possible Values are values Max length: 20. Required.
   */
  QuoteStatus: z.string().nullable().optional(),
  /**
   * Sale Order status. Possible Values are values Max length: 20. Required.
   */
  OrderStatus: z.string().nullable().optional(),
  /**
   * Pick status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `PICKED`, `PICKING` , `NOT
   * PICKED` , `PARTIALLY PICKED` Max length: 20. Required.
   */
  CombinedPickingStatus: z.string().nullable().optional(),
  /**
   * Pack status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `PACKED`, `PACKING`, `NOT
   * PACKED`, `PARTIALLY PACKED` Max length: 20. Required.
   */
  CombinedPackingStatus: z.string().nullable().optional(),
  /**
   * Ship status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `SHIPPED`, `SHIPPING` , `NOT
   * SHIPPED` , `PARTIALLY SHIPPED` Max length: 20. Required.
   */
  CombinedShippingStatus: z.string().nullable().optional(),
  /**
   * Fulfilment status. Possible Values are `FULFILLED`, `PARTIALLY FULFILLED`, `NOT
   * AVAILABLE`, `NOT FULFILLED`, `VOIDED` Max length: 20. Required.
   */
  FulFilmentStatus: z.string().nullable().optional(),
  /**
   * Invoice status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE`,
   * `PAID` Max length: 20. Required.
   */
  CombinedInvoiceStatus: z.string().nullable().optional(),
  /**
   * Credit Note status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE`
   * Max length: 20. Required.
   */
  CreditNoteStatus: z.string().nullable().optional(),
  /**
   * Payment status. Possible Values are `NOT REFUNDED`, `PREPAID`, `PARTIALLY PAID`,
   * `UNPAID`, `PAID`, `VOIDED` Max length: 20. Required.
   */
  CombinedPaymentStatus: z.string().nullable().optional(),
  /**
   * Type of Sale. Possible Values are `Simple Sale`, `Advanced Sale` , `Service Sale`, `Sale
   * Credit Note`, `Credit Note` Max length: 50. Required.
   */
  Type: z.string().nullable().optional(),
  /**
   * Tracking Numbers Max length: 256. Required.
   */
  CombinedTrackingNumbers: z.string().nullable().optional(),
  /**
   * Source of the sale. read-only field Max length: 32.
   */
  SourceChannel: z.string().nullable().optional(),
  /**
   * Custom field that is only available in API and allows to set arbitrary value for the
   * sale for later search and any custom logic Max length: 256.
   */
  ExternalID: z.string().nullable().optional(),
  /**
   * Sale Order Location ID
   */
  OrderLocationID: z.string().nullable().optional()
});

export type SaleCreditNoteList = z.infer<typeof SaleCreditNoteListSchema>;

/**
 * Sale Payment Line Partial Model
 */
export const SalePaymentLinePartialSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale ID.
   */
  SaleID: z.string().nullable().optional(),
  /**
   * Unique Cin7 Core Sale Task ID. Available for POST Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Identifier of payment. Available for PUT Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Sale Order Number
   */
  SaleOrderNumber: z.string().nullable().optional(),
  /**
   * Sale Task Invoice Number
   */
  InvoiceNumber: z.string().nullable().optional(),
  /**
   * Sale Task Credit Note Number
   */
  CreditNoteNumber: z.string().nullable().optional(),
  /**
   * Available values are `PREPAYMENT`,`PAYMENT`,`REFUND`. Available for POST Required.
   */
  Type: z.string().nullable().optional(),
  /**
   * Payment reference number. Available for POST/PUT
   */
  Reference: z.string().nullable().optional(),
  /**
   * Payment amount in customer currency. Available for POST/PUT. For PUT is not available
   * when payment is a credit. Required.
   */
  Amount: z.number().nullable().optional(),
  /**
   * Date when payment has been made. Available for POST/PUT Required.
   */
  DatePaid: z.string().nullable().optional(),
  /**
   * Account Code of the bank/payment account from Chart of accounts. Available for POST/PUT,
   * ignored if CreditID is specified. For PUT is not available when payment is a credit.
   * Required.
   */
  Account: z.string().nullable().optional(),
  /**
   * Currency Conversion rate expressed as number of Base currency units for one Customer
   * currency unit. Available for POST/PUT, ignored if CreditID is specified. Required.
   */
  CurrencyRate: z.number().nullable().optional(),
  /**
   * Date of creation payment record.
   */
  DateCreated: z.string().nullable().optional(),
  /**
   * Id for Sale Credit entry. Available for PUT. The payment is taken from a credit, if it
   * is specified. Can be used only with Type=`PAYMENT`.
   */
  CreditID: z.string().nullable().optional()
});

export type SalePaymentLinePartial = z.infer<typeof SalePaymentLinePartialSchema>;

/**
 * Sale Payment Line Model
 */
export const SalePaymentLineSchema = z.looseObject({
  /**
   * Identifier of payment
   */
  ID: z.string().nullable().optional(),
  /**
   * Payment reference number
   */
  Reference: z.string().nullable().optional(),
  /**
   * Payment amount in customer currency
   */
  Amount: z.number().nullable().optional(),
  /**
   * Date when payment has been made
   */
  DatePaid: z.string().nullable().optional(),
  /**
   * Account Code of the bank/payment account from Chart of accounts
   */
  Account: z.string().nullable().optional(),
  /**
   * Currency Conversion rate expressed as number of Base currency units for one Customer
   * currency unit.
   */
  CurrencyRate: z.number().nullable().optional(),
  /**
   * Date of creation payment record.
   */
  DateCreated: z.string().nullable().optional()
});

export type SalePaymentLine = z.infer<typeof SalePaymentLineSchema>;

/**
 * Sale Additional Charge Model
 */
export const SaleAdditionalChargeSchema = z.looseObject({
  /**
   * Name of Service Product referenced by this Line Max length: 256. Required.
   */
  Description: z.string().nullable().optional(),
  /**
   * Price per unit in Customer currency Required.
   */
  Price: z.number().nullable().optional(),
  /**
   * Product or service quantity. Minimal value is 1. Required.
   */
  Quantity: z.number().nullable().optional(),
  /**
   * Discount. Value between 0 and 100. For free items discount is 100. Default value is 0
   */
  Discount: z.number().nullable().optional(),
  /**
   * Tax Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Line Total. For validation
   */
  Total: z.number().nullable().optional(),
  /**
   * Line Tax Rule name. Max length: 50. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Comment Max length: 1024.
   */
  Comment: z.string().nullable().optional()
});

export type SaleAdditionalCharge = z.infer<typeof SaleAdditionalChargeSchema>;

/**
 * Sale Fulfilment Pick
 */
export const SaleFulfilmentPickSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale Task ID Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Pick status. Possible Values are `NOT AVAILABLE`, `DRAFT`, `AUTHORISED`, `VOIDED`. For
   * `POST` available values are `DRAFT`, `AUTHORISED` Required.
   */
  Status: z.string().nullable().optional(),
  Lines: z.array(SaleFulfilmentPickPackLineSchema).nullable().optional()
});

export type SaleFulfilmentPick = z.infer<typeof SaleFulfilmentPickSchema>;

/**
 * Sale Fulfilment Pack
 */
export const SaleFulfilmentPackSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale Task ID Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Pack status. Possible Values are `NOT AVAILABLE`, `DRAFT`, `AUTHORISED`, `VOIDED`. For
   * `POST` available values are `DRAFT`, `AUTHORISED` Required.
   */
  Status: z.string().nullable().optional(),
  Lines: z.array(SaleFulfilmentPickPackLineSchema).nullable().optional()
});

export type SaleFulfilmentPack = z.infer<typeof SaleFulfilmentPackSchema>;

/**
 * Sale Manual Journal Line Model
 */
export const SaleManualJournalLineSchema = z.looseObject({
  /**
   * Reference Service Product
   */
  Reference: z.string().nullable().optional(),
  /**
   * Amount in base currency for manual journal Required.
   */
  Amount: z.number().nullable().optional(),
  /**
   * Effective date of manual journal Required.
   */
  Date: z.string().nullable().optional(),
  /**
   * Debit Account Required.
   */
  Debit: z.string().nullable().optional(),
  /**
   * Credit Account Required.
   */
  Credit: z.string().nullable().optional()
});

export type SaleManualJournalLine = z.infer<typeof SaleManualJournalLineSchema>;

/**
 * Sale Shipping Address Model
 */
export const SaleShippingAddressSchema = z.looseObject({
  /**
   * Address ID, optional. If specified then existing address is taken by ID. Ignored if
   * ShipToOther = true
   */
  ID: z.string().nullable().optional(),
  /**
   * Address Line 1 as displayed on Sale form. = Line1 + Line2 Max length: 256.
   */
  DisplayAddressLine1: z.string().nullable().optional(),
  /**
   * Address Line 2 as displayed on Sale form. = City + State/Region + Zip/Postcode + Country
   * Max length: 256.
   */
  DisplayAddressLine2: z.string().nullable().optional(),
  /**
   * Address Line 1 Max length: 256. Required.
   */
  Line1: z.string().nullable().optional(),
  /**
   * Address Line 2 Max length: 256.
   */
  Line2: z.string().nullable().optional(),
  /**
   * City Max length: 256.
   */
  City: z.string().nullable().optional(),
  /**
   * State Max length: 256.
   */
  State: z.string().nullable().optional(),
  /**
   * Post code Max length: 20.
   */
  Postcode: z.string().nullable().optional(),
  /**
   * Country Max length: 256. Required.
   */
  Country: z.string().nullable().optional(),
  /**
   * Company Name Max length: 128.
   */
  Company: z.string().nullable().optional(),
  /**
   * Contact Max length: 512.
   */
  Contact: z.string().nullable().optional(),
  /**
   * If false and Customer's address matching Line 1 not found, than new customer shipping
   * address will be created.
   */
  ShipToOther: z.boolean().nullable().optional()
});

export type SaleShippingAddress = z.infer<typeof SaleShippingAddressSchema>;

/**
 * Sale Transaction Line Model
 */
export const SaleTransactionLineSchema = z.looseObject({
  /**
   * Identifier of sale task
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Identifier of transaction
   */
  TransactionID: z.string().nullable().optional(),
  /**
   * Debit Account
   */
  Debit: z.string().nullable().optional(),
  /**
   * Credit Account
   */
  Credit: z.string().nullable().optional(),
  /**
   * Transaction description
   */
  Description: z.string().nullable().optional(),
  /**
   * Amount in base currency
   */
  Amount: z.number().nullable().optional(),
  /**
   * Transaction Date
   */
  EffectiveDate: z.string().nullable().optional()
});

export type SaleTransactionLine = z.infer<typeof SaleTransactionLineSchema>;

/**
 * Sale Quote
 */
export const SaleQuoteSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale ID Required.
   */
  SaleID: z.string().nullable().optional(),
  /**
   * if `true` then `additional charges` lines displayed in `Lines` array Required.
   */
  CombineAdditionalCharges: z.boolean().nullable().optional(),
  /**
   * Additional information for Quote Max length: 1024. Required.
   */
  Memo: z.string().nullable().optional(),
  /**
   * Quote Status. Possible Values are values . For POST only `DRAFT` and `AUTHORISED` values
   * accepted Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Required.
   */
  Lines: z.array(SaleQuoteLineSchema).nullable().optional(),
  AdditionalCharges: z.array(SaleAdditionalChargeSchema).nullable().optional(),
  /**
   * Sum of quote lines and additional charges without taxes. Not required for POST.
   * Required.
   */
  TotalBeforeTax: z.number().nullable().optional(),
  /**
   * Sum of quote lines and additional charges taxes. Not required for POST. Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Sum of quote lines and additional charges with taxes. Not required for POST. Required.
   */
  Total: z.number().nullable().optional()
});

export type SaleQuote = z.infer<typeof SaleQuoteSchema>;

/**
 * Sale Order
 */
export const SaleOrderSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale ID Required.
   */
  SaleID: z.string().nullable().optional(),
  /**
   * Sale Order Number (auto-generated) Max length: 256.
   */
  SaleOrderNumber: z.string().nullable().optional(),
  /**
   * if `true` then `additional charges` lines displayed in `Lines` array Required.
   */
  CombineAdditionalCharges: z.boolean().nullable().optional(),
  /**
   * Additional information for Order Max length: 1024. Required.
   */
  Memo: z.string().nullable().optional(),
  /**
   * Order Status. Possible Values are values . For POST only `DRAFT` and `AUTHORISED` values
   * accepted Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Required.
   */
  Lines: z.array(SaleOrderLineSchema).nullable().optional(),
  AdditionalCharges: z.array(SaleAdditionalChargeSchema).nullable().optional(),
  /**
   * Sum of order lines and additional charges without taxes. Not required for POST.
   * Required.
   */
  TotalBeforeTax: z.number().nullable().optional(),
  /**
   * Sum of order lines and additional charges taxes. Not required for POST. Required.
   */
  Tax: z.number().nullable().optional(),
  /**
   * Sum of order lines and additional charges with taxes. Not required for POST. Required.
   */
  Total: z.number().nullable().optional()
});

export type SaleOrder = z.infer<typeof SaleOrderSchema>;

/**
 * Sale Invoice Model
 */
export const SaleInvoiceSchema = z.looseObject({
  /**
   * Identifier of sale Invoice task Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Invoice Number (auto-generated)
   */
  InvoiceNumber: z.string().nullable().optional(),
  /**
   * Additional information for Invoice. Max length: 1024.
   */
  Memo: z.string().nullable().optional(),
  /**
   * Invoice status. Possible Values are values . For `POST` available values are `DRAFT`,
   * `AUTHORISED` Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Invoice Date. Required.
   */
  InvoiceDate: z.string().nullable().optional(),
  /**
   * Invoice Due Date. Required.
   */
  InvoiceDueDate: z.string().nullable().optional(),
  CurrencyConversionRate: z.number().nullable().optional(),
  /**
   * Billing Address Line 1 Max length: 256.
   */
  BillingAddressLine1: z.string().nullable().optional(),
  /**
   * Billing Address Line 2 Max length: 256.
   */
  BillingAddressLine2: z.string().nullable().optional(),
  /**
   * Number of Fulfilment linked to this invoice
   */
  LinkedFulfillmentNumber: z.string().nullable().optional(),
  Lines: z.array(SaleInvoiceLineSchema).nullable().optional(),
  AdditionalCharges: z.array(SaleInvoiceAdditionalChargeSchema).nullable().optional(),
  Payments: z.array(SalePaymentLineSchema).nullable().optional(),
  /**
   * Sum of Invoice lines and additional charges without taxes
   */
  TotalBeforeTax: z.number().nullable().optional(),
  /**
   * Sum of Invoice lines and additional charges taxes
   */
  Tax: z.number().nullable().optional(),
  /**
   * Sum of Invoice lines and additional charges with taxes
   */
  Total: z.number().nullable().optional(),
  /**
   * Sum of payments.
   */
  Paid: z.number().nullable().optional()
});

export type SaleInvoice = z.infer<typeof SaleInvoiceSchema>;

/**
 * Sale Invoice Partial Model
 */
export const SaleInvoicePartialSchema = z.looseObject({
  /**
   * Identifier of sale Invoice task Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * if `true` then `additional charges` lines displayed in `Lines` array Required.
   */
  CombineAdditionalCharges: z.boolean().nullable().optional(),
  /**
   * Invoice Number (auto-generated)
   */
  InvoiceNumber: z.string().nullable().optional(),
  /**
   * Additional information for Invoice. Max length: 1024.
   */
  Memo: z.string().nullable().optional(),
  /**
   * Invoice status. Possible Values are values . For `POST` available values are `DRAFT`,
   * `AUTHORISED` Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Invoice Date. Required.
   */
  InvoiceDate: z.string().nullable().optional(),
  /**
   * Invoice Due Date. Required.
   */
  InvoiceDueDate: z.string().nullable().optional(),
  CurrencyConversionRate: z.number().nullable().optional(),
  /**
   * Billing Address Line 1 Max length: 256.
   */
  BillingAddressLine1: z.string().nullable().optional(),
  /**
   * Billing Address Line 2 Max length: 256.
   */
  BillingAddressLine2: z.string().nullable().optional(),
  /**
   * Number of Fulfilment linked to this invoice
   */
  LinkedFulfillmentNumber: z.string().nullable().optional(),
  Lines: z.array(SaleInvoiceLineSchema).nullable().optional(),
  AdditionalCharges: z.array(SaleInvoiceAdditionalChargeSchema).nullable().optional()
});

export type SaleInvoicePartial = z.infer<typeof SaleInvoicePartialSchema>;

/**
 * Sale Credit Note Model
 */
export const SaleCreditNoteSchema = z.looseObject({
  /**
   * Identifier of sale Invoice task Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Number of Invoice linked to this Credit Note Required.
   */
  CreditNoteInvoiceNumber: z.string().nullable().optional(),
  /**
   * Additional information for Credit Note. Max length: 1024.
   */
  Memo: z.string().nullable().optional(),
  /**
   * Credit Note status. Possible Values are `NOT AVAILABLE`, `DRAFT`, `AUTHORISED`,
   * `VOIDED`. For `POST` available values are `DRAFT`, `AUTHORISED` Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Credit Note Date. Required.
   */
  CreditNoteDate: z.string().nullable().optional(),
  /**
   * Credit Note Number (auto-generated)
   */
  CreditNoteNumber: z.string().nullable().optional(),
  CreditNoteConversionRate: z.number().nullable().optional(),
  Lines: z.array(SaleInvoiceLineSchema).nullable().optional(),
  AdditionalCharges: z.array(SaleInvoiceAdditionalChargeSchema).nullable().optional(),
  Refunds: z.array(SalePaymentLineSchema).nullable().optional(),
  Restock: z.array(SaleFulfilmentPickPackLineSchema).nullable().optional(),
  /**
   * Sum of Credit Note lines and additional charges without taxes
   */
  TotalBeforeTax: z.number().nullable().optional(),
  /**
   * Sum of Credit Note lines and additional charges taxes
   */
  Tax: z.number().nullable().optional(),
  /**
   * Sum of Credit Note lines and additional charges with taxes
   */
  Total: z.number().nullable().optional()
});

export type SaleCreditNote = z.infer<typeof SaleCreditNoteSchema>;

/**
 * Sale Fulfilment Ship
 */
export const SaleFulfilmentShipSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale Task ID Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Ship status. Possible Values are `NOT AVAILABLE`, `DRAFT`, `PARTIALLY AUTHORISED`,
   * `AUTHORISED`, `VOIDED`. For `POST`/`PUT` available values are `DRAFT`, `PARTIALLY
   * AUTHORISED`, `AUTHORISED` Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Require By Date. Setting this will set or override the Required by date of the sale
   * order.
   */
  RequireBy: z.string().nullable().optional(),
  /**
   * Shipping Address
   */
  ShippingAddress: SaleShippingAddressSchema.nullable().optional(),
  /**
   * Shipping Notes Max length: 1024.
   */
  ShippingNotes: z.string().nullable().optional(),
  Lines: z.array(SaleFulfilmentShipLineSchema).nullable().optional()
});

export type SaleFulfilmentShip = z.infer<typeof SaleFulfilmentShipSchema>;

/**
 * Sale Manual Journal Model
 */
export const SaleManualJournalSchema = z.looseObject({
  /**
   * Manual Journal Status. Available values are `NOT AVAILABLE`, `DRAFT`, `AUTHORISED`.
   * Available values for POST are `DRAFT`, `AUTHORISED` Required.
   */
  Status: z.string().nullable().optional(),
  Lines: z.array(SaleManualJournalLineSchema).nullable().optional()
});

export type SaleManualJournal = z.infer<typeof SaleManualJournalSchema>;

/**
 * Sale Fulfilment Pick Pack Model
 */
export const SaleFulfilmentPickPackSchema = z.looseObject({
  /**
   * Pick/Pack status. Possible Values are `NOT AVAILABLE`, `DRAFT`, `AUTHORISED`, `VOIDED`
   * Required.
   */
  Status: z.string().nullable().optional(),
  Lines: z.array(SaleFulfilmentPickPackLineSchema).nullable().optional()
});

export type SaleFulfilmentPickPack = z.infer<typeof SaleFulfilmentPickPackSchema>;

/**
 * Inventory Movement Line Model
 */
export const InventoryMovementLineSchema = z.looseObject({
  /**
   * Identifier of sale Invoice task
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Product identifier referenced by this Line.
   */
  ProductID: z.string().nullable().optional(),
  /**
   * Inventory Movement Date
   */
  Date: z.string().nullable().optional(),
  /**
   * Inventory Movement Amount
   */
  COGS: z.unknown().nullable().optional()
});

export type InventoryMovementLine = z.infer<typeof InventoryMovementLineSchema>;

/**
 * Sale Fulfilment Model
 */
export const SaleFulfilmentSchema = z.looseObject({
  /**
   * Identifier of sale fulfilment task Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Fulfillment Number (auto-generated) Required.
   */
  FulfillmentNumber: z.number().nullable().optional(),
  /**
   * Invoice number linked to this fulfilment
   */
  LinkedInvoiceNumber: z.string().nullable().optional(),
  /**
   * Fulfilment status. Possible Values are `NOT AVAILABLE`, `NOT FULFILLED`, `FULFILLED`,
   * `PARTIALLY FULFILLED`, `VOIDED` Required.
   */
  FulFilmentStatus: z.string().nullable().optional(),
  Pick: SaleFulfilmentPickPackSchema.nullable().optional(),
  Pack: SaleFulfilmentPickPackSchema.nullable().optional(),
  Ship: SaleFulfilmentShipSchema.nullable().optional()
});

export type SaleFulfilment = z.infer<typeof SaleFulfilmentSchema>;

/**
 * Sale
 */
export const SaleSchema = z.looseObject({
  /**
   * Unique Cin7 Core Sale ID. Required for PUT
   */
  ID: z.string().nullable().optional(),
  /**
   * Customer name Max length: 256.
   */
  Customer: z.string().nullable().optional(),
  /**
   * Customer identifier
   */
  CustomerID: z.string().nullable().optional(),
  /**
   * Customer Contact name Max length: 256.
   */
  Contact: z.string().nullable().optional(),
  /**
   * Customer Contact phone Max length: 50.
   */
  Phone: z.string().nullable().optional(),
  /**
   * Customer Contact email Max length: 256.
   */
  Email: z.string().nullable().optional(),
  /**
   * Account code used by default for invoice lines when no revenue account is defined on
   * Product. By default it is equal to Customer Sale account Max length: 50.
   */
  DefaultAccount: z.string().nullable().optional(),
  /**
   * `True` if there is no quote in the sale
   */
  SkipQuote: z.boolean().nullable().optional(),
  /**
   * Sale Billing address
   */
  BillingAddress: z.unknown().nullable().optional(),
  /**
   * Sale Shipping address
   */
  ShippingAddress: SaleShippingAddressSchema.nullable().optional(),
  /**
   * Shipping Notes Max length: 1024.
   */
  ShippingNotes: z.string().nullable().optional(),
  /**
   * 3 character currency code of Base Currency defined in General Settings on the moment
   * when Sale was created. Max length: 3.
   */
  BaseCurrency: z.string().nullable().optional(),
  /**
   * 3 character currency code of customer Currency defined in Customer card at the moment
   * when customer is selected for the Sale. Max length: 3.
   */
  CustomerCurrency: z.string().nullable().optional(),
  /**
   * Default Tax Rule name selected for Sale Max length: 50.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * `Inclusive` or `Exclusive`
   */
  TaxCalculation: z.string().nullable().optional(),
  /**
   * Payment terms name Max length: 256.
   */
  Terms: z.string().nullable().optional(),
  /**
   * Price Tier name selected for Sale Max length: 50.
   */
  PriceTier: z.string().nullable().optional(),
  /**
   * Date when shipment is due
   */
  ShipBy: z.string().nullable().optional(),
  /**
   * Default location to pick stock from Max length: 256.
   */
  Location: z.string().nullable().optional(),
  /**
   * Date when task was created
   */
  SaleOrderDate: z.string().nullable().optional(),
  /**
   * UTC Time
   */
  LastModifiedOn: z.string().nullable().optional(),
  /**
   * Custom Sale note Max length: 1024.
   */
  Note: z.string().nullable().optional(),
  /**
   * Reference number used by customer to identify this sale. Could be a purchase order
   * number generated by customer. Max length: 256.
   */
  CustomerReference: z.string().nullable().optional(),
  /**
   * COGS amount in base currency
   */
  COGSAmount: z.number().nullable().optional(),
  /**
   * Sale Status, see possible values Max length: 25.
   */
  Status: z.string().nullable().optional(),
  /**
   * Pick status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `PICKED`, `PICKING` , `NOT
   * PICKED` , `PARTIALLY PICKED` Max length: 20. Required.
   */
  CombinedPickingStatus: z.string().nullable().optional(),
  /**
   * Pack status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `PACKED`, `PACKING`, `NOT
   * PACKED`, `PARTIALLY PACKED` Max length: 20. Required.
   */
  CombinedPackingStatus: z.string().nullable().optional(),
  /**
   * Ship status. Possible Values are `VOIDED`, `NOT AVAILABLE`, `SHIPPED`, `SHIPPING` , `NOT
   * SHIPPED` , `PARTIALLY SHIPPED` Max length: 20. Required.
   */
  CombinedShippingStatus: z.string().nullable().optional(),
  /**
   * Fulfilment status. Possible Values are `FULFILLED`, `PARTIALLY FULFILLED`, `NOT
   * AVAILABLE`, `NOT FULFILLED`, `VOIDED` Max length: 20.
   */
  FulFilmentStatus: z.string().nullable().optional(),
  /**
   * Invoice status. Possible Values are `VOIDED`, `DRAFT`, `AUTHORISED`, `NOT AVAILABLE`,
   * `PAID` Max length: 20.
   */
  CombinedInvoiceStatus: z.string().nullable().optional(),
  /**
   * Payment status. Possible Values are `NOT REFUNDED`, `PREPAID`, `PARTIALLY PAID`,
   * `UNPAID`, `PAID`, `VOIDED` Max length: 20.
   */
  CombinedPaymentStatus: z.string().nullable().optional(),
  /**
   * Tracking Numbers Max length: 256.
   */
  CombinedTrackingNumbers: z.string().nullable().optional(),
  /**
   * Max length: 256.
   */
  Carrier: z.string().nullable().optional(),
  /**
   * Conversion Rate expressed as number of Base currency units for one Customer currency
   * unit Max length: Up to 5 decimal places.
   */
  CurrencyRate: z.number().nullable().optional(),
  /**
   * Sales representative name Max length: 256.
   */
  SalesRepresentative: z.string().nullable().optional(),
  /**
   * Type of sale: `Simple Sale` or `Advanced Sale`, `Service Sale` Max length: 50.
   */
  Type: z.string().nullable().optional(),
  /**
   * Source of the sale. read-only field Max length: 32.
   */
  SourceChannel: z.string().nullable().optional(),
  /**
   * Custom field that is only available in API and allows to set arbitrary value for the
   * sale for later search and any custom logic Max length: 256.
   */
  ExternalID: z.string().nullable().optional(),
  /**
   * `true` when it is service-only sale
   */
  ServiceOnly: z.boolean().nullable().optional(),
  /**
   * Sale Quote
   */
  Quote: SaleQuoteSchema.nullable().optional(),
  /**
   * Sale Order
   */
  Order: SaleOrderSchema.nullable().optional(),
  /**
   * Sale Fulfilments
   */
  Fulfilments: z.array(SaleFulfilmentSchema).nullable().optional(),
  /**
   * Sale Invoices
   */
  Invoices: z.array(SaleInvoiceSchema).nullable().optional(),
  /**
   * Sale Credit Notes
   */
  CreditNotes: z.array(SaleCreditNoteSchema).nullable().optional(),
  /**
   * Sale Manual Journals
   */
  ManualJournals: SaleManualJournalSchema.nullable().optional(),
  /**
   * Sale Additional Attributes
   */
  AdditionalAttributes: z.unknown().nullable().optional(),
  /**
   * Sale Attachments
   */
  Attachments: z.array(z.unknown()).nullable().optional(),
  /**
   * Sale Inventory Movements
   */
  InventoryMovements: z.array(InventoryMovementLineSchema).nullable().optional(),
  /**
   * Sale Transactions
   */
  Transactions: z.array(SaleTransactionLineSchema).nullable().optional()
});

export type Sale = z.infer<typeof SaleSchema>;

export const SalePaymentSchema = SalePaymentLinePartialSchema;

export type SalePayment = z.infer<typeof SalePaymentSchema>;
