// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Stock adjustments, takes and transfers. https://dearinventory.docs.apiary.io/#reference/stock
 */

/**
 * Stock Adjustment
 */
export const StockAdjustmentSchema = z.looseObject({
  /**
   * Unique Cin7 Core Stock Adjustment ID
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Date of transaction
   */
  EffectiveDate: z.string().nullable().optional(),
  /**
   * Stock Take/Adjustment Number
   */
  StocktakeNumber: z.string().nullable().optional(),
  /**
   * Status of stock adjustment. Available values are `DRAFT`,`COMPLETED`,`VOIDED`.
   */
  Status: z.string().nullable().optional(),
  /**
   * Expense account for inventory adjustment
   */
  Account: z.string().nullable().optional(),
  /**
   * Custom reference
   */
  Reference: z.string().nullable().optional(),
  /**
   * Changes in non-zero stock
   */
  ExistingStockLines: z.array(z.unknown()).nullable().optional(),
  /**
   * Changes in zero stock
   */
  NewStockLines: z.array(z.unknown()).nullable().optional(),
  /**
   * Created transactions due to stock changes.
   */
  Transactions: z.array(z.unknown()).nullable().optional()
});

export type StockAdjustment = z.infer<typeof StockAdjustmentSchema>;

/**
 * Stock Adjustment List
 */
export const StockAdjustmentListSchema = z.looseObject({
  /**
   * Unique Cin7 Core Stock Adjustment ID
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Date of transaction
   */
  EffectiveDate: z.string().nullable().optional(),
  /**
   * Stock Number (auto-generated).
   */
  StocktakeNumber: z.string().nullable().optional(),
  /**
   * Status of stock adjustment. Available values are `DRAFT`,`COMPLETED`,`VOIDED`.
   */
  Status: z.string().nullable().optional(),
  /**
   * Expense account for inventory adjustment
   */
  Account: z.string().nullable().optional(),
  /**
   * Custom reference
   */
  Reference: z.string().nullable().optional(),
  /**
   * Comment
   */
  Comment: z.string().nullable().optional()
});

export type StockAdjustmentList = z.infer<typeof StockAdjustmentListSchema>;

/**
 * Stock Take
 */
export const StockTakeSchema = z.looseObject({
  /**
   * Unique Cin7 Core Stock Take ID. Required for PUT Required (conditional).
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Date of transaction Required.
   */
  EffectiveDate: z.string().nullable().optional(),
  /**
   * Stock Take Number (auto-generated).
   */
  StocktakeNumber: z.string().nullable().optional(),
  /**
   * Status of stocktake. Available values are `DRAFT`, `IN PROGRESS`, `COMPLETED`, `VOIDED`.
   * Required for PUT Required (conditional).
   */
  Status: z.string().nullable().optional(),
  /**
   * Expense account for inventory adjustment Required.
   */
  Account: z.string().nullable().optional(),
  /**
   * Location ID. Required if `Location` is empty Required (conditional).
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Required (conditional).
   */
  Location: z.string().nullable().optional(),
  /**
   * Tags used for additional product filtration. Can be used to filter
   * NonZeroStockOnHandProducts
   */
  Tags: z.array(z.string()).nullable().optional(),
  /**
   * Pick Zones used for additional product filtration. Can be used to filter
   * NonZeroStockOnHandProducts
   */
  PickZones: z.array(z.string()).nullable().optional(),
  /**
   * Stock Locators used for additional product filtration. Can be used to filter
   * NonZeroStockOnHandProducts
   */
  StockLocators: z.array(z.string()).nullable().optional(),
  /**
   * Categories used for additional product filtration. Can be used to filter
   * NonZeroStockOnHandProducts
   */
  Categories: z.array(z.unknown()).nullable().optional(),
  /**
   * Brands used for additional product filtration. Can be used to filter
   * NonZeroStockOnHandProducts
   */
  Brands: z.array(z.unknown()).nullable().optional(),
  /**
   * Bins used for additional product filtration. Can be used to filter
   * NonZeroStockOnHandProducts
   */
  Bins: z.array(z.unknown()).nullable().optional(),
  /**
   * Custom reference
   */
  Reference: z.string().nullable().optional(),
  /**
   * Lines will be automaticaly filled with filtered products which have non empty stock.(in
   * POST method or in PUT method if status is changing from `DRAFT` to `IN PROGRESS`. If
   * current `Status` is `IN PROGRESS`, lines can be passed to PUT method (line entry will be
   * found by product, location, batchSN and expiryDate and passed `Adjustment` will be set
   * as new `Adjustment`)
   */
  NonZeroStockOnHandProducts: z.array(z.unknown()).nullable().optional(),
  ZeroStockOnHandProducts: z.array(z.unknown()).nullable().optional(),
  /**
   * Created transactions due to stock changes.
   */
  Transactions: z.array(z.unknown()).nullable().optional(),
  /**
   * Indicates whether zero-stock products should be included in the stocktake. true –
   * includes products with zero stock false – excludes products with zero stock
   */
  UseRelativeQuantity: z.boolean().nullable().optional()
});

export type StockTake = z.infer<typeof StockTakeSchema>;

/**
 * Stock Take List
 */
export const StockTakeListSchema = z.looseObject({
  /**
   * Unique Cin7 Core Stock Take ID
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Date of transaction
   */
  EffectiveDate: z.string().nullable().optional(),
  /**
   * Stock Take Number (auto-generated).
   */
  StocktakeNumber: z.string().nullable().optional(),
  /**
   * Status of stock take. Available values are `DRAFT`,`COMPLETED`,`VOIDED`.
   */
  Status: z.string().nullable().optional(),
  /**
   * Expense account for inventory stocktake
   */
  Account: z.string().nullable().optional(),
  /**
   * Location ID
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Location Name
   */
  Location: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom tags
   */
  Tags: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom pick zones
   */
  PickZones: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom stock locators
   */
  StockLocators: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom categories
   */
  Categories: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom brands
   */
  Brands: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom bins
   */
  Bins: z.string().nullable().optional(),
  /**
   * Custom reference
   */
  Reference: z.string().nullable().optional(),
  /**
   * Date of creation stocktake
   */
  CreatedDate: z.string().nullable().optional(),
  /**
   * Date and time when stocktake was last time modified
   */
  LastUpdatedDate: z.string().nullable().optional(),
  /**
   * User which made last update
   */
  LastUpdatedBy: z.string().nullable().optional()
});

export type StockTakeList = z.infer<typeof StockTakeListSchema>;

/**
 * Stock Transfer List
 */
export const StockTransferListSchema = z.looseObject({
  /**
   * Unique Cin7 Core Stock Transfer ID
   */
  TaskID: z.string().nullable().optional(),
  /**
   * ID of location from which transfer was done
   */
  From: z.string().nullable().optional(),
  /**
   * Name of location from which transfer was done
   */
  FromLocation: z.string().nullable().optional(),
  /**
   * ID of location to which transfer was done
   */
  To: z.string().nullable().optional(),
  /**
   * Name of location to which transfer was done
   */
  ToLocation: z.string().nullable().optional(),
  /**
   * Status of stock transfer. Available values are `DRAFT`, `IN
   * TRANSIT`,`COMPLETED`,`VOIDED`.
   */
  Status: z.string().nullable().optional(),
  /**
   * Stock Transfer Number (auto-generated).
   */
  Number: z.string().nullable().optional(),
  /**
   * Date of transaction
   */
  CompletionDate: z.string().nullable().optional(),
  /**
   * Type of additional journals capitalization cost distribution. Available values are
   * `Cost`, `Quantity`,`Weight`,`Volume`.
   */
  CostDistributionType: z.string().nullable().optional(),
  /**
   * Asset Account holding stock value while it is in transit.
   */
  InTransitAccount: z.string().nullable().optional(),
  /**
   * Date when stock left the From warehouse.
   */
  DepartureDate: z.string().nullable().optional(),
  /**
   * Custom reference
   */
  Reference: z.string().nullable().optional(),
  /**
   * Date of last modification. UTC Time. Read-only.
   */
  LastModifiedOn: z.string().nullable().optional()
});

export type StockTransferList = z.infer<typeof StockTransferListSchema>;

/**
 * Stock Transfer Order
 */
export const StockTransferOrderSchema = z.looseObject({
  /**
   * Unique Cin7 Core Stock Transfer ID Required.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Status of stock transfer order. Available values are `DRAFT`, `AUTHORISED`, `NOT
   * AVAILABLE`. Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Required.
   */
  Lines: z.array(z.unknown()).nullable().optional(),
  /**
   * Date of last modification. UTC Time. Read-only.
   */
  LastModifiedOn: z.string().nullable().optional()
});

export type StockTransferOrder = z.infer<typeof StockTransferOrderSchema>;

/**
 * Inventory Write-Off
 */
export const InventoryWriteOffSchema = z.looseObject({
  /**
   * Unique ID.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Inventory Write-Off Number
   */
  InventoryWriteOffNumber: z.string().nullable().optional(),
  /**
   * Inventory Write-Off Task Status. Available values are `DRAFT`, `COMPLETED`, `VOIDED`
   */
  Status: z.string().nullable().optional(),
  /**
   * Location ID
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Location Name
   */
  Location: z.string().nullable().optional(),
  /**
   * Expense Account
   */
  Account: z.string().nullable().optional(),
  /**
   * Effective Date
   */
  EffectiveDate: z.string().nullable().optional(),
  /**
   * Notes
   */
  Notes: z.string().nullable().optional(),
  Lines: z.array(z.unknown()).nullable().optional(),
  Transactions: z.array(z.unknown()).nullable().optional(),
  /**
   * If While processing `POST` or `PUT` method, some errors occurred, but task was created,
   * this property will contain array of error messages.
   */
  Errors: z.array(z.unknown()).nullable().optional()
});

export type InventoryWriteOff = z.infer<typeof InventoryWriteOffSchema>;

/**
 * Inventory Write-Off List
 */
export const InventoryWriteOffListSchema = z.looseObject({
  /**
   * Unique ID.
   */
  TaskID: z.string().nullable().optional(),
  /**
   * Inventory Write-Off Number
   */
  InventoryWriteOffNumber: z.string().nullable().optional(),
  /**
   * Inventory Write-Off Task Status. Available values are `DRAFT`, `COMPLETED`, `VOIDED`
   */
  Status: z.string().nullable().optional(),
  /**
   * Location ID
   */
  LocationID: z.string().nullable().optional(),
  /**
   * Location Name
   */
  Location: z.string().nullable().optional(),
  /**
   * Date When Task Created.
   */
  Date: z.string().nullable().optional(),
  /**
   * Notes
   */
  Notes: z.string().nullable().optional()
});

export type InventoryWriteOffList = z.infer<typeof InventoryWriteOffListSchema>;

/**
 * Stock Transfer
 */
export const StockTransferSchema = z.looseObject({
  /**
   * Unique Cin7 Core Stock Transfer ID.Required for PUT Required (conditional).
   */
  TaskID: z.string().nullable().optional(),
  /**
   * ID of location from which transfer was done. Required if FromLocation is null Required
   * (conditional).
   */
  From: z.string().nullable().optional(),
  /**
   * Name of location from which transfer was done. Required if From is null Required
   * (conditional).
   */
  FromLocation: z.string().nullable().optional(),
  /**
   * ID of location to which transfer was done. Required if ToLocation is null Required
   * (conditional).
   */
  To: z.string().nullable().optional(),
  /**
   * Name of location to which transfer was done. Required if To is null Required
   * (conditional).
   */
  ToLocation: z.string().nullable().optional(),
  /**
   * Status of stock transfer. Available values are `DRAFT`, `IN
   * TRANSIT`,`COMPLETED`,`VOIDED`. Required.
   */
  Status: z.string().nullable().optional(),
  /**
   * Stock Transfer Number (auto-generated).
   */
  Number: z.string().nullable().optional(),
  /**
   * Type of additional journals capitalization cost distribution. Available values are
   * `Cost`, `Quantity`,`Weight`,`Volume`. Default value is `Cost`
   */
  CostDistributionType: z.string().nullable().optional(),
  /**
   * Asset Account holding stock value while it is in transit. Required if `Status` is `IN
   * TRANSIT`. Required (conditional).
   */
  InTransitAccount: z.string().nullable().optional(),
  /**
   * Date when stock left the From warehouse. Required if `Status` is `IN TRANSIT`. Required
   * (conditional).
   */
  DepartureDate: z.string().nullable().optional(),
  /**
   * Date of transaction Required.
   */
  CompletionDate: z.string().nullable().optional(),
  /**
   * Date when stock is required to be delivered to destination warehouse.
   */
  RequiredByDate: z.string().nullable().optional(),
  /**
   * Custom reference
   */
  Reference: z.string().nullable().optional(),
  /**
   * Skip stock transfer order. Default value `true`.
   */
  SkipOrder: z.boolean().nullable().optional(),
  /**
   * Required.
   */
  Lines: z.array(z.unknown()).nullable().optional(),
  Order: StockTransferOrderSchema.nullable().optional(),
  /**
   * Date of last modification. UTC Time. Read-only.
   */
  LastModifiedOn: z.string().nullable().optional()
});

export type StockTransfer = z.infer<typeof StockTransferSchema>;
