// Generated by src/scripts/cin7-core-codegen.ts from the Cin7 Core API Blueprint.
// Run `yarn codegen:cin7-core` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Suppliers. https://dearinventory.docs.apiary.io/#reference/supplier
 */

/**
 * Supplier
 */
export const SupplierSchema = z.looseObject({
  /**
   * Unique Supplier ID. Required.
   */
  ID: z.string().nullable().optional(),
  /**
   * Name of Supplier. Max length: 256. Required.
   */
  Name: z.string().nullable().optional(),
  /**
   * Currency code of Supplier. Required.
   */
  Currency: z.string().nullable().optional(),
  /**
   * PaymentTerm name. Required.
   */
  PaymentTerm: z.string().nullable().optional(),
  /**
   * AccountPayable code of Supplier. Required.
   */
  AccountPayable: z.string().nullable().optional(),
  /**
   * TaxRule name. Required.
   */
  TaxRule: z.string().nullable().optional(),
  /**
   * Points that Supplier is Active. Can be `Active` or `Deprecated` Required (conditional).
   */
  Status: z.string().nullable().optional(),
  /**
   * Discount must be between 0% and 100%. 0% used as default.
   */
  Discount: z.number().nullable().optional(),
  /**
   * Comments. Max length: 256.
   */
  Comments: z.string().nullable().optional(),
  /**
   * TaxNumber.
   */
  TaxNumber: z.number().nullable().optional(),
  /**
   * AttributeSet name.
   */
  AttributeSet: z.string().nullable().optional(),
  /**
   * Additional attribute value. # - int(1-10).
   */
  'AdditionalAttribute#': z.string().nullable().optional(),
  /**
   * Date of last modification.
   */
  LastModifiedOn: z.string().nullable().optional(),
  /**
   * List of addresses.
   */
  Addresses: z.array(z.unknown()).nullable().optional(),
  /**
   * List of contacts.
   */
  Contacts: z.array(z.unknown()).nullable().optional()
});

export type Supplier = z.infer<typeof SupplierSchema>;
