/**
 * A client for the ShipHero public GraphQL API (https://developer.shiphero.com/).
 *
 * The client is a transport only: it handles token auth, refresh, credit throttling
 * and the rolling request ceiling, and executes whatever document you hand it. Queries
 * live in the calling project, generated by pointing graphql-codegen at ShipHero's live
 * endpoint (it supports introspection when authenticated) so adding one never requires
 * a change here — see the README for the codegen setup.
 *
 * ```ts
 * import { ShipHero } from 'easify/shiphero';
 * import { PurchaseOrdersDocument } from './generated/shiphero';
 *
 * const shiphero = new ShipHero({
 *   auth: { accessToken: '...', refreshToken: '...' },
 *   options: { customerAccountId: 'QWNjb3VudDoxMjM0' }
 * });
 *
 * // Result and variables are inferred from the generated document.
 * const data = await shiphero.query(PurchaseOrdersDocument, { updatedFrom: lastRun });
 * ```
 */
export { ShipHeroClient as ShipHero } from './client';
export { default } from './client';

export * from './client';
export * from './errors';
