// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Stock adjustments. https://api.cin7.com/api/Help#Adjustments
 */

export const AdjustmentLineItemSchema = z.looseObject({
  /**
   * Quantity Adjusted.
   */
  qtyAdjusted: z.number().nullable().optional(),
  /**
   * Holding Quantity.
   */
  holdingQty: z.number().nullable().optional(),
  /**
   * GL Account Code.
   */
  account: z.string().nullable().optional(),
  /**
   * Unit Cost.
   */
  unitCost: z.number().nullable().optional(),
  /**
   * The unique Cin7 ID
   */
  id: z.number().nullable().optional(),
  /**
   * Created date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Transaction ID e.g. Sales Order Id, Quote Id or Purchase Order Id
   */
  transactionId: z.number().nullable().optional(),
  /**
   * Parent Line Item ID (Read-only)
   */
  parentId: z.number().nullable().optional(),
  /**
   * Product ID (Read-only)
   */
  productId: z.number().nullable().optional(),
  /**
   * The product option ID (Optional); ProductOptionId or Code should be specified to link a
   * product to the line item.
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * Integration reference
   */
  integrationRef: z.string().nullable().optional(),
  /**
   * Sort (or sequence) of line items
   */
  sort: z.number().nullable().optional(),
  code: z.string().nullable().optional(),
  /**
   * Item name
   */
  name: z.string().nullable().optional(),
  /**
   * Option 1
   */
  option1: z.string().nullable().optional(),
  /**
   * Option 2
   */
  option2: z.string().nullable().optional(),
  /**
   * Option 3
   */
  option3: z.string().nullable().optional(),
  /**
   * Quantity
   */
  qty: z.number().nullable().optional()
});

export type AdjustmentLineItem = z.infer<typeof AdjustmentLineItemSchema>;

export const AdjustmentSchema = z.looseObject({
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Order created date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Order last modified date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * The ID for the User who created the Transaction.
   */
  createdBy: z.number().nullable().optional(),
  /**
   * The ID for the User who processed the Transaction.
   */
  processedBy: z.number().nullable().optional(),
  /**
   * Is Approved (default: true)
   */
  isApproved: z.boolean().nullable().optional(),
  /**
   * A unique order reference (leave blank to auto-generate in an insert). Max length: 20.
   */
  reference: z.string().nullable().optional(),
  /**
   * Branch ID.
   */
  branchId: z.number().nullable().optional(),
  /**
   * Completed Date. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  completedDate: z.string().nullable().optional(),
  /**
   * Date to adjust in Accounting system. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  adjustInAccountingSystem: z.string().nullable().optional(),
  /**
   * The reason for adjusting Stock.
   */
  adjustmentReason: z.string().nullable().optional(),
  /**
   * Alternative GL Account.
   */
  alternativeAccountCode: z.string().nullable().optional(),
  /**
   * Product Total.
   */
  productTotal: z.number().nullable().optional(),
  /**
   * The source of the Transaction.
   */
  source: z.string().nullable().optional(),
  /**
   * Line Items.
   */
  lineItems: z.array(AdjustmentLineItemSchema).nullable().optional()
});

export type Adjustment = z.infer<typeof AdjustmentSchema>;

export const AdjustmentCreateSchema = AdjustmentSchema;

export type AdjustmentCreate = z.infer<typeof AdjustmentCreateSchema>;

export const AdjustmentUpdateSchema = AdjustmentSchema;

export type AdjustmentUpdate = z.infer<typeof AdjustmentUpdateSchema>;
