// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Bill of materials masters. https://api.cin7.com/api/Help#BomMasters
 */

export const BomMasterProductComponentSchema = z.looseObject({
  /**
   * The unique Cin7 ID
   */
  id: z.number().nullable().optional(),
  /**
   * Product ID
   */
  productId: z.number().nullable().optional(),
  /**
   * Product option ID
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * Component Type (Make, Use, Addon). Documented values: Undefined, Make, Use, Addon.
   */
  type: z.string().nullable().optional(),
  /**
   * Sort Order
   */
  sort: z.number().nullable().optional(),
  /**
   * Item Code
   */
  code: z.string().nullable().optional(),
  /**
   * Item Name
   */
  name: z.string().nullable().optional(),
  /**
   * Option 1
   */
  option1: z.string().nullable().optional(),
  /**
   * Option 2
   */
  option2: z.string().nullable().optional(),
  /**
   * Option 3
   */
  option3: z.string().nullable().optional(),
  /**
   * Notes
   */
  notes: z.string().nullable().optional(),
  /**
   * Standard Qty
   */
  qty: z.number().nullable().optional(),
  /**
   * Unit Cost
   */
  unitCost: z.number().nullable().optional()
});

export type BomMasterProductComponent = z.infer<typeof BomMasterProductComponentSchema>;

export const BomMasterProductSchema = z.looseObject({
  /**
   * Product Components
   */
  components: z.array(BomMasterProductComponentSchema).nullable().optional(),
  /**
   * The unique Cin7 ID
   */
  id: z.number().nullable().optional(),
  /**
   * Product ID
   */
  productId: z.number().nullable().optional(),
  /**
   * Product option ID
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * Component Type (Make, Use, Addon). Documented values: Undefined, Make, Use, Addon.
   */
  type: z.string().nullable().optional(),
  /**
   * Sort Order
   */
  sort: z.number().nullable().optional(),
  /**
   * Item Code
   */
  code: z.string().nullable().optional(),
  /**
   * Item Name
   */
  name: z.string().nullable().optional(),
  /**
   * Option 1
   */
  option1: z.string().nullable().optional(),
  /**
   * Option 2
   */
  option2: z.string().nullable().optional(),
  /**
   * Option 3
   */
  option3: z.string().nullable().optional(),
  /**
   * Notes
   */
  notes: z.string().nullable().optional(),
  /**
   * Standard Qty
   */
  qty: z.number().nullable().optional(),
  /**
   * Unit Cost
   */
  unitCost: z.number().nullable().optional()
});

export type BomMasterProduct = z.infer<typeof BomMasterProductSchema>;

export const BomMasterSchema = z.looseObject({
  /**
   * Bom
   */
  product: BomMasterProductSchema.nullable().optional(),
  /**
   * A unique Job ID.
   */
  id: z.number().nullable().optional(),
  /**
   * Created date time. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Last modified date time. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * Created by User ID.
   */
  createdBy: z.number().nullable().optional(),
  /**
   * Modified by User ID.
   */
  modifiedBy: z.number().nullable().optional(),
  /**
   * Production Notes.
   */
  productionNotes: z.string().nullable().optional(),
  /**
   * The unique Job reference. Max length: 20.
   */
  reference: z.string().nullable().optional()
});

export type BomMaster = z.infer<typeof BomMasterSchema>;

/**
 * The v2 representation of a BOM master.
 */
export const BomMasterV2Schema = z.looseObject({
  products: z.array(BomMasterProductSchema).nullable().optional(),
  /**
   * A unique Job ID.
   */
  id: z.number().nullable().optional(),
  /**
   * Created date time. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Last modified date time. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * Created by User ID.
   */
  createdBy: z.number().nullable().optional(),
  /**
   * Modified by User ID.
   */
  modifiedBy: z.number().nullable().optional(),
  /**
   * Production Notes.
   */
  productionNotes: z.string().nullable().optional(),
  /**
   * The unique Job reference. Max length: 20.
   */
  reference: z.string().nullable().optional()
});

export type BomMasterV2 = z.infer<typeof BomMasterV2Schema>;
