// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Branch transfers. https://api.cin7.com/api/Help#BranchTransfers
 */

export const BranchTransferLineItemSizeSchema = z.looseObject({
  name: z.string().nullable().optional(),
  code: z.string().nullable().optional(),
  barcode: z.string().nullable().optional(),
  qty: z.number().nullable().optional()
});

export type BranchTransferLineItemSize = z.infer<typeof BranchTransferLineItemSizeSchema>;

export const BranchTransferLineItemSchema = z.looseObject({
  /**
   * The unique Cin7 ID
   */
  id: z.number().nullable().optional(),
  /**
   * Quantity Transferred; this field is read-only, Branch Transfers must be dispatched and
   * completed in Cin7.
   */
  qtyTransferred: z.number().nullable().optional(),
  /**
   * Unit Cost
   */
  unitCost: z.number().nullable().optional(),
  /**
   * Sizes; this field is read-only.
   */
  sizes: z.array(BranchTransferLineItemSizeSchema).nullable().optional(),
  /**
   * Created date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Transaction ID e.g. Sales Order Id, Quote Id or Purchase Order Id
   */
  transactionId: z.number().nullable().optional(),
  /**
   * Parent Line Item ID (Read-only)
   */
  parentId: z.number().nullable().optional(),
  /**
   * Product ID (Read-only)
   */
  productId: z.number().nullable().optional(),
  /**
   * The product option ID (Optional); ProductOptionId or Code should be specified to link a
   * product to the line item.
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * Integration reference
   */
  integrationRef: z.string().nullable().optional(),
  /**
   * Sort (or sequence) of line items
   */
  sort: z.number().nullable().optional(),
  code: z.string().nullable().optional(),
  /**
   * Item name
   */
  name: z.string().nullable().optional(),
  /**
   * Option 1
   */
  option1: z.string().nullable().optional(),
  /**
   * Option 2
   */
  option2: z.string().nullable().optional(),
  /**
   * Option 3
   */
  option3: z.string().nullable().optional(),
  /**
   * Quantity
   */
  qty: z.number().nullable().optional()
});

export type BranchTransferLineItem = z.infer<typeof BranchTransferLineItemSchema>;

export const BranchTransferSchema = z.looseObject({
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Order created date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Order last modified date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * The ID for the User who created the Transaction.
   */
  createdBy: z.number().nullable().optional(),
  /**
   * The ID for the User who processed the Transaction.
   */
  processedBy: z.number().nullable().optional(),
  /**
   * The ID of the User who approved the Branch Transfer.
   */
  approvedBy: z.number().nullable().optional(),
  /**
   * Is Approved (default: true)
   */
  isApproved: z.boolean().nullable().optional(),
  /**
   * A unique reference. Max length: 20.
   */
  reference: z.string().nullable().optional(),
  /**
   * Branch email Max length: 250.
   */
  branchEmail: z.string().nullable().optional(),
  /**
   * Delivery instructions e.g. Leave at the door, beware the dog. Max length: 2000.
   */
  deliveryInstructions: z.string().nullable().optional(),
  /**
   * Internal comment
   */
  internalComments: z.string().nullable().optional(),
  /**
   * Product Total
   */
  productTotal: z.number().nullable().optional(),
  /**
   * Contact first name Max length: 250.
   */
  firstName: z.string().nullable().optional(),
  /**
   * Contact last name Max length: 250.
   */
  lastName: z.string().nullable().optional(),
  /**
   * Contact company Max length: 250.
   */
  company: z.string().nullable().optional(),
  /**
   * Contact email address, could be different from MemberEmail assigned to the order Max
   * length: 250.
   */
  email: z.string().nullable().optional(),
  /**
   * Contact phone Max length: 50.
   */
  phone: z.string().nullable().optional(),
  /**
   * Contact mobile Max length: 50.
   */
  mobile: z.string().nullable().optional(),
  /**
   * Contact fax Max length: 50.
   */
  fax: z.string().nullable().optional(),
  /**
   * Project Name
   */
  projectName: z.string().nullable().optional(),
  /**
   * Shipping tracking code Max length: 50.
   */
  trackingCode: z.string().nullable().optional(),
  /**
   * The source of the Transaction.
   */
  source: z.string().nullable().optional(),
  /**
   * Source Branch ID
   */
  sourceBranchId: z.number().nullable().optional(),
  /**
   * Destination Branch ID
   */
  destinationBranchId: z.number().nullable().optional(),
  /**
   * Approval Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  approvalDate: z.string().nullable().optional(),
  /**
   * Dispatched Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  dispatchedDate: z.string().nullable().optional(),
  /**
   * Received Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  receivedDate: z.string().nullable().optional(),
  /**
   * Stage
   */
  stage: z.string().nullable().optional(),
  /**
   * Custom Fields The spec reflects this as an array of strings, but the API returns custom
   * fields keyed by name. Both shapes are accepted.
   */
  customFields: z
    .union([z.record(z.string(), z.unknown()), z.array(z.unknown())])
    .nullable()
    .optional(),
  lineItems: z.array(BranchTransferLineItemSchema).nullable().optional()
});

export type BranchTransfer = z.infer<typeof BranchTransferSchema>;

export const BranchTransferCreateSchema = BranchTransferSchema;

export type BranchTransferCreate = z.infer<typeof BranchTransferCreateSchema>;

export const BranchTransferUpdateSchema = BranchTransferSchema;

export type BranchTransferUpdate = z.infer<typeof BranchTransferUpdateSchema>;
