// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Branches. https://api.cin7.com/api/Help#Branches
 */

export const BranchBranchLocationSchema = z.looseObject({
  zone: z.string().nullable().optional(),
  bins: z.array(z.string()).nullable().optional()
});

export type BranchBranchLocation = z.infer<typeof BranchBranchLocationSchema>;

export const BranchSecondaryContactSchema = z.looseObject({
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Company Max length: 150.
   */
  company: z.string().nullable().optional(),
  /**
   * First Name Max length: 50.
   */
  firstName: z.string().nullable().optional(),
  /**
   * Last Name Max length: 50.
   */
  lastName: z.string().nullable().optional(),
  /**
   * Job Title Max length: 50.
   */
  jobTitle: z.string().nullable().optional(),
  /**
   * Email Max length: 50.
   */
  email: z.string().nullable().optional(),
  /**
   * Mobile Max length: 50.
   */
  mobile: z.string().nullable().optional(),
  /**
   * Phone Max length: 50.
   */
  phone: z.string().nullable().optional()
});

export type BranchSecondaryContact = z.infer<typeof BranchSecondaryContactSchema>;

export const BranchSchema = z.looseObject({
  /**
   * Branch Type Max length: 250.
   */
  branchType: z.string().nullable().optional(),
  /**
   * Stock control options.
   */
  stockControlOptions: z.string().nullable().optional(),
  /**
   * Tax Status
   */
  taxStatus: z.string().nullable().optional(),
  accountNumber: z.string().nullable().optional(),
  /**
   * Branch Locations.
   */
  branchLocations: z.array(BranchBranchLocationSchema).nullable().optional(),
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Created Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Modified Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * Is Active
   */
  isActive: z.boolean().nullable().optional(),
  /**
   * Company Max length: 250.
   */
  company: z.string().nullable().optional(),
  /**
   * First Name Max length: 250.
   */
  firstName: z.string().nullable().optional(),
  /**
   * Last Name Max length: 250.
   */
  lastName: z.string().nullable().optional(),
  /**
   * Job Title Max length: 250.
   */
  jobTitle: z.string().nullable().optional(),
  /**
   * A unique email address
   */
  email: z.string().nullable().optional(),
  /**
   * Website Max length: 50.
   */
  website: z.string().nullable().optional(),
  /**
   * Phone Max length: 50.
   */
  phone: z.string().nullable().optional(),
  /**
   * Fax Max length: 50.
   */
  fax: z.string().nullable().optional(),
  /**
   * Mobile Max length: 50.
   */
  mobile: z.string().nullable().optional(),
  /**
   * Address 1 Max length: 50.
   */
  address1: z.string().nullable().optional(),
  /**
   * Address 2 Max length: 50.
   */
  address2: z.string().nullable().optional(),
  /**
   * City Max length: 50.
   */
  city: z.string().nullable().optional(),
  /**
   * State Max length: 50.
   */
  state: z.string().nullable().optional(),
  /**
   * Post Code Max length: 50.
   */
  postCode: z.string().nullable().optional(),
  /**
   * Country Max length: 50.
   */
  country: z.string().nullable().optional(),
  /**
   * Billing/Postal Address 1 Max length: 50.
   */
  postalAddress1: z.string().nullable().optional(),
  /**
   * Billing/Postal Address 2 Max length: 50.
   */
  postalAddress2: z.string().nullable().optional(),
  /**
   * Billing/Postal City Max length: 50.
   */
  postalCity: z.string().nullable().optional(),
  /**
   * Billing/Postal Post Code Max length: 50.
   */
  postalPostCode: z.string().nullable().optional(),
  /**
   * Billing/Postal State Max length: 50.
   */
  postalState: z.string().nullable().optional(),
  /**
   * Billing/Postal Country Max length: 50.
   */
  postalCountry: z.string().nullable().optional(),
  /**
   * Notes Max length: 250.
   */
  notes: z.string().nullable().optional(),
  /**
   * Integration reference.
   */
  integrationRef: z.string().nullable().optional(),
  /**
   * Custom fields. The spec reflects this as an array of strings, but the API returns custom
   * fields keyed by name. Both shapes are accepted.
   */
  customFields: z
    .union([z.record(z.string(), z.unknown()), z.array(z.unknown())])
    .nullable()
    .optional(),
  /**
   * Secondary Contacts
   */
  secondaryContacts: z.array(BranchSecondaryContactSchema).nullable().optional()
});

export type Branch = z.infer<typeof BranchSchema>;

export const BranchCreateSchema = BranchSchema;

export type BranchCreate = z.infer<typeof BranchCreateSchema>;

export const BranchUpdateSchema = BranchSchema;

export type BranchUpdate = z.infer<typeof BranchUpdateSchema>;
