// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Sales order cartons. https://api.cin7.com/api/Help#Cartons
 */

export const CartonCartonItemSchema = z.looseObject({
  /**
   * Cin7 Sales Order Line Item ID
   */
  lineItemId: z.number().nullable().optional(),
  /**
   * Product Code/SKU. Used to match the LineItemId if none supplied. Max length: 50.
   */
  productCode: z.string().nullable().optional(),
  /**
   * Batch Number Max length: 50.
   */
  batchNumber: z.string().nullable().optional(),
  /**
   * Quantity
   */
  quantity: z.number().nullable().optional()
});

export type CartonCartonItem = z.infer<typeof CartonCartonItemSchema>;

export const CartonSchema = z.looseObject({
  /**
   * Carton Number. Numbers only. Max length: 20.
   */
  number: z.string().nullable().optional(),
  /**
   * SSCC Number. Numbers only. Max length: 20.
   */
  sscc: z.string().nullable().optional(),
  /**
   * Length
   */
  length: z.number().nullable().optional(),
  /**
   * Depth
   */
  depth: z.number().nullable().optional(),
  /**
   * Height
   */
  height: z.number().nullable().optional(),
  /**
   * Volume
   */
  volume: z.number().nullable().optional(),
  /**
   * Weight
   */
  weight: z.number().nullable().optional(),
  /**
   * Tracking Number Max length: 50.
   */
  trackingNumber: z.string().nullable().optional(),
  /**
   * Carton Items
   */
  cartonItems: z.array(CartonCartonItemSchema).nullable().optional()
});

export type Carton = z.infer<typeof CartonSchema>;

export const CartonUpdateSchema = CartonSchema;

export type CartonUpdate = z.infer<typeof CartonUpdateSchema>;
