// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Response envelopes shared by every Cin7 Omni endpoint.
 */

/**
 * The per-record result Cin7 returns for each item in a POST or PUT batch.
 */
export const UpsertResultSchema = z.looseObject({
  /**
   * The index at which the record was positioned in an insert or update.
   */
  index: z.number().nullable().optional(),
  /**
   * True if the record was successfully inserted or updated.
   */
  success: z.boolean().nullable().optional(),
  /**
   * The record Id.
   */
  id: z.number().nullable().optional(),
  /**
   * The record code.
   */
  code: z.string().nullable().optional(),
  /**
   * A list of errors if the insert or update fails.
   */
  errors: z.array(z.string()).nullable().optional()
});

export type UpsertResult = z.infer<typeof UpsertResultSchema>;

/**
 * The result Cin7 returns when a record is deleted.
 */
export const DeleteResultSchema = z.looseObject({
  /**
   * True if the record was successfully inserted or updated.
   */
  success: z.boolean().nullable().optional(),
  /**
   * The record Id.
   */
  id: z.number().nullable().optional(),
  /**
   * The record code.
   */
  code: z.string().nullable().optional(),
  /**
   * A list of errors if the insert or update fails.
   */
  errors: z.array(z.string()).nullable().optional()
});

export type DeleteResult = z.infer<typeof DeleteResultSchema>;

/**
 * The result Cin7 returns when a product image is uploaded.
 */
export const ImageUploadResultSchema = DeleteResultSchema;

export type ImageUploadResult = z.infer<typeof ImageUploadResultSchema>;
