// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * CRM contacts. https://api.cin7.com/api/Help#Contacts
 */

export const ContactAccountingIntegrationIdSchema = z.looseObject({
  xero: z.string().nullable().optional(),
  quickBooksOnline: z.string().nullable().optional(),
  quickBooksDesktop: z.string().nullable().optional()
});

export type ContactAccountingIntegrationId = z.infer<typeof ContactAccountingIntegrationIdSchema>;

export const ContactSecondaryContactSchema = z.looseObject({
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Company Max length: 150.
   */
  company: z.string().nullable().optional(),
  /**
   * First Name Max length: 50.
   */
  firstName: z.string().nullable().optional(),
  /**
   * Last Name Max length: 50.
   */
  lastName: z.string().nullable().optional(),
  /**
   * Job Title Max length: 50.
   */
  jobTitle: z.string().nullable().optional(),
  /**
   * Email Max length: 50.
   */
  email: z.string().nullable().optional(),
  /**
   * Mobile Max length: 50.
   */
  mobile: z.string().nullable().optional(),
  /**
   * Phone Max length: 50.
   */
  phone: z.string().nullable().optional()
});

export type ContactSecondaryContact = z.infer<typeof ContactSecondaryContactSchema>;

export const ContactSchema = z.looseObject({
  /**
   * Contact Type: Customer, Supplier Documented values: Internal, Customer, Supplier.
   */
  type: z.string().nullable().optional(),
  /**
   * The User Id
   */
  salesPersonId: z.number().nullable().optional(),
  /**
   * Account Number Max length: 10.
   */
  accountNumber: z.string().nullable().optional(),
  /**
   * Parent company member id
   */
  billingId: z.number().nullable().optional(),
  /**
   * Billing Company Max length: 50.
   */
  billingCompany: z.string().nullable().optional(),
  /**
   * Accounts contact first name Max length: 50.
   */
  accountsFirstName: z.string().nullable().optional(),
  /**
   * Accounts contact last name Max length: 50.
   */
  accountsLastName: z.string().nullable().optional(),
  /**
   * Billing Email Max length: 50.
   */
  billingEmail: z.string().nullable().optional(),
  /**
   * Accounts contact phone Max length: 50.
   */
  accountsPhone: z.string().nullable().optional(),
  /**
   * Alternative GL account of a Parent company if exists
   */
  billingCostCenter: z.string().nullable().optional(),
  /**
   * Alternative GL account
   */
  costCenter: z.string().nullable().optional(),
  /**
   * A price column name. Query ProductOptions to get a list of valid price column names.
   */
  priceColumn: z.string().nullable().optional(),
  /**
   * Percentage Off Price Tier. Price discount on top of PriceColumn. Max length: 100.
   */
  percentageOff: z.number().nullable().optional(),
  /**
   * Payment terms
   */
  paymentTerms: z.string().nullable().optional(),
  /**
   * Tax Status
   */
  taxStatus: z.string().nullable().optional(),
  /**
   * Taxt Number
   */
  taxNumber: z.string().nullable().optional(),
  /**
   * Credit Limit
   */
  creditLimit: z.number().nullable().optional(),
  /**
   * Balance Owing
   */
  balanceOwing: z.number().nullable().optional(),
  /**
   * Hold Status
   */
  onHold: z.boolean().nullable().optional(),
  /**
   * Group
   */
  group: z.string().nullable().optional(),
  /**
   * Subgroup
   */
  subGroup: z.string().nullable().optional(),
  /**
   * Stages
   */
  stages: z.string().nullable().optional(),
  /**
   * Accounting Integration Ids for Xero, QuickBooks Online and QuickBooks Desktop (readonly)
   */
  accountingIntegrationId: ContactAccountingIntegrationIdSchema.nullable().optional(),
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Created Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Modified Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * Is Active
   */
  isActive: z.boolean().nullable().optional(),
  /**
   * Company Max length: 250.
   */
  company: z.string().nullable().optional(),
  /**
   * First Name Max length: 250.
   */
  firstName: z.string().nullable().optional(),
  /**
   * Last Name Max length: 250.
   */
  lastName: z.string().nullable().optional(),
  /**
   * Job Title Max length: 250.
   */
  jobTitle: z.string().nullable().optional(),
  /**
   * A unique email address
   */
  email: z.string().nullable().optional(),
  /**
   * Website Max length: 50.
   */
  website: z.string().nullable().optional(),
  /**
   * Phone Max length: 50.
   */
  phone: z.string().nullable().optional(),
  /**
   * Fax Max length: 50.
   */
  fax: z.string().nullable().optional(),
  /**
   * Mobile Max length: 50.
   */
  mobile: z.string().nullable().optional(),
  /**
   * Address 1 Max length: 50.
   */
  address1: z.string().nullable().optional(),
  /**
   * Address 2 Max length: 50.
   */
  address2: z.string().nullable().optional(),
  /**
   * City Max length: 50.
   */
  city: z.string().nullable().optional(),
  /**
   * State Max length: 50.
   */
  state: z.string().nullable().optional(),
  /**
   * Post Code Max length: 50.
   */
  postCode: z.string().nullable().optional(),
  /**
   * Country Max length: 50.
   */
  country: z.string().nullable().optional(),
  /**
   * Billing/Postal Address 1 Max length: 50.
   */
  postalAddress1: z.string().nullable().optional(),
  /**
   * Billing/Postal Address 2 Max length: 50.
   */
  postalAddress2: z.string().nullable().optional(),
  /**
   * Billing/Postal City Max length: 50.
   */
  postalCity: z.string().nullable().optional(),
  /**
   * Billing/Postal Post Code Max length: 50.
   */
  postalPostCode: z.string().nullable().optional(),
  /**
   * Billing/Postal State Max length: 50.
   */
  postalState: z.string().nullable().optional(),
  /**
   * Billing/Postal Country Max length: 50.
   */
  postalCountry: z.string().nullable().optional(),
  /**
   * Notes Max length: 250.
   */
  notes: z.string().nullable().optional(),
  /**
   * Integration reference.
   */
  integrationRef: z.string().nullable().optional(),
  /**
   * Custom fields. The spec reflects this as an array of strings, but the API returns custom
   * fields keyed by name. Both shapes are accepted.
   */
  customFields: z
    .union([z.record(z.string(), z.unknown()), z.array(z.unknown())])
    .nullable()
    .optional(),
  /**
   * Secondary Contacts
   */
  secondaryContacts: z.array(ContactSecondaryContactSchema).nullable().optional()
});

export type Contact = z.infer<typeof ContactSchema>;

export const ContactCreateSchema = ContactSchema;

export type ContactCreate = z.infer<typeof ContactCreateSchema>;

export const ContactUpdateSchema = ContactSchema;

export type ContactUpdate = z.infer<typeof ContactUpdateSchema>;
