// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Cin7 Pay fees and payouts. https://api.cin7.com/api/Help#FeesAndPayouts
 */

export const PaymentFeeSchema = z.looseObject({
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Payment fee or payout reference, e.g. for fees we use "PMTFEE-{id}" and for payouts we
   * use the Orders_25
   */
  invoiceReference: z.string().nullable().optional(),
  /**
   * Description
   */
  description: z.string().nullable().optional(),
  /**
   * Payment Id from stripe
   */
  stripePaymentId: z.string().nullable().optional(),
  /**
   * Indicates whether the record is a Payment Fee or Payout.
   */
  transactionType: z.string().nullable().optional(),
  /**
   * Created Date in UTC, serialized as ISO 8601 (e.g. 2024-01-15T13:45:30Z). Format: UTC
   * date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Amount of the fee or payout
   */
  total: z.number().nullable().optional(),
  /**
   * Currency code (e.g. NZD, USD)
   */
  currency: z.string().nullable().optional(),
  /**
   * Predefined DR/CR accounting behavior
   */
  accountingTreatment: z.string().nullable().optional(),
  /**
   * Tax handling
   */
  taxTreatment: z.string().nullable().optional(),
  /**
   * Indicates whether the amount is net of settlement
   */
  isNetOfSettlement: z.boolean().nullable().optional()
});

export type PaymentFee = z.infer<typeof PaymentFeeSchema>;

export const PaymentPayoutSchema = PaymentFeeSchema;

export type PaymentPayout = z.infer<typeof PaymentPayoutSchema>;
