// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Payments. https://api.cin7.com/api/Help#Payments
 */

export const PaymentSchema = z.looseObject({
  /**
   * The unique Cin7 payment Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Created Date UTC: yyyy-MM-dd HH:mm:ss Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Modified Date UTC: yyyy-MM-dd HH:mm:ss Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * Payment Date UTC: yyyy-MM-dd HH:mm:ss Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  paymentDate: z.string().nullable().optional(),
  /**
   * Payment Amount
   */
  amount: z.number().nullable().optional(),
  /**
   * Payment Method
   */
  method: z.string().nullable().optional(),
  /**
   * Transaction Authorized
   */
  isAuthorized: z.boolean().nullable().optional(),
  /**
   * Transaction reference e.g. payment gateway transaction Id or ref Max length: 50.
   */
  transactionRef: z.string().nullable().optional(),
  /**
   * Comments Max length: 250.
   */
  comments: z.string().nullable().optional(),
  /**
   * The unique Cin7 sales order or purchase order Id.
   */
  orderId: z.number().nullable().optional(),
  /**
   * A unique sales order or purchase order reference. (Read-only) Max length: 30.
   */
  orderRef: z.string().nullable().optional(),
  /**
   * Payment imported ref
   */
  paymentImportedRef: z.string().nullable().optional(),
  /**
   * Batch Reference (Read-only)
   */
  batchReference: z.string().nullable().optional(),
  /**
   * Reconcile date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  reconcileDate: z.string().nullable().optional(),
  /**
   * Branch Id.
   */
  branchId: z.number().nullable().optional(),
  /**
   * Order Type. Documented values: Undefined, GenericOrder, SalesOrder, PreOrder,
   * ProductionJob, PurchaseOrder, PurchaseQuote, Quote, Adjustment, BatchOrSplitInvoice,
   * BinLocationTransfer, BranchTransfer, SupplierConsignment, Consignment, CreditNote,
   * SupplierCreditNote, Layby, BomMaster, SalesOrdersWithCartons.
   */
  orderType: z.string().nullable().optional()
});

export type Payment = z.infer<typeof PaymentSchema>;

export const PaymentCreateSchema = PaymentSchema;

export type PaymentCreate = z.infer<typeof PaymentCreateSchema>;

export const PaymentUpdateSchema = PaymentSchema;

export type PaymentUpdate = z.infer<typeof PaymentUpdateSchema>;
