// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Product options. https://api.cin7.com/api/Help#ProductOptions
 */

export const ProductOptionUomOptionSchema = z.looseObject({
  /**
   * The unique Cin7 UOM Option Id
   */
  id: z.number().nullable().optional(),
  /**
   * The unique Cin7 Product Option Id
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * The UOM option code
   */
  code: z.string().nullable().optional(),
  /**
   * Product option 1 (Example: Box)
   */
  option1: z.string().nullable().optional(),
  /**
   * Product option 2 (Example: XL)
   */
  option2: z.string().nullable().optional(),
  /**
   * Product option 3 (Example: Cotton)
   */
  option3: z.string().nullable().optional(),
  /**
   * UOM quantity
   */
  quantity: z.number().nullable().optional(),
  /**
   * The UOM option barcode
   */
  barcode: z.string().nullable().optional(),
  /**
   * The UOM option Supplier code
   */
  supplierCode: z.string().nullable().optional(),
  /**
   * Price Columns
   */
  priceColumns: z.array(z.string()).nullable().optional()
});

export type ProductOptionUomOption = z.infer<typeof ProductOptionUomOptionSchema>;

export const ProductOptionImageSchema = z.looseObject({
  /**
   * A link to an image
   */
  link: z.string().nullable().optional()
});

export type ProductOptionImage = z.infer<typeof ProductOptionImageSchema>;

export const ProductOptionCreateUomOptionSchema = z.looseObject({
  /**
   * The UOM option code
   */
  code: z.string().nullable().optional(),
  /**
   * Product option 1 (Example: Box) Max length: 50.
   */
  option1: z.string().nullable().optional(),
  /**
   * Product option 2 (Example: Color) Max length: 50.
   */
  option2: z.string().nullable().optional(),
  /**
   * Product option 3 (Example: Cotton) Max length: 50.
   */
  option3: z.string().nullable().optional(),
  /**
   * UOM quantity Required when creating a new UOM Max length: 2147483647.
   */
  quantity: z.number().nullable().optional(),
  /**
   * The UOM option barcode
   */
  barcode: z.string().nullable().optional(),
  /**
   * The UOM option Supplier code Max length: 50.
   */
  supplierCode: z.string().nullable().optional(),
  /**
   * Price Columns
   */
  priceColumns: z.array(z.string()).nullable().optional()
});

export type ProductOptionCreateUomOption = z.infer<typeof ProductOptionCreateUomOptionSchema>;

export const ProductOptionCreateSizeSchema = z.looseObject({
  /**
   * Size name. The size name must match one of the sizes in the Size Range assigned to the
   * product. Required when creating a new size. Max length: 20.
   */
  size: z.string().nullable().optional(),
  /**
   * A unique size code Max length: 20.
   */
  sizeCode: z.string().nullable().optional(),
  /**
   * A unique size barcode Max length: 20.
   */
  sizeBarcode: z.string().nullable().optional()
});

export type ProductOptionCreateSize = z.infer<typeof ProductOptionCreateSizeSchema>;

export const ProductOptionUpdateUomOptionSchema = z.looseObject({
  /**
   * The UOM Id Leave empty to create a new UOM or include to update an existing UOM
   */
  id: z.number().nullable().optional(),
  /**
   * The UOM option code
   */
  code: z.string().nullable().optional(),
  /**
   * Product option 1 (Example: Box) Max length: 50.
   */
  option1: z.string().nullable().optional(),
  /**
   * Product option 2 (Example: Color) Max length: 50.
   */
  option2: z.string().nullable().optional(),
  /**
   * Product option 3 (Example: Cotton) Max length: 50.
   */
  option3: z.string().nullable().optional(),
  /**
   * UOM quantity Required when creating a new UOM Max length: 2147483647.
   */
  quantity: z.number().nullable().optional(),
  /**
   * The UOM option barcode
   */
  barcode: z.string().nullable().optional(),
  /**
   * The UOM option Supplier code Max length: 50.
   */
  supplierCode: z.string().nullable().optional(),
  /**
   * Price Columns
   */
  priceColumns: z.array(z.string()).nullable().optional()
});

export type ProductOptionUpdateUomOption = z.infer<typeof ProductOptionUpdateUomOptionSchema>;

export const ProductOptionUpdateSizeSchema = z.looseObject({
  /**
   * Size Id. Leave empty to create a new size, or include to update an existing size.
   */
  sizeId: z.number().nullable().optional(),
  /**
   * Size name. The size name must match one of the sizes in the Size Range assigned to the
   * product. Required when creating a new size. Max length: 20.
   */
  size: z.string().nullable().optional(),
  /**
   * A unique size code Max length: 20.
   */
  sizeCode: z.string().nullable().optional(),
  /**
   * A unique size barcode Max length: 20.
   */
  sizeBarcode: z.string().nullable().optional()
});

export type ProductOptionUpdateSize = z.infer<typeof ProductOptionUpdateSizeSchema>;

export const ProductOptionSchema = z.looseObject({
  /**
   * The unique Cin7 Product Option Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Created Date UTC Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Modifie Date UTC Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * Product Option Status: Primary, Active or Disabled Documented values: Disabled, Primary,
   * Active.
   */
  status: z.string().nullable().optional(),
  /**
   * The unique Cin7 product id
   */
  productId: z.number().nullable().optional(),
  /**
   * [OBSOLETE] Use ProductOptionCode Max length: 20.
   */
  code: z.string().nullable().optional(),
  /**
   * [OBSOLETE] Use ProductOptionBarcode Max length: 13.
   */
  barcode: z.string().nullable().optional(),
  /**
   * The Product Option Code/SKU Max length: 20.
   */
  productOptionCode: z.string().nullable().optional(),
  /**
   * The Product Option Size Code/SKU Max length: 20.
   */
  productOptionSizeCode: z.string().nullable().optional(),
  /**
   * The Product Option Barcode Max length: 13.
   */
  productOptionBarcode: z.string().nullable().optional(),
  /**
   * The Product Option Size Barcode Max length: 13.
   */
  productOptionSizeBarcode: z.string().nullable().optional(),
  /**
   * Supplier code Max length: 20.
   */
  supplierCode: z.string().nullable().optional(),
  /**
   * Product option 1 (Example: Red) Max length: 50.
   */
  option1: z.string().nullable().optional(),
  /**
   * Product option 2 (Example: XL) Max length: 50.
   */
  option2: z.string().nullable().optional(),
  /**
   * Product option 3 (Example: Cotton) Max length: 50.
   */
  option3: z.string().nullable().optional(),
  /**
   * Product Option Weight
   */
  optionWeight: z.number().nullable().optional(),
  /**
   * Size
   */
  size: z.string().nullable().optional(),
  /**
   * Size Id
   */
  sizeId: z.number().nullable().optional(),
  /**
   * Retail Price
   */
  retailPrice: z.number().nullable().optional(),
  /**
   * Wholesale Price
   */
  wholesalePrice: z.number().nullable().optional(),
  /**
   * VIP Price
   */
  vipPrice: z.number().nullable().optional(),
  /**
   * Special Price
   */
  specialPrice: z.number().nullable().optional(),
  /**
   * Specials Start Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  specialsStartDate: z.string().nullable().optional(),
  /**
   * Number of days Specials last
   */
  specialDays: z.number().nullable().optional(),
  /**
   * Stock Available
   */
  stockAvailable: z.number().nullable().optional(),
  /**
   * Stock On Hand
   */
  stockOnHand: z.number().nullable().optional(),
  /**
   * UOM options
   */
  uomOptions: z.array(ProductOptionUomOptionSchema).nullable().optional(),
  /**
   * A product option image
   */
  image: ProductOptionImageSchema.nullable().optional(),
  /**
   * Price Columns
   */
  priceColumns: z.array(z.string()).nullable().optional()
});

export type ProductOption = z.infer<typeof ProductOptionSchema>;

export const ProductOptionCreateSchema = z.looseObject({
  /**
   * Documented values: Disabled, Primary, Active.
   */
  status: z.string().nullable().optional(),
  /**
   * The id of the Product this product option belongs to. Max length: 2147483647.
   */
  productId: z.number().nullable().optional(),
  /**
   * A unique Code for this product option. Max length: 20.
   */
  productOptionCode: z.string().nullable().optional(),
  /**
   * A unique barcode Max length: 20.
   */
  productOptionBarcode: z.string().nullable().optional(),
  /**
   * Max length: 20.
   */
  supplierCode: z.string().nullable().optional(),
  /**
   * Max length: 50.
   */
  option1: z.string().nullable().optional(),
  /**
   * Max length: 50.
   */
  option2: z.string().nullable().optional(),
  /**
   * Max length: 50.
   */
  option3: z.string().nullable().optional(),
  /**
   * The special price
   */
  specialPrice: z.number().nullable().optional(),
  /**
   * Start date for the speical price to apply Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  specialsStartDate: z.string().nullable().optional(),
  /**
   * How many days the special will run starting from the SpecialsStartDate
   */
  specialDays: z.number().nullable().optional(),
  /**
   * The option weight
   */
  optionWeight: z.number().nullable().optional(),
  /**
   * An array of unit of measures. Max length: 20.
   */
  uomOptions: z.array(ProductOptionCreateUomOptionSchema).nullable().optional(),
  priceColumns: z.array(z.string()).nullable().optional(),
  /**
   * Product option sizes. A size range id needs to be assigned to the product before
   * creating sizes. Max length: 20.
   */
  sizes: z.array(ProductOptionCreateSizeSchema).nullable().optional()
});

export type ProductOptionCreate = z.infer<typeof ProductOptionCreateSchema>;

export const ProductOptionUpdateSchema = z.looseObject({
  /**
   * Product Option Id
   */
  id: z.number().nullable().optional(),
  /**
   * Documented values: Disabled, Primary, Active.
   */
  status: z.string().nullable().optional(),
  /**
   * ProductOptionCode
   */
  productOptionCode: z.string().nullable().optional(),
  productOptionBarcode: z.string().nullable().optional(),
  supplierCode: z.string().nullable().optional(),
  /**
   * Max length: 50.
   */
  option1: z.string().nullable().optional(),
  /**
   * Max length: 50.
   */
  option2: z.string().nullable().optional(),
  /**
   * Max length: 50.
   */
  option3: z.string().nullable().optional(),
  /**
   * The special price
   */
  specialPrice: z.number().nullable().optional(),
  /**
   * Start date for the speical price to apply Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  specialsStartDate: z.string().nullable().optional(),
  /**
   * How many days the special will run starting from the SpecialsStartDate
   */
  specialDays: z.number().nullable().optional(),
  /**
   * The option weight
   */
  optionWeight: z.number().nullable().optional(),
  /**
   * An array of unit of measures. Max length: 20.
   */
  uomOptions: z.array(ProductOptionUpdateUomOptionSchema).nullable().optional(),
  priceColumns: z.array(z.string()).nullable().optional(),
  /**
   * Product option sizes. A size range id needs to be assigned to the product before
   * creating sizes. Max length: 20.
   */
  sizes: z.array(ProductOptionUpdateSizeSchema).nullable().optional()
});

export type ProductOptionUpdate = z.infer<typeof ProductOptionUpdateSchema>;
