// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Product categories. https://api.cin7.com/api/Help#ProductCategories
 */

export const ProductCategoryImageSchema = z.looseObject({
  /**
   * A link to an image
   */
  link: z.string().nullable().optional()
});

export type ProductCategoryImage = z.infer<typeof ProductCategoryImageSchema>;

export const ProductCategorySchema = z.looseObject({
  id: z.number().nullable().optional(),
  parentId: z.number().nullable().optional(),
  isActive: z.boolean().nullable().optional(),
  sort: z.number().nullable().optional(),
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  image: ProductCategoryImageSchema.nullable().optional()
});

export type ProductCategory = z.infer<typeof ProductCategorySchema>;

export const ProductCategoryCreateSchema = z.looseObject({
  /**
   * Max length: 50.
   */
  name: z.string().nullable().optional(),
  /**
   * Max length: 250.
   */
  description: z.string().nullable().optional(),
  /**
   * Parent category Id. 0 for top level. Default is 0. Max length: 2147483647.
   */
  parentId: z.number().nullable().optional(),
  /**
   * Max length: 2147483647.
   */
  sort: z.number().nullable().optional()
});

export type ProductCategoryCreate = z.infer<typeof ProductCategoryCreateSchema>;

export const ProductCategoryUpdateSchema = z.looseObject({
  /**
   * Max length: 2147483647.
   */
  id: z.number().nullable().optional(),
  /**
   * Max length: 50.
   */
  name: z.string().nullable().optional(),
  /**
   * Max length: 250.
   */
  description: z.string().nullable().optional(),
  /**
   * Category Id of the parent category. 0 for root category (or to unlink from parent). null
   * to not update. Max length: 2147483647.
   */
  parentId: z.number().nullable().optional(),
  /**
   * Max length: 2147483647.
   */
  sort: z.number().nullable().optional()
});

export type ProductCategoryUpdate = z.infer<typeof ProductCategoryUpdateSchema>;
