// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Products. https://api.cin7.com/api/Help#Products
 */

export const ProductImageSchema = z.looseObject({
  /**
   * A link to an image
   */
  link: z.string().nullable().optional()
});

export type ProductImage = z.infer<typeof ProductImageSchema>;

export const ProductProductOptionUomOptionSchema = z.looseObject({
  /**
   * The unique Cin7 UOM Option Id
   */
  id: z.number().nullable().optional(),
  /**
   * The unique Cin7 Product Option Id
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * The UOM option code
   */
  code: z.string().nullable().optional(),
  /**
   * Product option 1 (Example: Box)
   */
  option1: z.string().nullable().optional(),
  /**
   * Product option 2 (Example: XL)
   */
  option2: z.string().nullable().optional(),
  /**
   * Product option 3 (Example: Cotton)
   */
  option3: z.string().nullable().optional(),
  /**
   * UOM quantity
   */
  quantity: z.number().nullable().optional(),
  /**
   * The UOM option barcode
   */
  barcode: z.string().nullable().optional(),
  /**
   * The UOM option Supplier code
   */
  supplierCode: z.string().nullable().optional(),
  /**
   * Price Columns
   */
  priceColumns: z.array(z.string()).nullable().optional()
});

export type ProductProductOptionUomOption = z.infer<typeof ProductProductOptionUomOptionSchema>;

export const ProductProductOptionSchema = z.looseObject({
  /**
   * The unique Cin7 Product Option Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Created Date UTC Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Modifie Date UTC Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * Product Option Status: Primary, Active or Disabled Documented values: Disabled, Primary,
   * Active.
   */
  status: z.string().nullable().optional(),
  /**
   * The unique Cin7 product id
   */
  productId: z.number().nullable().optional(),
  /**
   * [OBSOLETE] Use ProductOptionCode Max length: 20.
   */
  code: z.string().nullable().optional(),
  /**
   * [OBSOLETE] Use ProductOptionBarcode Max length: 13.
   */
  barcode: z.string().nullable().optional(),
  /**
   * The Product Option Code/SKU Max length: 20.
   */
  productOptionCode: z.string().nullable().optional(),
  /**
   * The Product Option Size Code/SKU Max length: 20.
   */
  productOptionSizeCode: z.string().nullable().optional(),
  /**
   * The Product Option Barcode Max length: 13.
   */
  productOptionBarcode: z.string().nullable().optional(),
  /**
   * The Product Option Size Barcode Max length: 13.
   */
  productOptionSizeBarcode: z.string().nullable().optional(),
  /**
   * Supplier code Max length: 20.
   */
  supplierCode: z.string().nullable().optional(),
  /**
   * Product option 1 (Example: Red) Max length: 50.
   */
  option1: z.string().nullable().optional(),
  /**
   * Product option 2 (Example: XL) Max length: 50.
   */
  option2: z.string().nullable().optional(),
  /**
   * Product option 3 (Example: Cotton) Max length: 50.
   */
  option3: z.string().nullable().optional(),
  /**
   * Product Option Weight
   */
  optionWeight: z.number().nullable().optional(),
  /**
   * Size
   */
  size: z.string().nullable().optional(),
  /**
   * Size Id
   */
  sizeId: z.number().nullable().optional(),
  /**
   * Retail Price
   */
  retailPrice: z.number().nullable().optional(),
  /**
   * Wholesale Price
   */
  wholesalePrice: z.number().nullable().optional(),
  /**
   * VIP Price
   */
  vipPrice: z.number().nullable().optional(),
  /**
   * Special Price
   */
  specialPrice: z.number().nullable().optional(),
  /**
   * Specials Start Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  specialsStartDate: z.string().nullable().optional(),
  /**
   * Number of days Specials last
   */
  specialDays: z.number().nullable().optional(),
  /**
   * Stock Available
   */
  stockAvailable: z.number().nullable().optional(),
  /**
   * Stock On Hand
   */
  stockOnHand: z.number().nullable().optional(),
  /**
   * UOM options
   */
  uomOptions: z.array(ProductProductOptionUomOptionSchema).nullable().optional(),
  /**
   * A product option image
   */
  image: ProductImageSchema.nullable().optional(),
  /**
   * Price Columns
   */
  priceColumns: z.array(z.string()).nullable().optional()
});

export type ProductProductOption = z.infer<typeof ProductProductOptionSchema>;

export const ProductCreateDimensionsSchema = z.looseObject({
  /**
   * The product weight Max length: 999.
   */
  weight: z.number().nullable().optional(),
  /**
   * The product height Max length: 999.
   */
  height: z.number().nullable().optional(),
  /**
   * The product width Max length: 999.
   */
  width: z.number().nullable().optional(),
  /**
   * The product length Max length: 999.
   */
  length: z.number().nullable().optional(),
  /**
   * The product volume Max length: 999.
   */
  volume: z.number().nullable().optional()
});

export type ProductCreateDimensions = z.infer<typeof ProductCreateDimensionsSchema>;

export const ProductCreateProductOptionSchema = z.looseObject({
  /**
   * Code for this product option. If not set, an identifier will be generated for it. Max
   * length: 50.
   */
  productOptionCode: z.string().nullable().optional(),
  /**
   * Retail Price of the product Max length: 1.7976931348623157e+308.
   */
  retailPrice: z.number().nullable().optional(),
  /**
   * The product cost Max length: 1.7976931348623157e+308.
   */
  cost: z.number().nullable().optional()
});

export type ProductCreateProductOption = z.infer<typeof ProductCreateProductOptionSchema>;

export const ProductUpdateProductDimensionsSchema = z.looseObject({
  /**
   * Max length: 999.
   */
  weight: z.number().nullable().optional(),
  /**
   * Max length: 999.
   */
  height: z.number().nullable().optional(),
  /**
   * Max length: 999.
   */
  width: z.number().nullable().optional(),
  /**
   * Max length: 999.
   */
  length: z.number().nullable().optional(),
  /**
   * Max length: 999.
   */
  volume: z.number().nullable().optional()
});

export type ProductUpdateProductDimensions = z.infer<typeof ProductUpdateProductDimensionsSchema>;

export const ProductSchema = z.looseObject({
  /**
   * The unique Cin7 product Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Status: Inactive, Public, ShowInB2B, Internal Documented values: Inactive, Public,
   * ShowInB2B, Internal.
   */
  status: z.string().nullable().optional(),
  /**
   * Created Date UTC Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Modified Date UTC Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * The product style code
   */
  styleCode: z.string().nullable().optional(),
  /**
   * The product name Max length: 250.
   */
  name: z.string().nullable().optional(),
  /**
   * The product description
   */
  description: z.string().nullable().optional(),
  /**
   * Comma delimited list of custom tags
   */
  tags: z.string().nullable().optional(),
  /**
   * A list of images
   */
  images: z.array(ProductImageSchema).nullable().optional(),
  /**
   * PDF file
   */
  pdfUpload: z.string().nullable().optional(),
  /**
   * PDF description
   */
  pdfDescription: z.string().nullable().optional(),
  /**
   * The unique Cin7 supplier Id
   */
  supplierId: z.number().nullable().optional(),
  /**
   * The product brand name
   */
  brand: z.string().nullable().optional(),
  /**
   * Category
   */
  category: z.string().nullable().optional(),
  /**
   * Subcategory
   */
  subCategory: z.string().nullable().optional(),
  /**
   * Category IDs assigned to the product.
   */
  categoryIdArray: z.array(z.number()).nullable().optional(),
  /**
   * Selling Channels
   */
  channels: z.string().nullable().optional(),
  /**
   * The product weight Max length: 999.
   */
  weight: z.number().nullable().optional(),
  /**
   * The product height Max length: 999.
   */
  height: z.number().nullable().optional(),
  /**
   * The product width Max length: 999.
   */
  width: z.number().nullable().optional(),
  /**
   * The product length Max length: 999.
   */
  length: z.number().nullable().optional(),
  /**
   * The product volume Max length: 999.
   */
  volume: z.number().nullable().optional(),
  /**
   * The stock control type Documented values: Undefined, Batch, Machine, Serial, Labour,
   * FIFO.
   */
  stockControl: z.string().nullable().optional(),
  /**
   * Order Type: Order, Kit, Limited Stock, Buy To Order, Pre-order, Gift Voucher
   */
  orderType: z.string().nullable().optional(),
  /**
   * Product Type
   */
  productType: z.string().nullable().optional(),
  /**
   * Product Subtype
   */
  productSubtype: z.string().nullable().optional(),
  /**
   * Project Name
   */
  projectName: z.string().nullable().optional(),
  /**
   * A label for product option name 1 (Example: Color)
   */
  optionLabel1: z.string().nullable().optional(),
  /**
   * A label for product option name 2 (Example: Size)
   */
  optionLabel2: z.string().nullable().optional(),
  /**
   * A label for product option name 3 (Example: Fabric)
   */
  optionLabel3: z.string().nullable().optional(),
  /**
   * Sales account
   */
  salesAccount: z.string().nullable().optional(),
  /**
   * Purchase account
   */
  purchasesAccount: z.string().nullable().optional(),
  /**
   * Import Customs duty
   */
  importCustomsDuty: z.string().nullable().optional(),
  /**
   * Size range id
   */
  sizeRangeId: z.number().nullable().optional(),
  /**
   * Custom fields. The spec reflects this as an array of strings, but the API returns custom
   * fields keyed by name. Both shapes are accepted.
   */
  customFields: z
    .union([z.record(z.string(), z.unknown()), z.array(z.unknown())])
    .nullable()
    .optional(),
  /**
   * A list of product options
   */
  productOptions: z.array(ProductProductOptionSchema).nullable().optional()
});

export type Product = z.infer<typeof ProductSchema>;

export const ProductCreateSchema = z.looseObject({
  /**
   * The product name Max length: 250.
   */
  name: z.string().nullable().optional(),
  /**
   * Will default to Public if not set. Status: Public, Inactive, ShowInB2B, Internal
   * Documented values: Inactive, Public, ShowInB2B, Internal.
   */
  status: z.string().nullable().optional(),
  /**
   * The Product style code Max length: 250.
   */
  styleCode: z.string().nullable().optional(),
  /**
   * The product description Max length: 250.
   */
  description: z.string().nullable().optional(),
  /**
   * Will default to FIFO if not set. Stock control: FIFO, Batch, Machine, Serial, Labour
   * Documented values: Undefined, Batch, Machine, Serial, Labour, FIFO.
   */
  stockControl: z.string().nullable().optional(),
  /**
   * Will default to Order if not set. Order Type: Order, Kit, Limited Stock, Buy To Order,
   * Pre-order, Gift Voucher Documented values: Order, Kit, Limited Stock, Buy To Order,
   * Pre-order, Gift Voucher.
   */
  orderType: z.string().nullable().optional(),
  /**
   * The product brand name. Allow users to assign a brand name based on their preference.
   * This doesn’t need to be part of the existing list of brands present in the backend. Max
   * length: 250.
   */
  brand: z.string().nullable().optional(),
  /**
   * A label for the first product option (e.g., Color). Max length: 250.
   */
  optionLabel1: z.string().nullable().optional(),
  /**
   * A label for the second product option (e.g., Size). Max length: 250.
   */
  optionLabel2: z.string().nullable().optional(),
  /**
   * A label for the third product option (e.g., Fabric). Max length: 250.
   */
  optionLabel3: z.string().nullable().optional(),
  /**
   * The sales account associated with the product. Max length: 250.
   */
  salesAccount: z.string().nullable().optional(),
  /**
   * The purchase account associated with the product. Max length: 250.
   */
  purchasesAccount: z.string().nullable().optional(),
  /**
   * The import customs duty applicable to the product. Max length: 250.
   */
  importCustomsDuty: z.string().nullable().optional(),
  /**
   * Array of category IDs assigned to the product.
   */
  categoryIdArray: z.array(z.number()).nullable().optional(),
  /**
   * Dimensions of the product like weight, height, width, length, volume
   */
  dimensions: ProductCreateDimensionsSchema.nullable().optional(),
  /**
   * Prices and Costs of the product. *Only ONE Product Option* is supported at this time.
   * Max length: 1.
   */
  productOptions: z.array(ProductCreateProductOptionSchema).nullable().optional(),
  /**
   * The Id of the Size Range. This can be obtained from the GetSizeRanges Endpoint
   */
  sizeRangeId: z.number().nullable().optional()
});

export type ProductCreate = z.infer<typeof ProductCreateSchema>;

export const ProductUpdateSchema = z.looseObject({
  /**
   * Max length: 2147483647.
   */
  id: z.number().nullable().optional(),
  /**
   * Max length: 250.
   */
  name: z.string().nullable().optional(),
  /**
   * Will default to Public if not set. Status: Public, Inactive, ShowInB2B, Internal
   * Documented values: Inactive, Public, ShowInB2B, Internal.
   */
  status: z.string().nullable().optional(),
  /**
   * Max length: 250.
   */
  description: z.string().nullable().optional(),
  /**
   * Max length: 250.
   */
  styleCode: z.string().nullable().optional(),
  /**
   * The product brand name. Allow users to assign a brand name based on their preference.
   * This doesn’t need to be part of the existing list of brands present in the backend. Max
   * length: 250.
   */
  brand: z.string().nullable().optional(),
  /**
   * A label for the first product option (e.g., Color). Max length: 250.
   */
  optionLabel1: z.string().nullable().optional(),
  /**
   * A label for the second product option (e.g., Size). Max length: 250.
   */
  optionLabel2: z.string().nullable().optional(),
  /**
   * A label for the third product option (e.g., Fabric). Max length: 250.
   */
  optionLabel3: z.string().nullable().optional(),
  /**
   * The sales account associated with the product. Max length: 250.
   */
  salesAccount: z.string().nullable().optional(),
  /**
   * The purchase account associated with the product. Max length: 250.
   */
  purchasesAccount: z.string().nullable().optional(),
  /**
   * The import customs duty applicable to the product. Max length: 250.
   */
  importCustomsDuty: z.string().nullable().optional(),
  /**
   * The id of the Size Range available in Omni account.
   */
  sizeRangeId: z.number().nullable().optional(),
  /**
   * Array of category IDs assigned to the product.
   */
  categoryIdArray: z.array(z.number()).nullable().optional(),
  productDimensions: ProductUpdateProductDimensionsSchema.nullable().optional()
});

export type ProductUpdate = z.infer<typeof ProductUpdateSchema>;
