// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Production jobs. https://api.cin7.com/api/Help#ProductionJobs
 */

export const ProductionJobProductComponentSchema = z.looseObject({
  /**
   * The unique Cin7 ID
   */
  id: z.number().nullable().optional(),
  /**
   * Product ID
   */
  productId: z.number().nullable().optional(),
  /**
   * Product option ID
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * Component Type (Make, Use, Addon). Documented values: Undefined, Make, Use, Addon.
   */
  type: z.string().nullable().optional(),
  /**
   * Sort Order
   */
  sort: z.number().nullable().optional(),
  /**
   * Item Code
   */
  code: z.string().nullable().optional(),
  /**
   * Item Name
   */
  name: z.string().nullable().optional(),
  /**
   * Option 1
   */
  option1: z.string().nullable().optional(),
  /**
   * Option 2
   */
  option2: z.string().nullable().optional(),
  /**
   * Option 3
   */
  option3: z.string().nullable().optional(),
  /**
   * Notes
   */
  notes: z.string().nullable().optional(),
  /**
   * Due Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  dueDate: z.string().nullable().optional(),
  /**
   * Standard Qty
   */
  standardQty: z.number().nullable().optional(),
  /**
   * Actual quantity (Read-only)
   */
  actualQty: z.number().nullable().optional(),
  /**
   * Unit Cost
   */
  unitCost: z.number().nullable().optional()
});

export type ProductionJobProductComponent = z.infer<typeof ProductionJobProductComponentSchema>;

export const ProductionJobProductSchema = z.looseObject({
  /**
   * Product Components (Read-only)
   */
  components: z.array(ProductionJobProductComponentSchema).nullable().optional(),
  /**
   * The unique Cin7 ID
   */
  id: z.number().nullable().optional(),
  /**
   * Product ID
   */
  productId: z.number().nullable().optional(),
  /**
   * Product option ID
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * Component Type (Make, Use, Addon). Documented values: Undefined, Make, Use, Addon.
   */
  type: z.string().nullable().optional(),
  /**
   * Sort Order
   */
  sort: z.number().nullable().optional(),
  /**
   * Item Code
   */
  code: z.string().nullable().optional(),
  /**
   * Item Name
   */
  name: z.string().nullable().optional(),
  /**
   * Option 1
   */
  option1: z.string().nullable().optional(),
  /**
   * Option 2
   */
  option2: z.string().nullable().optional(),
  /**
   * Option 3
   */
  option3: z.string().nullable().optional(),
  /**
   * Notes
   */
  notes: z.string().nullable().optional(),
  /**
   * Due Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  dueDate: z.string().nullable().optional(),
  /**
   * Standard Qty
   */
  standardQty: z.number().nullable().optional(),
  /**
   * Actual quantity (Read-only)
   */
  actualQty: z.number().nullable().optional(),
  /**
   * Unit Cost
   */
  unitCost: z.number().nullable().optional()
});

export type ProductionJobProduct = z.infer<typeof ProductionJobProductSchema>;

export const ProductionJobSchema = z.looseObject({
  /**
   * A unique Job ID.
   */
  id: z.number().nullable().optional(),
  /**
   * Created date time. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Last modified date time. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * Due Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  dueDate: z.string().nullable().optional(),
  /**
   * Completed Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  completedDate: z.string().nullable().optional(),
  /**
   * Created by User ID.
   */
  createdBy: z.number().nullable().optional(),
  /**
   * Completed by User ID.
   */
  completedBy: z.number().nullable().optional(),
  /**
   * Is Approved (default: true)
   */
  isApproved: z.boolean().nullable().optional(),
  /**
   * Branch ID
   */
  branchId: z.number().nullable().optional(),
  /**
   * Company Max length: 250.
   */
  company: z.string().nullable().optional(),
  /**
   * Project Name
   */
  projectName: z.string().nullable().optional(),
  /**
   * Production Notes.
   */
  productionNotes: z.string().nullable().optional(),
  /**
   * The unique Job reference. Max length: 20.
   */
  reference: z.string().nullable().optional(),
  /**
   * The source
   */
  source: z.string().nullable().optional(),
  /**
   * Product Total
   */
  totalCost: z.number().nullable().optional(),
  /**
   * Custom Fields The spec reflects this as an array of strings, but the API returns custom
   * fields keyed by name. Both shapes are accepted.
   */
  customFields: z
    .union([z.record(z.string(), z.unknown()), z.array(z.unknown())])
    .nullable()
    .optional(),
  /**
   * Production Job Products.
   */
  products: z.array(ProductionJobProductSchema).nullable().optional()
});

export type ProductionJob = z.infer<typeof ProductionJobSchema>;

export const ProductionJobCreateSchema = ProductionJobSchema;

export type ProductionJobCreate = z.infer<typeof ProductionJobCreateSchema>;

export const ProductionJobUpdateSchema = ProductionJobSchema;

export type ProductionJobUpdate = z.infer<typeof ProductionJobUpdateSchema>;
