// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Sales orders. https://api.cin7.com/api/Help#SalesOrders
 */

export const SalesOrderLineItemStockMovementSchema = z.looseObject({
  batch: z.string().nullable().optional(),
  quantity: z.number().nullable().optional(),
  serial: z.string().nullable().optional()
});

export type SalesOrderLineItemStockMovement = z.infer<typeof SalesOrderLineItemStockMovementSchema>;

export const SalesOrderLineItemSchema = z.looseObject({
  /**
   * Product style code
   */
  styleCode: z.string().nullable().optional(),
  /**
   * Barcode/UPC. Note, if the product option barcode exists in Cin7, only quantity needs to
   * be included; all other fields are optional.
   */
  barcode: z.string().nullable().optional(),
  /**
   * An array of size quantities and codes e.g. Qty|Size|Code|Barcode. (Note this is
   * Read-only)
   */
  sizeCodes: z.string().nullable().optional(),
  /**
   * Line item comment
   */
  lineComments: z.string().nullable().optional(),
  /**
   * Unit Cost
   */
  unitCost: z.number().nullable().optional(),
  /**
   * Unit Price
   */
  unitPrice: z.number().nullable().optional(),
  /**
   * Uom Price of the product. To create/update UOM's use UomPrice instead of UnitPrice.
   */
  uomPrice: z.number().nullable().optional(),
  /**
   * Total line item discount
   */
  discount: z.number().nullable().optional(),
  /**
   * Uom Qty Ordered. To create/update UOM's use UomQtyOrdered instead of Qty.
   */
  uomQtyOrdered: z.number().nullable().optional(),
  /**
   * Uom Qty shipped/dispatched. This field is read-only. This is calculated from QtyShipped.
   */
  uomQtyShipped: z.number().nullable().optional(),
  /**
   * Uom Size. (Read-only)
   */
  uomSize: z.number().nullable().optional(),
  /**
   * Qty shipped/dispatched. This field is read-only. Populate 'DispatchedDate' to update
   * this field.
   */
  qtyShipped: z.number().nullable().optional(),
  /**
   * Holding Quantity (Read-only).
   */
  holdingQty: z.number().nullable().optional(),
  /**
   * Alternative GL Account Code. Omit to default to Product GL.
   */
  accountCode: z.string().nullable().optional(),
  /**
   * Documented values: Undefined, Batch, Machine, Serial, Labour, FIFO.
   */
  stockControl: z.string().nullable().optional(),
  /**
   * Dispatch quantities. (Read-only)
   */
  stockMovements: z.array(SalesOrderLineItemStockMovementSchema).nullable().optional(),
  /**
   * The unique Cin7 ID
   */
  id: z.number().nullable().optional(),
  /**
   * Created date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Transaction ID e.g. Sales Order Id, Quote Id or Purchase Order Id
   */
  transactionId: z.number().nullable().optional(),
  /**
   * Parent Line Item ID (Read-only)
   */
  parentId: z.number().nullable().optional(),
  /**
   * Product ID (Read-only)
   */
  productId: z.number().nullable().optional(),
  /**
   * The product option ID (Optional); ProductOptionId or Code should be specified to link a
   * product to the line item.
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * Integration reference
   */
  integrationRef: z.string().nullable().optional(),
  /**
   * Sort (or sequence) of line items
   */
  sort: z.number().nullable().optional(),
  code: z.string().nullable().optional(),
  /**
   * Item name
   */
  name: z.string().nullable().optional(),
  /**
   * Option 1
   */
  option1: z.string().nullable().optional(),
  /**
   * Option 2
   */
  option2: z.string().nullable().optional(),
  /**
   * Option 3
   */
  option3: z.string().nullable().optional(),
  /**
   * Quantity
   */
  qty: z.number().nullable().optional()
});

export type SalesOrderLineItem = z.infer<typeof SalesOrderLineItemSchema>;

export const SalesOrderAccountingAttributesSchema = z.looseObject({
  /**
   * The date an invoice was imported to a Cin7 accounts accounting software. Format: UTC
   * date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  importDate: z.string().nullable().optional(),
  /**
   * This refers to the Accounting Invoice Status of the order in Cin7. Documented values:
   * NotImported, Imported, DoNotImport, Error.
   */
  accountingImportStatus: z.string().nullable().optional()
});

export type SalesOrderAccountingAttributes = z.infer<typeof SalesOrderAccountingAttributesSchema>;

export const SalesOrderSchema = z.looseObject({
  /**
   * Invoice date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  invoiceDate: z.string().nullable().optional(),
  /**
   * Invoice number. This is a read-only field. It is updated when an invoice date is
   * provided.
   */
  invoiceNumber: z.number().nullable().optional(),
  /**
   * The date that the order was fully dispatched. Format: UTC date-time
   * (yyyy-MM-ddTHH:mm:ssZ).
   */
  dispatchedDate: z.string().nullable().optional(),
  /**
   * Logistics Carrier
   */
  logisticsCarrier: z.string().nullable().optional(),
  /**
   * Logistics Status
   */
  logisticsStatus: z.number().nullable().optional(),
  /**
   * Edi Status
   */
  ediStatus: z.number().nullable().optional(),
  /**
   * Distribution Branch
   */
  distributionBranchId: z.number().nullable().optional(),
  /**
   * Department Number
   */
  departmentNumber: z.string().nullable().optional(),
  /**
   * Store Location Number
   */
  storeLocationNumber: z.string().nullable().optional(),
  /**
   * Distribution Center
   */
  distributionCenter: z.string().nullable().optional(),
  /**
   * Line Items
   */
  lineItems: z.array(SalesOrderLineItemSchema).nullable().optional(),
  /**
   * Set to true to void an order; note this behaviour is irreversible.
   */
  isVoid: z.boolean().nullable().optional(),
  /**
   * This is for the Accounting Integration
   */
  accountingAttributes: SalesOrderAccountingAttributesSchema.nullable().optional(),
  /**
   * Status - (Read-only) Documented values: Draft, Approved, Void.
   */
  status: z.string().nullable().optional(),
  /**
   * Stage: New, Awaiting Payment, Declined, Dispatched, Processing, On Hold (default: New)
   */
  stage: z.string().nullable().optional(),
  /**
   * The CRM contact email of a customer in an order Max length: 250.
   */
  memberEmail: z.string().nullable().optional(),
  /**
   * Member Cost Center (Alternative GL Account).
   */
  memberCostCenter: z.string().nullable().optional(),
  /**
   * The member Alternative Tax Rate.
   */
  memberAlternativeTaxRate: z.string().nullable().optional(),
  /**
   * Cost Center (Alternative GL Account).
   */
  costCenter: z.string().nullable().optional(),
  /**
   * Alternative Tax Rate.
   */
  alternativeTaxRate: z.string().nullable().optional(),
  /**
   * Estimated Delivery Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  estimatedDeliveryDate: z.string().nullable().optional(),
  /**
   * The unique Cin7 user Id of the sales person.
   */
  salesPersonId: z.number().nullable().optional(),
  /**
   * Made obsolete. This value will be null in the response. Max length: 250.
   */
  salesPersonEmail: z.string().nullable().optional(),
  /**
   * Payment terms
   */
  paymentTerms: z.string().nullable().optional(),
  /**
   * Customer purchase order reference
   */
  customerOrderNo: z.string().nullable().optional(),
  /**
   * Voucher code Max length: 30.
   */
  voucherCode: z.string().nullable().optional(),
  /**
   * Delivery instructions e.g. Leave at the door, beware the dog. Max length: 2000.
   */
  deliveryInstructions: z.string().nullable().optional(),
  /**
   * Order cancellation date - (Read-only) Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  cancellationDate: z.string().nullable().optional(),
  /**
   * Last modified date of Cost of Good Sold(COGS) - (Read-only) Format: UTC date-time
   * (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedCOGSDate: z.string().nullable().optional(),
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Created date. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Last modified date. Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * The ID for the User who created the Transaction.
   */
  createdBy: z.number().nullable().optional(),
  /**
   * The ID for the User who processed the Transaction.
   */
  processedBy: z.number().nullable().optional(),
  /**
   * Is Approved (default: true)
   */
  isApproved: z.boolean().nullable().optional(),
  /**
   * A unique order reference (leave blank to auto-generate in an insert). Max length: 30.
   */
  reference: z.string().nullable().optional(),
  /**
   * The Customer Id (Optional). MemberId or MemberEmail should be specified to link a member
   * to the order.
   */
  memberId: z.number().nullable().optional(),
  /**
   * Contact first name Max length: 250.
   */
  firstName: z.string().nullable().optional(),
  /**
   * Contact last name Max length: 250.
   */
  lastName: z.string().nullable().optional(),
  /**
   * Contact company Max length: 250.
   */
  company: z.string().nullable().optional(),
  /**
   * Contact email address, could be different from MemberEmail assigned to the order Max
   * length: 250.
   */
  email: z.string().nullable().optional(),
  /**
   * Contact phone Max length: 50.
   */
  phone: z.string().nullable().optional(),
  /**
   * Contact mobile Max length: 50.
   */
  mobile: z.string().nullable().optional(),
  /**
   * Contact fax Max length: 50.
   */
  fax: z.string().nullable().optional(),
  /**
   * Delivery recipient first name Max length: 250.
   */
  deliveryFirstName: z.string().nullable().optional(),
  /**
   * Delivery recipient last name Max length: 250.
   */
  deliveryLastName: z.string().nullable().optional(),
  /**
   * Delivery recipient company name Max length: 250.
   */
  deliveryCompany: z.string().nullable().optional(),
  /**
   * Delivery address 1 Max length: 250.
   */
  deliveryAddress1: z.string().nullable().optional(),
  /**
   * Delivery address 2 Max length: 250.
   */
  deliveryAddress2: z.string().nullable().optional(),
  /**
   * Delivery address city Max length: 250.
   */
  deliveryCity: z.string().nullable().optional(),
  /**
   * Delivery address state Max length: 250.
   */
  deliveryState: z.string().nullable().optional(),
  /**
   * Delivery address postcode Max length: 250.
   */
  deliveryPostalCode: z.string().nullable().optional(),
  /**
   * Delivery address country Max length: 250.
   */
  deliveryCountry: z.string().nullable().optional(),
  /**
   * Billing recipient first name Max length: 250.
   */
  billingFirstName: z.string().nullable().optional(),
  /**
   * Billing recipient last name Max length: 250.
   */
  billingLastName: z.string().nullable().optional(),
  /**
   * The billing company name Max length: 250.
   */
  billingCompany: z.string().nullable().optional(),
  /**
   * Billing address 1 Max length: 250.
   */
  billingAddress1: z.string().nullable().optional(),
  /**
   * Billing address 2 Max length: 250.
   */
  billingAddress2: z.string().nullable().optional(),
  /**
   * Billing address city Max length: 250.
   */
  billingCity: z.string().nullable().optional(),
  /**
   * Billing address postcode Max length: 250.
   */
  billingPostalCode: z.string().nullable().optional(),
  /**
   * Billing address state Max length: 250.
   */
  billingState: z.string().nullable().optional(),
  /**
   * Billing address country Max length: 250.
   */
  billingCountry: z.string().nullable().optional(),
  /**
   * Branch Id. Not updatable if SO Dispatched or PO Received. Defaults to "Main Branch" ID
   * when omitted.
   */
  branchId: z.number().nullable().optional(),
  /**
   * Branch email Max length: 250.
   */
  branchEmail: z.string().nullable().optional(),
  /**
   * Project Name
   */
  projectName: z.string().nullable().optional(),
  /**
   * Shipping tracking code Max length: 50.
   */
  trackingCode: z.string().nullable().optional(),
  /**
   * Internal comment
   */
  internalComments: z.string().nullable().optional(),
  /**
   * Product Total Only
   */
  productTotal: z.number().nullable().optional(),
  /**
   * Total cost of delivery charges
   */
  freightTotal: z.number().nullable().optional(),
  /**
   * Freight/carrier description
   */
  freightDescription: z.string().nullable().optional(),
  /**
   * Surcharge
   */
  surcharge: z.number().nullable().optional(),
  /**
   * Surcharge description
   */
  surchargeDescription: z.string().nullable().optional(),
  /**
   * Total overall discount
   */
  discountTotal: z.number().nullable().optional(),
  /**
   * The discount description
   */
  discountDescription: z.string().nullable().optional(),
  /**
   * Order total includes Product Total, Freight Total, Discount Total, Surcharge Total, and
   * Tax
   */
  total: z.number().nullable().optional(),
  /**
   * The three-character ISO currency code e.g. NZD. Omit to use account default.
   */
  currencyCode: z.string().nullable().optional(),
  /**
   * The currency rate. If no rate is specified (i.e. zero or null), Cin7 will lookup the
   * currency rate from the start of the day as provided by our 3rd party currency service.
   */
  currencyRate: z.number().nullable().optional(),
  /**
   * The currency symbol e.g. $. This field is automatically populate based on currency code.
   */
  currencySymbol: z.string().nullable().optional(),
  /**
   * Tax Status: Incl, Excl, Exempt. Omit to use account default. Documented values:
   * Undefined, Incl, Excl, Exempt.
   */
  taxStatus: z.string().nullable().optional(),
  /**
   * Tax Rate e.g. 15. If different from your default tax rate you will need to set the
   * CostCenter or Alternative tax rate field as well. Max length: 100.
   */
  taxRate: z.number().nullable().optional(),
  /**
   * The source of the Transaction. This field is read-only.
   */
  source: z.string().nullable().optional(),
  /**
   * Custom fields. The spec reflects this as an array of strings, but the API returns custom
   * fields keyed by name. Both shapes are accepted.
   */
  customFields: z
    .union([z.record(z.string(), z.unknown()), z.array(z.unknown())])
    .nullable()
    .optional()
});

export type SalesOrder = z.infer<typeof SalesOrderSchema>;

export const SalesOrderCreateSchema = SalesOrderSchema;

export type SalesOrderCreate = z.infer<typeof SalesOrderCreateSchema>;

export const SalesOrderUpdateSchema = SalesOrderSchema;

export type SalesOrderUpdate = z.infer<typeof SalesOrderUpdateSchema>;
