// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Serial numbers. https://api.cin7.com/api/Help#SerialNumbers
 */

export const SerialNumberSchema = z.looseObject({
  /**
   * The unique Cin7 Id.
   */
  id: z.number().nullable().optional(),
  /**
   * Serial number
   */
  serialnumber: z.string().nullable().optional(),
  /**
   * The unique Cin7 product Id.
   */
  productId: z.number().nullable().optional(),
  /**
   * The unique product option Id.
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * The ID for the respective line item.
   */
  lineItemId: z.number().nullable().optional(),
  /**
   * The unique Cin7 price option code.
   */
  code: z.string().nullable().optional(),
  /**
   * Holding Group
   */
  holdingGroup: z.string().nullable().optional(),
  /**
   * The unique Cin7 member Id of the branch.
   */
  branchId: z.number().nullable().optional(),
  /**
   * Available
   */
  available: z.number().nullable().optional()
});

export type SerialNumber = z.infer<typeof SerialNumberSchema>;
