// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Size ranges. https://api.cin7.com/api/Help#SizeRanges
 */

export const SizeRangeSchema = z.looseObject({
  sizeRangeName: z.string().nullable().optional(),
  sizes: z.array(z.string()).nullable().optional(),
  id: z.number().nullable().optional()
});

export type SizeRange = z.infer<typeof SizeRangeSchema>;
