// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Stock levels. https://api.cin7.com/api/Help#Stock
 */

export const StockSchema = z.looseObject({
  /**
   * The unique Cin7 product Id.
   */
  productId: z.number().nullable().optional(),
  /**
   * The Product Option Id
   */
  productOptionId: z.number().nullable().optional(),
  /**
   * Last Transaction Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  modifiedDate: z.string().nullable().optional(),
  /**
   * The style code.
   */
  styleCode: z.string().nullable().optional(),
  /**
   * The unique code i.e. SKU
   */
  code: z.string().nullable().optional(),
  /**
   * Barcode i.e. UPC
   */
  barcode: z.string().nullable().optional(),
  /**
   * The unique Cin7 branch Id.
   */
  branchId: z.number().nullable().optional(),
  /**
   * The branch name.
   */
  branchName: z.string().nullable().optional(),
  /**
   * The product name
   */
  productName: z.string().nullable().optional(),
  /**
   * Product option 1 (example: Red) Max length: 50.
   */
  option1: z.string().nullable().optional(),
  /**
   * Product option 2 (example: XL) Max length: 50.
   */
  option2: z.string().nullable().optional(),
  /**
   * Product option 3 (example: Cotton) Max length: 50.
   */
  option3: z.string().nullable().optional(),
  /**
   * Size (mainly for clothing when color size grid module is used)
   */
  size: z.string().nullable().optional(),
  /**
   * Available to Sell (StockOnHand - OpenSales)
   */
  available: z.number().nullable().optional(),
  /**
   * The stock on hand (SOH)
   */
  stockOnHand: z.number().nullable().optional(),
  /**
   * The open sales quantity i.e. The number of stock items on order.
   */
  openSales: z.number().nullable().optional(),
  /**
   * Inbound purchase order quantity
   */
  incoming: z.number().nullable().optional(),
  /**
   * Virtual stock for Kit products, zero for non-kit products
   */
  virtual: z.number().nullable().optional(),
  /**
   * Holding stock.
   */
  holding: z.number().nullable().optional()
});

export type Stock = z.infer<typeof StockSchema>;
