// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Users. https://api.cin7.com/api/Help#Users
 */

export const UserSchema = z.looseObject({
  /**
   * The user ID.
   */
  id: z.number().nullable().optional(),
  /**
   * The status of the User
   */
  isActive: z.boolean().nullable().optional(),
  /**
   * The user first name.
   */
  firstName: z.string().nullable().optional(),
  /**
   * The user last name.
   */
  lastName: z.string().nullable().optional(),
  /**
   * The user job title.
   */
  jobTitle: z.string().nullable().optional(),
  /**
   * The user email.
   */
  email: z.string().nullable().optional()
});

export type User = z.infer<typeof UserSchema>;
