// Generated by src/scripts/cin7-omni-codegen.ts from the Cin7 Omni OpenAPI spec.
// Run `yarn codegen:cin7-omni` to regenerate. Do not edit by hand.

import { z } from 'zod';

/**
 * Vouchers. https://api.cin7.com/api/Help#Voucher
 */

export const VoucherSchema = z.looseObject({
  /**
   * Voucher Created Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  createdDate: z.string().nullable().optional(),
  /**
   * Status - Active: voucher has balance, Inactive: already fully redeemed
   */
  status: z.string().nullable().optional(),
  /**
   * Voucher Code
   */
  code: z.string().nullable().optional(),
  /**
   * Voucher Type
   */
  type: z.string().nullable().optional(),
  /**
   * Promotion Description
   */
  description: z.string().nullable().optional(),
  /**
   * Voucher Expiry Date Format: UTC date-time (yyyy-MM-ddTHH:mm:ssZ).
   */
  expiryDate: z.string().nullable().optional(),
  /**
   * Voucher Amount
   */
  amount: z.number().nullable().optional(),
  /**
   * Customer ID of which voucher is assigned to
   */
  customerID: z.number().nullable().optional(),
  /**
   * Customer Email of which voucher is assigned to
   */
  customerEmail: z.string().nullable().optional(),
  /**
   * Count on how many times the voucher has been redeemed. Only makes sense when
   * RedeemedCountLimit=1
   */
  redeemedCount: z.number().nullable().optional(),
  /**
   * Limit on how many times the voucher can be fully redeemed, should always be 1 unless
   * modified from backend. Cin7 vouchers don't have limit counts on partial redemptions as
   * long as they have balance left.
   */
  redeemedCountLimit: z.number().nullable().optional(),
  /**
   * Voucher Redeemed Amount
   */
  redeemedAmount: z.number().nullable().optional()
});

export type Voucher = z.infer<typeof VoucherSchema>;
